### ISSUE TITLE
Idle channels sometimes fails RPCs with UNAVAILABLE status

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [grpc/grpc#11043]
When a gRPC channel goes idle, the first request started after it went idle will sometimes fail with status UNAVAILABLE. [This doesn't seem to be in line with the documented cases for UNAVAILABLE status](https://github.com/grpc/grpc/blob/99f20dbef8d812d468a54b58b2c55c28ea31cc54/doc/statuscodes.md), and since UNAVAILABLE is not a retriable status, implementing correct application-level semantics are more difficult.

Why does the Core say UNAVAILABLE when it doesn't have recent-in-time link-layer evidence to believe that the remote host is UNAVAILABLE? Or is there something I'm misunderstanding about channels going idle?

**Comment by marshallbrekka** [comment]
Hope this is helpful, I was debugging this issue (or one like it) for the ruby and python clients, and captured trace logs of the error occurring.

## Test Method
The test is pretty simple
1. Issue first RPC
2. Restart server
3. Issue second RPC

I did this manually by having the client sleep 15 seconds between RPCs, and manually restarting the server between calls.

The tests were run from the [ruby:2.3.1](https://hub.docker.com/r/library/ruby/tags/2.3.1/) and [python:3.5.2](https://hub.docker.com/r/library/python/tags/3.5.2/) docker images.

The test used the helloworld example from the grpc repo, with modified [ruby](https://gist.github.com/marshallbrekka/382e18317df71801b06e003ac227b79a) and [python](https://gist.github.com/marshallbrekka/7dbc7e7eb65c5701149be2ab01b1a815) clients, run with the environment vars
- `GRPC_TRACE=connectivity_state,channel,http,tcp`
-  `GRPC_VERBOSITY=debug`

The problem exists for the [ruby gem version 1.2.5](https://rubygems.org/gems/grpc/versions/1.2.5), and the [python package version 1.3.0](https://pypi.python.org/pypi/grpcio/1.3.0), however building the [ruby gem from source on 1.3.1](https://rubygems.org/gems/wearefair-grpc/versions/1.3.1.pre.c) does not contain the issue (building from source on 1.2.5 still does).

Building python from source on 1.3.1 still failed, which lead me to believe that [this PR](https://github.com/grpc/grpc/pull/10670) potentially had the side effect of fixing the issue for Ruby.

## Logs
The logs have been annotated with markers of significant events, all prefixed by `### NOTE`.

- [Ruby: 1.2.5 - FAIL](https://gist.github.com/marshallbrekka/08025c5c60cf3453a60f0299cdd3b66a)
- [Ruby: 1.3.1 - SUCCESS](https://gist.github.com/marshallbrekka/8b327256c4c57e4a8d1847fe6c47c1b7)
- [Python: 1.3.0 - FAIL](https://gist.github.com/marshallbrekka/abfd4b5a08de8c78f15cef7ad304d61d)

**Comment by nathanielmanistaatgoogle** [comment]
When you say "manually restarting the server", what do you mean exactly? Invoking the server's `stop` method and properly shutting it down? Sending a signal to server process? If a signal, which signal?

Thank you for the legwork!

**Comment by marshallbrekka** [comment]
Roughly this

```
$ ruby greeter_client.rb &
$ ruby greeter_server.rb
# watch for log from server receiving request
<ctrl-c>
$ ruby greeter_server.rb
```

I was able to reproduce the issue using both `ctrl-c`, and `kill -9 <pid>` against the server.

**Comment by marshallbrekka** [comment]
FWIW I could also reproduce the issue by running a client pod on K8 that looped forever, issuing requests every 15 seconds, and a deployment of 2 server pods, telling K8 to kill one pod at a time, so that there was always at least one healthy pod available.

**Comment by marshallbrekka** [comment]
Another data point: I couldn't reproduce the issue for python when building from source on master, but it looks like a lot of the networking internals in core have changed between v1.3.x and master.

**Comment by sulliwane** [comment]
Same error here:

**Client**:
- **grpcio@1.3.0**
- python 3.6

**Server**:
- grpc@1.3.0
- node 6.9

**Client error message:**
```
  File "/home/project/venv/lib/python3.6/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Endpoint read failed)>
```

**Comment by marshallbrekka** [comment]
verified issue is no longer present (for my test case) on ruby grpc-1.3.4 and python grpcio-1.3.5

**Comment by vetyy** [comment]
Hello I can still simulate this problem using python '3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]' , grpcio==1.3.5, Ubuntu 16.04.2 LTS

If I edit kpayson64 ReconnectTest and put for loop around test, lets say for _ in range(2000) it will randomly fail sometimes after 10 iterations sometimes after 500+.

What I am doing in my code is, I will create grpc.insecure_channel in setUpClass once, then for each setUp / tearDown I will create server, start it, stop it, delete server while running 20+ unittests per class and having 30 classes it almost always fails my pipeline with this exception.

**Comment by kpayson64** [comment]
Fixed by #11154

**Comment by fho** [comment]
Could it be that the problem still exist in the PHP client?
We are getting `Sisu\Grpc\Exception\GRPCException: Endpoint read failed` errors on the client on long living and (often) idle connections

**Comment by wenerme** [comment]
PHP with newest client still has this problem.

**Comment by fho** [comment]
@wenbozhu The ticket is labeled with `lang/all wrapped languages`.
The issue still exist in the PHP-Client but the ticket was already closed.
Should it be reopened?

**Comment by apolcyn** [comment]
@ZhouyihaiDing are you able to investigate this issue as it affects PHP?

**Comment by ZhouyihaiDing** [comment]
Sorry for the delay. Start looking into this in PHP.

**Comment by MitchDart** [comment]
I am having this issue in C# dotnet core. If a channel idles for long I get this exception.

**Comment by jtattermusch** [comment]
@MitchDart can you  provide more details about the issue you are seeing? (the usual info: platform, gRPC version, any other additional that would help reproducing etc.)

**Comment by jtattermusch** [comment]
@MitchDart I think the problem was resolved by https://github.com/grpc/grpc/pull/11021 (available in v1.3.5+). Are you seeing evidence that contradicts that?

**Comment by MitchDart** [comment]
@jtattermusch It has been a rough few days but I believe this is because of my current setup. I am using Grpc 1.8.3 in C#. I am using Kubernetes pods to host all my clients and servers in a microservice architecture. I believe the problem is because each kubernetes service has multiple pods meaning that the dns remains the same but the IP address changes continuously. So these idle channels simply "loose" its connection. So I decided to rather construct a new channel for each "scope" of work and destroy the channel afterwards using ShutdownAsync. The problem is ShutdownAsync takes around 12 seconds to finish !? This however seemed to solve the "Unavailable" problem however I get Status(StatusCode=Unknown, Detail="Stream removed") instead.

**Comment by jtattermusch** [comment]
ShutdownAsync taking that long can be an indication of some objects (calls, channels, ... ) not being cleaned up properly).
have you tried GRPC_VERBOSITY=debug and GRPC_TRACE=....    from https://github.com/grpc/grpc/blob/master/doc/environment_variables.md?

**Comment by MitchDart** [comment]
Thanks @jtattermusch, I will check that out and let you know. Just two quick questions maybe you can help me with.

1) Unary async calls are just awaited and stream calls are disposed with "using". Is there anything else I need to do to clean up the calls naturally? I can't seem to find anything in the samples.

2) Do you think setting up channels on a per scope basis is better than long lived channels where IP address could change during an IDLE state?

Thanks for your help, its much appreciated.

**Comment by jtattermusch** [comment]
1.  the native objects held by client-side call objects will be cleaned up when status is received from server and you have no pending operations on the call.  What Dispose() does is that it cancels the call if it hasn't finished yet, which results in status from server being delivered soon afterward (and the call is cleaned up).
With streaming calls you should always finish reading the response stream (MoveNext()) until the call finishes successfully or you get RpcException with status - abandoning the reponse stream can lead to call not being cleaned up properly.

2. That really depends on your application. In general, short lived channels have more overhead (creating a TCP connection) but you of course cannot have streaming calls survive things like change of backend's IP (as you seem to be describing). For long-lived streaming calls, you should always have a way to terminate the call gracefully and start a new one (that's necessary for things like loadbalancing to work properly).

**Comment by congdufs** [comment]
@nathanielmanistaatgoogle @marshallbrekka When a gRPC channel goes idle, the first request started after it went idle will fail with Error Domain=io.grpc Code=2 "Stream removed" UserInfo={NSLocalizedDescription=Stream removed, io.grpc.TrailersKey={}}, do you have any idea? Thank you very much.
