### ISSUE TITLE
Multiple h2_full_nosec_test tests failed on windows-worker3 with possible port server issues

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12595]
It looks like this test failed to reach a server:

`c_windows_opt_native.cmake/build/Release/h2_full_nosec_test.exe filter_call_init_fails`

shows output:

```
D0915 02:38:03.161000000  1932 test_config.c:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0915 02:38:03.163000000  1932 dns_resolver.c:301] Using native dns resolver
I0915 02:38:03.163000000  1932 filter_call_init_fails.c:513] Testing SERVER_CHANNEL filter.
I0915 02:38:03.163000000  1932 filter_call_init_fails.c:48] Running test: filter_call_init_fails/chttp2/fullstack
I0915 02:38:03.719000000  1932 filter_call_init_fails.c:517] Testing CLIENT_CHANNEL / CLIENT_DIRECT_CHANNEL filter.
I0915 02:38:03.719000000  1932 filter_call_init_fails.c:48] Running test: filter_call_init_fails/chttp2/fullstack
E0915 02:38:04.754000000  1932 channel.c:295] call_create: {"created":"@1505443084.754000000","description":"Call creation failed","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\surface\call.c","file_line":299,"referenced_errors":[{"created":"@1505443084.754000000","description":"access denied","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\test\core\end2end\tests\filter_call_init_fails.c","file_line":406,"grpc_status":7}]}
I0915 02:38:04.755000000  1932 filter_call_init_fails.c:522] Testing CLIENT_SUBCHANNEL filter.
I0915 02:38:04.755000000  1932 filter_call_init_fails.c:48] Running test: filter_call_init_fails/chttp2/fullstack
D0915 02:38:06.780000000  1932 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443086.780000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443085.780000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443085.780000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443086.780000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:38:09.950000000  1932 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443089.950000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443088.935000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443088.935000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443089.950000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
E0915 02:38:12.174000000  1932 filter_call_init_fails.c:354] assertion failed: status == GRPC_STATUS_PERMISSION_DENIED
Abort handler called.
*** 0: 0000000001422EBC  - 0000000000000000
*** 1: 0000000001422B0D  - 0000000000000000
*** 2: 000000006DC44672 abort - 000000006DC44640
*** 3: 00000000013BB3F6 abort - 000000006DC44640
*** 4: 00000000013BAA12 abort - 000000006DC44640
*** 5: 00000000013B1CB4 abort - 000000006DC44640
*** 6: 00000000013B118F abort - 000000006DC44640
*** 7: 000000000142D076 abort - 000000006DC44640
*** 8: 0000000076A5336A BaseThreadInitThunk - 0000000076A53358
*** 9: 0000000076F89902 RtlInitializeExceptionChain - 0000000076F8989F
*** 10: 0000000076F898D5 RtlInitializeExceptionChain - 0000000076F8989F
```

Other tests on the same machine look like they have possibly related errors:

`c_windows_opt_native.cmake/build/Release/h2_full_test.exe ping_pong_streaming`

shows output:

```
Failure
Stacktrace

c:38] Running test: test_pingpong_streaming/chttp2/fullstack
I0915 02:37:49.617000000  8292 ping_pong_streaming.c:38] Running test: test_pingpong_streaming/chttp2/fullstack
I0915 02:37:49.680000000  8292 ping_pong_streaming.c:38] Running test: test_pingpong_streaming/chttp2/fullstack
I0915 02:37:50.323000000  8292 ping_pong_streaming.c:38] Running test: test_pingpong_streaming/chttp2/fullstack
D0915 02:37:52.379000000  8292 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443072.379000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443071.348000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443071.348000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443072.379000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:37:55.504000000  8292 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443075.504000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443074.449000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443074.449000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443075.504000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:37:59.217000000  8292 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443079.217000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443078.216000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443078.216000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443079.217000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:38:02.812000000  8292 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443082.812000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443081.812000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443081.812000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443082.812000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:38:07.367000000  8292 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443087.367000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443086.272000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443086.272000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443087.367000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:38:11.080000000  8292 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443091.080000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443090.058000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443090.058000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443091.080000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
gRPC tests require a helper port server to allocate ports used 
during the test.

This server is not currently running.

To start it, run tools/run_tests/start_port_server.py
```

And

`c_windows_opt_native.cmake/build/Release/h2_ssl_cert_test.exe simple_cacheable_request`

shows output:

```
Failure
Stacktrace

D0915 02:37:50.454000000  3536 test_config.c:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0915 02:37:50.456000000  3536 dns_resolver.c:301] Using native dns resolver
I0915 02:37:50.456000000  3536 h2_ssl_cert.c:256] SSL_CERT_tests/chttp2/ssl_GRPC_SSL_DONT_REQUEST_CLIENT_CERTIFICATE_NONE_SUCCESS_
D0915 02:37:52.866000000  3536 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443072.866000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443071.783000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443071.783000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443072.866000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:37:56.079000000  3536 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443076.079000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443075.066000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443075.066000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443076.079000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:37:59.749000000  3536 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443079.749000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443078.679000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443078.679000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443079.749000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:38:03.488000000  3536 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443083.488000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443082.411000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443082.411000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443083.488000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:38:07.989000000  3536 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443087.989000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443086.905000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443086.905000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443087.989000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
D0915 02:38:11.389000000  3536 port_server_client.c:140] failed port pick from server: retrying [{"created":"@1505443091.389000000","description":"Failed HTTP requests to all targets","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":213,"referenced_errors":[{"created":"@1505443090.379000000","description":"Failed HTTP/1 client request","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\http\httpcli.c","file_line":116,"referenced_errors":[{"created":"@1505443090.379000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv4:127.0.0.1:32766","wsa_error":10061},{"created":"@1505443091.389000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","target_address":"ipv6:[::1]:32766","wsa_error":10061}]}]}]
gRPC tests require a helper port server to allocate ports used 
during the test.

This server is not currently running.

To start it, run tools/run_tests/start_port_server.py
```

jenkins main page in https://grpc-testing.appspot.com/job/gRPC_pr_win/7833/#showFailuresLink

What's strange though is that making a GET request to `http://localhost:32766/version_number` on `grpc-jenkins-windows-worker3` shows `20`, so it looks like that the worker is running the latest master's version of the port server as intended.

**Comment by AspirinSJL** [comment]
Seen 66 similar failures in https://sponge.corp.google.com/target?id=4d98b775-2b32-419f-8fe5-430065f97eb8&target=github/grpc/c_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by apolcyn** [comment]
Looking further into the port server issues here... even though test logs claim that the port server is missing (like [in these jenkins windows PR logs from 9/26, on windows worker 6](https://grpc-testing.appspot.com/job/gRPC_pr_win/8126/consoleFull), it can be seen by looking at the port server process on that windows-worker-6 that the current port server has in actually been running uninterrupted since 9/14. The current (9/27) port server process's tempfile "output log" command arg has existed in that machines "temp" directory and been getting logged to since 9/14. Also, the log shows no sign of any [https://github.com/grpc/grpc/blob/master/tools/run_tests/python_utils/port_server.py#L111](failure of the port server to respond 200 to a request).

**Comment by matt-kwong** [comment]
I see a lot of h2* errors w/ the log saying 
```
This server is not currently running.

To start it, run tools/run_tests/start_port_server.py
```
This also happens on Kokoro (which builds on clean VMs) also, so there isn't any leftover `start_port_server.py` process leftover from previous builds. The # of tests failing isn't consistent and many h2* tests pass, so I'm sure the port_server works for some of the tests. 

Perhaps the issue is associated with how the port is selected on Windows?

**Comment by apolcyn** [comment]
this should be fixed by https://github.com/grpc/grpc/pull/12777

**Comment by adelez** [comment]
Still seeing it: https://sponge.corp.google.com/target?id=3c768619-5476-4959-8810-adb37274aedc&target=github/grpc/c_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by apolcyn** [comment]
@adelez I took a look at that log but from what I can tell that error is different from the one in this issue.

The error in this  issue was port server clients in tests were exhausting there retries and would give up with the error:

```
gRPC tests require a helper port server to allocate ports used 

during the test.



This server is not currently running.



To start it, run tools/run_tests/start_port_server.py
```

In that log though, it looks like after a couple of retries, the test did successfully get a port, but it failed for some other reason:

```
I1115 16:33:32.921000000   136 http_proxy_fixture.cc:495] Proxy address: localhost:21312
E1115 16:33:32.921000000   136 filter_call_init_fails.cc:354] assertion failed: status == GRPC_STATUS_PERMISSION_DENIED
```

**Comment by adelez** [comment]
The trace may be different but assertion failed: status == GRPC_STATUS_PERMISSION_DENIED was in the original report as well. Please feel free to open a separate bug if you think they are different issues.

**Comment by apolcyn** [comment]
I believe that assertion is the same one described in https://github.com/grpc/grpc/issues/12748.

Sorry this title and original post might be confusing. I'd like to keep this issue specifically for the port server issue though.
