### ISSUE TITLE
Bazel test failure: arena test fails under TSAN and MSAN

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#14513]
https://source.cloud.google.com/results/invocations/45571f80-62f2-4e33-a601-03975b652456/targets/%2F%2Ftest%2Fcore%2Fgpr:arena_test@poller%3Depoll1/log

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ export GRPC_POLL_STRATEGY=epoll1
+ shift
+ test/core/gpr/arena_test
D0223 17:11:44.616693676      19 test_config.cc:390]         test slowdown factor: sanitizer=5, fixture=1, poller=1, total=5
I0223 17:11:44.619815802      19 arena_test.cc:49]           test '0_1': 0 <- {1,}
I0223 17:11:44.620922908      19 arena_test.cc:49]           test '1_1': 1 <- {1,}
I0223 17:11:44.620969642      19 arena_test.cc:49]           test '1_2': 1 <- {2,}
I0223 17:11:44.621075068      19 arena_test.cc:49]           test '1_3': 1 <- {3,}
I0223 17:11:44.622938466      19 arena_test.cc:49]           test '1_inc': 1 <- {1,2,3,4,5,6,7,8,9,10,11,}
I0223 17:11:44.624796252      19 arena_test.cc:49]           test '6_123': 6 <- {1,2,3,}
D0223 17:11:44.624828389      19 arena_test.cc:94]           concurrent_test
Killed
```

**Comment by jtattermusch** [comment]
@adelez  is this fixed now?

**Comment by adelez** [comment]
No, still happening: https://source.cloud.google.com/results/invocations/9b476e04-d002-4daf-b4e6-67bb9c5b96b1/targets

**Comment by jtattermusch** [comment]
@vjpai  this is blocking our progress with foundry and it has been open for >1 months now. Can you please take a look and update this thread?

**Comment by ncteisen** [comment]
I think this should be resolved. However, who is to say if my desk environ is like the remote bazel one, so please reopen if this pops up again

**Comment by adelez** [comment]
Hi Noah, it's easy to trying remote execution from your desktop. Please check the doc I shared about Foundry integration.

**Comment by adelez** [comment]
Verified that this is indeed fixed: https://source.cloud.google.com/results/invocations/934abc65-f5cc-46e1-8903-8f712ff9e719/targets

**Comment by sab24** [comment]
This issue should not have been closed. Shall I make a new one or can someone reopen this?

This test fails on Archlinux:
D0620 20:15:10.747514446   11504 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
[RUN]     Testing arena_test
D0620 20:15:10.753543986   11507 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0620 20:15:10.753787101   11507 arena_test.cc:50]           test '0_1': 0 <- {1,}
I0620 20:15:10.753936317   11507 arena_test.cc:50]           test '1_1': 1 <- {1,}
I0620 20:15:10.754034369   11507 arena_test.cc:50]           test '1_2': 1 <- {2,}
I0620 20:15:10.754166620   11507 arena_test.cc:50]           test '1_3': 1 <- {3,}
I0620 20:15:10.754276471   11507 arena_test.cc:50]           test '1_inc': 1 <- {1,2,3,4,5,6,7,8,9,10,11,}
I0620 20:15:10.754390871   11507 arena_test.cc:50]           test '6_123': 6 <- {1,2,3,}
D0620 20:15:10.754499131   11507 arena_test.cc:95]           concurrent_test
/bin/sh: line 1: 11507 Killed                  /home/user/Downloads/grpc/bins/opt/arena_test
test arena_test failed
make: *** [Makefile:1883: test_c] Error 1

**Comment by ncteisen** [comment]
Are you running HEAD? This passes on all architectures I have at my disposal (macos, and two different linux configurations)

**Comment by sab24** [comment]
@ncteisen Thanks for your suggestion. These are the commands that I ran. Did I do something wrong?

git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
git checkout HEAD
    Your branch is up to date with 'origin/v1.12.x'.
make CXXFLAGS="-Wno-error=class-memaccess -Wno-error=ignored-qualifiers -Wno-error=stringop-truncation" CFLAGS="-Wno-error=class-memaccess -Wno-error=ignored-qualifiers -Wno-error=stringop-truncation"
make CXXFLAGS="-Wno-error=class-memaccess -Wno-error=ignored-qualifiers -Wno-error=stringop-truncation -Wno-error=implicit-function-declaration -Wno-error=implicit-fallthrough -Wno-error=sizeof-pointer-memaccess -Wno-error=stringop-overflow -Wno-error=sizeof-pointer-div" CFLAGS="-Wno-error=class-memaccess -Wno-error=ignored-qualifiers -Wno-error=stringop-truncation -Wno-error=implicit-function-declaration -Wno-error=implicit-fallthrough -Wno-error=sizeof-pointer-memaccess -Wno-error=stringop-overflow -Wno-error=sizeof-pointer-div" test


I0620 23:04:10.143219674   13789 arena_test.cc:50]           test '6_123': 6 <- {1,2,3,}
D0620 23:04:10.143503812   13789 arena_test.cc:95]           concurrent_test
/bin/sh: line 1: 13789 Killed                  /home/user/Downloads/grpc/bins/opt/arena_test
test arena_test failed
