### ISSUE TITLE
on ppc64le Alpine Linux "make test fails" with unsupported relocation type 43

### ISSUE THREAD

**Issue by mksully22** [grpc/grpc#17877]
### What version of gRPC and what language are you using?
1.18.0
 
### What operating system (Linux, Windows, …) and version?
 Linux Alpine (edge) on ppc64le
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc-8.2.0
musl-1.1.20
php7-7.2.14
 
### What did you do?
After making modules/grpc.so without error using:
  ./configure --prefix=/usr --with-php-config=php-config7
  make

Running "make test" fails with error:
=====================================================================
PHP         : /usr/bin/php7
Warning: PHP Startup: Unable to load dynamic library 'grpc.so' (tried: /home/mksully/aports/testing/php7-pecl-grpc/src/grpc-1.18.0/modules/grpc.so (Error relocating /home/mksully/aports/testing/php7-pecl-grpc/src/grpc-1.18.0/modules/grpc.so: unsupported relocation type 43), /home/mksully/aports/testing/php7-pecl-grpc/src/grpc-1.18.0/modules/grpc.so.so (Error loading shared library /home/mksully/aports/testing/php7-pecl-grpc/src/grpc-1.18.0/modules/grpc.so.so: No such file or directory)) in Unknown on line 0

PHP_SAPI    : cli
PHP_VERSION : 7.2.14
ZEND_VERSION: 3.2.0
PHP_OS      : Linux - Linux 6b8f13c9c5e7 4.15.7-041507-generic #201802280530 SMP Wed Feb 28 11:07:12 UTC 2018 ppc64le
INI actual  : /home/mksully/tmp-php.ini
More .INIs  :
CWD         : /home/mksully/aports/testing/php7-pecl-grpc/src/grpc-1.18.0
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2019-01-30 15:30:14
=====================================================================
No tests were run.

### What did you expect to see?
Successfully completion of tests 
 
### Anything else we should know about your project / environment?
If I understand this correctly type 43 is R_PPC64_UADDR64
/usr/include # grep 43 /usr/include/elf.h | grep PPC
#define R_PPC64_UADDR64         43

Objdump shows a number of symbols of this type:
~/aports/testing/php7-pecl-grpc $ objdump -R /home/mksully/aports/testing/php7-p
ecl-grpc/src/grpc-1.18.0/modules/grpc.so | grep UADDR
000000000039decf R_PPC64_UADDR64   .tbss+0x0000000000011dd3
000000000039df26 R_PPC64_UADDR64   .tbss+0x0000000000011f86
000000000039df43 R_PPC64_UADDR64   .tbss+0x0000000000011ebb
000000000039dfb7 R_PPC64_UADDR64   .tbss+0x00000000000032e4
000000000039e97f R_PPC64_UADDR64   .tbss+0x0000000000012208
000000000039e99c R_PPC64_UADDR64   .tbss+0x0000000000003c38
000000000039e9f3 R_PPC64_UADDR64   .tbss+0x000000000001225f
00000000003acaa6 R_PPC64_UADDR64   .tbss+0x000000000000333b
00000000003acb8e R_PPC64_UADDR64   .tbss+0x000000000000333b
00000000003acbe5 R_PPC64_UADDR64   .tbss+0x000000000000328d
00000000003acc59 R_PPC64_UADDR64   .tbss+0x000000000000333b
00000000003acd7b R_PPC64_UADDR64   .tbss+0x000000000000333b
000000000039deec R_PPC64_UADDR64   .init+0x00000000002a146d
000000000039e00e R_PPC64_UADDR64   .init+0x00000000002a14fe
000000000039e065 R_PPC64_UADDR64   .init+0x00000000002a15c9
000000000039e945 R_PPC64_UADDR64   .init+0x00000000002a9043
000000000039e9d6 R_PPC64_UADDR64   .init+0x00000000002a912b
00000000003acb37 R_PPC64_UADDR64   .init+0x00000000002a14fe
00000000003acb54 R_PPC64_UADDR64   .init+0x00000000002a14fe
00000000003acc1f R_PPC64_UADDR64   .init+0x00000000002a1555
00000000003acc3c R_PPC64_UADDR64   .init+0x00000000002a1555
00000000003accea R_PPC64_UADDR64   .init+0x00000000002a14fe
00000000003acd07 R_PPC64_UADDR64   .init+0x00000000002a14fe
00000000003acd24 R_PPC64_UADDR64   .init+0x00000000002a1555
00000000003acd41 R_PPC64_UADDR64   .init+0x00000000002a1555
00000000003acf32 R_PPC64_UADDR64   .init+0x00000000002a8f95
00000000003acf6c R_PPC64_UADDR64   .init+0x00000000002a8fec
00000000003acffd R_PPC64_UADDR64   .init+0x00000000002a90d4

The ones in the .tbss section all seem to be defined using GRP_TLS_DECL:
~/aports/testing/php7-pecl-grpc/src/grpc-1.18.0 $ objdump -t /home/mksully/aports/testing/php7-pecl-grpc/src/grpc-1.18.0/modules/grpc.so  | grep tbss
000000000039acf8 l    d  .tbss  0000000000000000 .tbss
0000000000000000 l       .tbss  0000000000000008 _ZZ15gpr_default_logP17gpr_log_func_argsE3tid
0000000000000028 l       .tbss  0000000000000008 _ZL23g_current_thread_worker
0000000000000030 l       .tbss  0000000000000008 _ZL23g_current_thread_poller
0000000000000050 l       .tbss  0000000000000008 _ZL11g_cached_cq
0000000000000058 l       .tbss  0000000000000008 _ZL14g_cached_event
0000000000000018 l       .tbss  0000000000000008 _ZL23g_current_thread_worker
0000000000000020 l       .tbss  0000000000000008 _ZL24g_current_thread_pollset
0000000000000040 l       .tbss  0000000000000008 _ZL19g_this_thread_state
0000000000000048 l       .tbss  0000000000000008 _ZL21g_last_seen_min_timer
0000000000000008 l       .tbss  0000000000000008 _ZL23g_current_thread_worker
0000000000000010 l       .tbss  0000000000000008 _ZL24g_current_thread_pollset
0000000000000038 l       .tbss  0000000000000008 _ZN9grpc_core7ExecCtx9exec_ctx_E

~/aports/testing/php7-pecl-grpc/src/grpc-1.18.0 $ find . -name "*.cc" -exec grep GPR_TLS_DECL {} \; -print
GPR_TLS_DECL(g_current_thread_poller);
GPR_TLS_DECL(g_current_thread_worker);
./src/core/lib/iomgr/ev_poll_posix.cc
GPR_TLS_DECL(g_last_seen_min_timer);
./src/core/lib/iomgr/timer_generic.cc
GPR_TLS_DECL(g_current_thread_pollset);
GPR_TLS_DECL(g_current_thread_worker);
./src/core/lib/iomgr/ev_epoll1_linux.cc
GPR_TLS_DECL(g_this_thread_state);
./src/core/lib/iomgr/executor.cc
GPR_TLS_DECL(g_current_thread_pollset);
GPR_TLS_DECL(g_current_thread_worker);
./src/core/lib/iomgr/ev_epollex_linux.cc
GPR_TLS_DECL(g_cached_event);
GPR_TLS_DECL(g_cached_cq);
./src/core/lib/surface/completion_queue.cc

Any insights to what might be going on?

**Comment by andypost** [comment]
It fails on s390x as well, probably byte order effect cos both Little-endian

**Comment by richfelker** [comment]
Can you determine what CFLAGS and LDFLAGS were used to build the affected libraries? Is it possible that they depend on some libraries which were only built in static form, and not as PIC, so that non-PIC code got linked into the shared library?

**Comment by richfelker** [comment]
OK, I've been informed that this is a known issue: https://www.openwall.com/lists/musl/2019/06/30/4

It will be fixed upstream in musl.

FYI, this happening is a result of having misaligned pointers in the data segment of the program/library affected, which is a really bad idea. It comes from someone using packed/align(1).

**Comment by richfelker** [comment]
I believe this is fixed. Can someone affected confirm?

**Comment by andypost** [comment]
Used to upgrade this week, both 390x and ppc64 still won't compile... The issue is not solved

**Comment by richfelker** [comment]
Can you clarify if the issue is still observed with musl v1.2.0 or git master? Alpine does not have latest musl yet so may still be affected (unless they added the patch) even if it's fixed upstream. If they don't yet have a patch please ping someone on the Alpine side about this or open an issue on their tracker.

**Comment by omnivagant** [comment]
I tried enabling a few archs to se if things've changed, if anyone's interested they can have a look at the build logs from the CI pipeline at https://gitlab.alpinelinux.org/omni/aports/-/jobs/360286

If anyone has input, I could re-open the MR and try patches and ideas.
