### ISSUE TITLE
Continues performance benchmarks are not available

### ISSUE THREAD

**Issue by IzabellaRaulin** [grpc/grpc#18417]
Most of the visualizations on [continues performance benchmarks dashboards](https://grpc.io/docs/guides/benchmarking.html) **have no data**.

There is an existing issue regarding microbenchmarks dashboard which was reported on January 24, 2019 in [grpc.github.io#827](https://github.com/grpc/grpc.github.io/issues/827) , but now all dashboards have been affected and I would like to make the issue more visible in community. Feel free to move this issue to another repo or merge it with [grpc.github.io#827](https://github.com/grpc/grpc.github.io/issues/827). 

**Could you tell me where I could find benchmark results for the latest release? Do you plan fix these dasboards?** Thanks in advance.

Below there are screenshots of dashboards and how they look at the moment:

**Screenshots:**
a) [Multi-language performance dashboard @latest_release (lastest available stable release)](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5636470266134528)

![image](https://user-images.githubusercontent.com/11335874/54552991-9affb880-49b1-11e9-9198-9c003315ffd3.png)

b) [Multi-language performance dashboard @master (latest dev version)](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584)
![image](https://user-images.githubusercontent.com/11335874/54553179-ec0fac80-49b1-11e9-9f7f-2cb14c8f75d0.png)

c) [C++ detailed performance dashboard @master (latest dev version)](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5685265389584384)
![image](https://user-images.githubusercontent.com/11335874/54553281-224d2c00-49b2-11e9-86fd-1e09712358aa.png)

**Comment by adelez** [comment]
@jtattermusch @billfeng327 . Looks like the latest result was on 2/28. Thank you for pointing out. We're investigating.

**Comment by jtattermusch** [comment]
I think this is because of https://github.com/grpc/grpc/issues/18274

**Comment by stanley-cheung** [comment]
It appears that some data is being shown now. There are 2 green builds since earlier today.

**Comment by adelez** [comment]
Thank you for the quick fix, Stanley!

**Comment by jtattermusch** [comment]
#18274 was fixed and it seems the dashboard are getting populated with new data now.

**Comment by IzabellaRaulin** [comment]
@jtattermusch, thanks for taking care. I confirm that dashboards b and c work look as expected, but there is still missing data for visualizations in dashboard a) [Multi-language performance dashboard @latest_release (lastest available stable release)](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5636470266134528 ). Could you tell me when I might expect availability of data regarding gRPC language comparision? Is it matter of time or there is still sth what needs to be fixed?

![image](https://user-images.githubusercontent.com/11335874/54698631-e6d86c00-4b2f-11e9-8b43-8e01872b096d.png)

**Comment by jtattermusch** [comment]
@IzabellaRaulin  the problem with "latest release" dashboard is likely that it's a version that's fixed to a specific commit and as such it doesn't include the fix from #18274 (we'd need to backport to fix).

CC @stanley-cheung 

Here's the log:
https://source.cloud.google.com/results/invocations/1e8e0109-992f-40cc-9c83-89a19a0381cb/targets;collapsed=/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_full_performance_release/log

```
Generating autoload files
+ cd vendor/google/protobuf/php/ext/google/protobuf
tools/run_tests/performance/build_performance_php7.sh: line 26: cd: vendor/google/protobuf/php/ext/google/protobuf: No such file or directory

2019-03-20 09:12:29,378 FAILED: local_build [ret=1, pid=30187, time=186.1sec]
```

**Comment by IzabellaRaulin** [comment]
OK, thanks @jtattermusch for the explanation
