### ISSUE TITLE
Random native grpc_csharp_ext.x64.dll crash while running C# VSTest unit tests

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#18753]
### What version of gRPC and what language are you using?
`1.19.1` in C#, taken from the official NuGet repository for Windows
 
### What operating system (Linux, Windows,...) and version?
 Windows 10 Pro, version `10.0.17134.648`
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Downloaded compiled binaries and assemblies from NuGet repository, version `1.19.1`
 
### What did you do?
The issue happens randomly when the code executes under Microsoft VSTest unit tests environment. Some tests fail from time to time with error `"The agent process was stopped while the test was running."` (similar to [this](https://stackoverflow.com/questions/2810012/vs-2010-test-runner-error-the-agent-process-was-stopped-while-the-test-was-runn)).
Digging into this problem, I found the error described below in the `Application` event log (Event 1000, `Application Error`). It appears the crash happened in the native gRPC code of the C# assembly (exception `0xc0000409` in offset `0x21b84d`). I don't know what was the base address of the loaded module, and I don't have the `pdb` symbols to investigate.
 
### What did you expect to see?
 ... no crash ...
 
### What did you see instead?

> Faulting application name: QTAgent_40.exe, version: 14.0.23107.0, time stamp: 0x559b7ab8
Faulting module name: grpc_csharp_ext.x64.dll, version: 0.0.0.0, time stamp: 0x5c757b11
Exception code: 0xc0000409
Fault offset: 0x000000000021b84d
Faulting process id: 0x2f2c
Faulting application start time: 0x01d4f29695d8f46a
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\QTAgent_40.exe
Faulting module path: c:\jenkins\workspace\...\grpc_csharp_ext.x64.dll
Report Id: 53964039-befa-4b6b-be5d-218788a76d3c
Faulting package full name: 

### Anything else we should know about your project / environment?
We use `VSTest` installed as part of `Visual Studio 14` ecosystem. It loads the tests `dll` which contains dozens of tests. For each test, we start a new instances of gRPC servers (on different ports, over and over again), and connect gRPC clients which run on different threads of that process. In the end of each test, everything is (allegedly) cleaned up.

**Comment by jtattermusch** [comment]
It would be useful to get a native and managed stack trace or a crash dump. Without it, we can't really do anything about the issue. Btw you can find the native symbols (.pdb) in https://www.nuget.org/packages/Grpc.Core.NativeDebug/ package (use the same version of the nuget as the grpc version you're using).

**Comment by amitwaisel** [comment]
I experience consistent crash when running a VSTest.
Platform: dotnet core 3.0 on win-x64 (either from Visual Studio or using the `dotnet.exe vstest` command line tool)
gRPC: Version `2.24.0`
Crash exception: `Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
`
I attached windbg to `dotnet.exe vstest` process (with `.childdbg 1` option as each test runs in its own process). At first it failed loading the PDB downloaded from `Grpc.Core.NativeDebug` nuget package, as it searched for `grpc_csharp_ext.pdb` while the pdbs are either `grpc_csharp_ext.x64.pdb` or `grpc_csharp_ext.x86.pdb`). In any case, I manually fixed it and got the symbols loaded. The call stack is:

```log
grpc_csharp_ext_x64!abort+0x35 [minkernel\crts\ucrt\src\appcrt\startup\abort.cpp @ 77] 
grpc_csharp_ext_x64!grpc_slice_buffer_take_first+0x84 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\slice\slice_buffer.cc @ 380] 
grpc_csharp_ext_x64!grpc_core::SliceBufferByteStream::Pull+0x33 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\transport\byte_stream.cc @ 66] 
grpc_csharp_ext_x64!pull_slice_from_send_message+0x33 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\http\message_compress\message_compress_filter.cc @ 309] 
grpc_csharp_ext_x64!continue_reading_send_message+0x48 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\http\message_compress\message_compress_filter.cc @ 325] 
grpc_csharp_ext_x64!start_transport_stream_op_batch+0x128 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\message_size\message_size_filter.cc @ 277] 
grpc_csharp_ext_x64!exec_ctx_run+0x13 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\exec_ctx.cc @ 46] 
grpc_csharp_ext_x64!grpc_core::ExecCtx::Flush+0x4c [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\exec_ctx.cc @ 159] 
grpc_csharp_ext_x64!grpc_core::ExecCtx::{dtor}+0x1f [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\exec_ctx.h @ 124] 
grpc_csharp_ext_x64!grpc_call_start_batch+0x181 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc @ 1975] 
grpc_csharp_ext_x64!grpcsharp_call_send_status_from_server+0x11b [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\csharp\ext\grpc_csharp_ext.c @ 856] 
```

The full stack with arguments and addresses are in [here](https://pastebin.com/hPZ3hNcr)

In my testing case, both client and server are loaded in the same process (as mentioned, C# over dotnet core 3.0 on latest Windows 10 x64).
The client initializes a stream-based RPC call (the client-side has the read end of the stream), and during that call it initializes another non-streaming RPC call. That second call is triggered on the server side, and once the handler callback returns a value (an empty protobuf message in my case), it crashes with the aforementioned exception and stack trace.

I hope it will help pinpoint the issue.
The exception is consistently thrown and makes it impossible to work with last gRPC versions.

**Comment by amitwaisel** [comment]
I can send the memory dump over a secure channel if necessary (contains sensitive data).

A bit more analysis to help speed things up:
1. Function `grpc_slice grpc_slice_buffer_take_first(grpc_slice_buffer* sb)` from `src\core\lib\slice\slice_buffer.cc` wasn't changed for the past 2 years - probably not the function to blame
2. **Function `grpc_error* SliceBufferByteStream::Pull(grpc_slice* slice)` from `src\core\lib\transport\byte_stream.cc` was last changed by https://github.com/grpc/grpc/commit/54a3b642466faf6f71578c44615d31af861b92ef. This is a good lead to investigate.**
3. Function `static grpc_error* pull_slice_from_send_message(call_data* calld)` in `src\core\ext\filters\http\message_compress\message_compress_filter.cc`) wasn't changed for the past 2 years - probably not the function to blame
4. Function `static void continue_reading_send_message(grpc_call_element* elem)` in `src\core\ext\filters\http\message_compress\message_compress_filter.cc`) wasn't changed for the past 2 years - probably not the function to blame
5. Function `static void start_transport_stream_op_batch(grpc_call_element* elem, grpc_transport_stream_op_batch* op)` in `src\core\ext\filters\message_size\message_size_filter.cc` wasn't changed for the past year - probably not the function to blame
6. Function `static void exec_ctx_run(grpc_closure* closure, grpc_error* error)` in `src\core\lib\iomgr\exec_ctx.cc` wasn't changed for the past 2 years - probably not the function to blame
7. Function `bool ExecCtx::Flush()` in `src\core\lib\iomgr\exec_ctx.cc` wasn't changed for the past 2 years - probably not the function to blame
8. Function `virtual ~ExecCtx()` in `src\core\lib\iomgr\exec_ctx.h` wasn't changed for the past year - probably not the function to blame
9. Function `grpc_call_error grpc_call_start_batch(grpc_call* call, const grpc_op* ops, size_t nops, void* tag, void* reserved)` in `src\core\lib\surface\call.cc` wasn't changed for the past 9 months - probably not the function to blame
10. **Function `GPR_EXPORT grpc_call_error GPR_CALLTYPE grpcsharp_call_send_status_from_server(...)` in `src\csharp\ext\grpc_csharp_ext.c` was lately changed by the following commit: https://github.com/grpc/grpc/commit/31eff3e679f12f3db28c80527f7f376c1beb8efd. This may be another good lead to investigate, as it changed the use of `byte[]` with `SliceBufferSafeHandle` in C# and introduced `grpcsharp_create_byte_buffer_from_stolen_slices` in `src/csharp/ext/grpc_csharp_ext.c`.**

Please let me know if you need any more information.

**Comment by amitwaisel** [comment]
This issue continuously happens when an empty response message is returned from the server - either the `message` is really empty (aka `message Empty { }`), or all fields contain default values.
Changing values to non-default bypasses this `abort()` crash.

**Comment by amitwaisel** [comment]
@jtattermusch @srini100 
Another C#-native crash has been discovered - `Access violation - code c0000005 (first chance)`:
```log
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Grpc.Core.Internal.GrpcThreadPool.RunHandlerLoop(Grpc.Core.Internal.CompletionQueueSafeHandle, Grpc.Core.Profiling.IProfiler)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

Happens on a C# server and client, running in the same process, under dotnet core 3.0 on Windows 10 x64.

The native call stack is:
```log
grpc_csharp_ext_x64!grpc_core::SockToPolledFdMap::CloseSocket+0xe1 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_ev_driver_windows.cc @ 822] 
grpc_csharp_ext_x64!ares__close_sockets+0xe6 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\third_party\cares\cares\ares__close_sockets.c @ 59] 
grpc_csharp_ext_x64!ares__destroy_servers_state+0x3c [t:\src\github\grpc\workspace_csharp_ext_windows_x64\third_party\cares\cares\ares_destroy.c @ 106] 
grpc_csharp_ext_x64!ares_destroy+0x78 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\third_party\cares\cares\ares_destroy.c @ 76] 
grpc_csharp_ext_x64!grpc_ares_ev_driver_unref+0x95 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_ev_driver.cc @ 112] 
grpc_csharp_ext_x64!grpc_combiner_continue_exec_ctx+0x11e [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\combiner.cc @ 269] 
grpc_csharp_ext_x64!grpc_core::ExecCtx::Flush+0x5b [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\exec_ctx.cc @ 161] 
grpc_csharp_ext_x64!pollset_work+0xd0 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\pollset_windows.cc @ 132] 
grpc_csharp_ext_x64!cq_next+0x1fc [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\completion_queue.cc @ 1036] 
grpc_csharp_ext_x64!grpc_completion_queue_next+0x23 [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\completion_queue.cc @ 1112] 
grpc_csharp_ext_x64!grpcsharp_completion_queue_next+0x3c [t:\src\github\grpc\workspace_csharp_ext_windows_x64\src\csharp\ext\grpc_csharp_ext.c @ 403]
```

The managed call stack is:
```log
ILStubClass.IL_STUB_PInvoke(Grpc.Core.Internal.CompletionQueueSafeHandle)
Grpc.Core.Internal.CompletionQueueSafeHandle.Next()
Grpc.Core.Internal.GrpcThreadPool.RunHandlerLoop(Grpc.Core.Internal.CompletionQueueSafeHandle, Grpc.Core.Profiling.IProfiler)
Grpc.Core.Internal.GrpcThreadPool+c__DisplayClass22_0.b__0()
System.Threading.ThreadHelper.ThreadStart_Context(System.Object) [/_/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs @ 50]
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs @ 172]
System.Threading.ThreadHelper.ThreadStart() [/_/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs @ 100]
```

As before - I can send the memory dump over a secure channel if necessary (contains sensitive data).
Please let me know if I can be of any further help.

**Comment by aaubry** [comment]
We are also experiencing this problem in some of our services. Thanks to @amitwaisel 's analysis, we figured out that the crashes that we observed happened when the service is returning an empty (all fields set to the default value) response. But we performed additional tests in that and other services and were unable to observe crashes even when the responses were empty.

We are unable to revert to version 1.19 due to the IAsyncEnumerable dependency, but we were able to work around the problem by adding a dummy uint field to the response and set it to 1, which is a clue that the issue may be triggered when the response is empty.

I tried to create a simple console application that hosted a server with the the same contract and perform requests to it, but I could not provoke any crash. I could try to remove as much as possible from our service to try to isolate the bug, but that would require a lot of effort as this service contains a substantial amount of code.

Which additional information could be useful to diagnose this problem ?

**Comment by srini100** [comment]
/cc @apolcyn, @hcaseyal, have you seen a similar crash with CAres in Core?

@amitwaisel, @aaubry, would you be able to bisect to a particular commit or version where this issue was introduced.

**Comment by hcaseyal** [comment]
@veblush since they are the current build cop

**Comment by aaubry** [comment]
@srini100 I don't really know to do that. If you provide guidance on how to do it, I can try do it.
In a related note, I have encountered the same problem in a client application, that is sending an empty (`Google.Protobuf.WellKnownTypes.Empty`) request. It appears that it is the same error.

**Comment by jtattermusch** [comment]
Is anyone able to provide a the code that reliably reproduces the problem described above?

Amit, you're saying that version 1.19 works and the problem was introduced sometimes between 1.20 and 2.24 - can you test each of the version is the first one that doesn't work. It would help us narrow down the problem. Can you also try to test 2.25, just to be sure?

**Comment by jtattermusch** [comment]
Btw, there's a good chance that in 2.25.0 nugets the issue is fixed.
On another issue, I see the same stack trace https://github.com/grpc/grpc/issues/18461#issuecomment-525120215 and that issue seems to have been fixed by https://github.com/grpc/grpc/pull/20274 (which is available in the 2.25.0 nuget).

Amit, can you test with 2.25.0 and confirm that the problem was fixed?

**Comment by jtattermusch** [comment]
> I can send the memory dump over a secure channel if necessary (contains sensitive data).
> 
> A bit more analysis to help speed things up:
> 
> 1. Function `grpc_slice grpc_slice_buffer_take_first(grpc_slice_buffer* sb)` from `src\core\lib\slice\slice_buffer.cc` wasn't changed for the past 2 years - probably not the function to blame
> 2. **Function `grpc_error* SliceBufferByteStream::Pull(grpc_slice* slice)` from `src\core\lib\transport\byte_stream.cc` was last changed by [54a3b64](https://github.com/grpc/grpc/commit/54a3b642466faf6f71578c44615d31af861b92ef). This is a good lead to investigate.**
> 3. Function `static grpc_error* pull_slice_from_send_message(call_data* calld)` in `src\core\ext\filters\http\message_compress\message_compress_filter.cc`) wasn't changed for the past 2 years - probably not the function to blame
> 4. Function `static void continue_reading_send_message(grpc_call_element* elem)` in `src\core\ext\filters\http\message_compress\message_compress_filter.cc`) wasn't changed for the past 2 years - probably not the function to blame
> 5. Function `static void start_transport_stream_op_batch(grpc_call_element* elem, grpc_transport_stream_op_batch* op)` in `src\core\ext\filters\message_size\message_size_filter.cc` wasn't changed for the past year - probably not the function to blame
> 6. Function `static void exec_ctx_run(grpc_closure* closure, grpc_error* error)` in `src\core\lib\iomgr\exec_ctx.cc` wasn't changed for the past 2 years - probably not the function to blame
> 7. Function `bool ExecCtx::Flush()` in `src\core\lib\iomgr\exec_ctx.cc` wasn't changed for the past 2 years - probably not the function to blame
> 8. Function `virtual ~ExecCtx()` in `src\core\lib\iomgr\exec_ctx.h` wasn't changed for the past year - probably not the function to blame
> 9. Function `grpc_call_error grpc_call_start_batch(grpc_call* call, const grpc_op* ops, size_t nops, void* tag, void* reserved)` in `src\core\lib\surface\call.cc` wasn't changed for the past 9 months - probably not the function to blame
> 10. **Function `GPR_EXPORT grpc_call_error GPR_CALLTYPE grpcsharp_call_send_status_from_server(...)` in `src\csharp\ext\grpc_csharp_ext.c` was lately changed by the following commit: [31eff3e](https://github.com/grpc/grpc/commit/31eff3e679f12f3db28c80527f7f376c1beb8efd). This may be another good lead to investigate, as it changed the use of `byte[]` with `SliceBufferSafeHandle` in C# and introduced `grpcsharp_create_byte_buffer_from_stolen_slices` in `src/csharp/ext/grpc_csharp_ext.c`.**
> 
> Please let me know if you need any more information.

FYI The `grpcsharp_create_byte_buffer_from_stolen_slices` is there starting from 2.24.0 release (see https://github.com/grpc/grpc/pull/19792), but it there seems to be two stack traces on this issue, so I'm not sure this is part of the problematic stacktrace.

**Comment by aaubry** [comment]
I am using version 2.25.0 and still encounter the crash. I've tried to create a repro but it did not crash. I'll try again but it seems to depend on something else. We have plenty of services that send empty requests without problems, but for a specific one we had to add an dummy field to the request to work around the crash.

**Comment by jtattermusch** [comment]
> I am using version 2.25.0 and still encounter the crash. I've tried to create a repro but it did not crash. I'll try again but it seems to depend on something else. We have plenty of services that send empty requests without problems, but for a specific one we had to add an dummy field to the request to work around the crash.

Which crash are you talking about? Two different stacktraces are mentioned in this issue (the one with `ares__close_sockets` and the other one with `grpc_slice_buffer_take_first`)

**Comment by aaubry** [comment]
I'm referring to the `grpc_slice grpc_slice_buffer_take_first` one. I managed to reproduce the problem, which in my case occurs when gzip compression is enabled. I don't know if this is the same problem as the one reported by @amitwaisel , or if I should open a separate issue for it.

Here is the repro in C#: [GrpcCrash.zip](https://github.com/grpc/grpc/files/3837272/GrpcCrash.zip)
The code starts a GRPC server and then connects to itself. When gzip compression is enabled and an empty request or response are sent, the part sending it crashes.

I have dumps of both the client-side and server-side crashes if needed.

**Comment by hcaseyal** [comment]
Regarding this issue being a potential bug in Core:
I tried to reproduce the crash in C++ using gzip compression and having the server send an empty response and was unable to reproduce the crash. https://github.com/grpc/grpc/pull/21118

This doesn't preclude there being a bug in C-core, but it seems that at least the reproduction is specific to C#.

**Comment by aaubry** [comment]
Maybe it is C# specific, however the crash happens while executing native code inside grpc_csharp_ext.x64.dll

**Comment by jtattermusch** [comment]
@aaubry  thanks for the repro, I think I know what's going on. Fix is coming.

**Comment by jtattermusch** [comment]
Fix is here: https://github.com/grpc/grpc/pull/21266. We can either fix the bug in C# native layer or in C-core itself. Let's continue the discussion on the PR.

**Comment by aaubry** [comment]
Thanks for looking into this @jtattermusch !
