### ISSUE TITLE
 @bazel_version//:bazel_version.bzl: The repository '@bazel_version' could not be resolved

### ISSUE THREAD

**Issue by deryck1031** [grpc/grpc#20511]
### What version of gRPC and what language are you using?

master.zip from github

### What operating system (Linux, Windows,...) and version?

Rhel6

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 7.4

### What did you do?
Adding grpc to my project using bazel.  It is added in WORKSPACE using http_archive() function

bazel build -s  //gmts:gmts_exec
     upb/bazel/upb_proto_library.bzl: Unable to find package for @bazel_version//:bazel_version.bzl: The repository '@bazel_version' could not be resolved

**Comment by andreich** [comment]
Seeing the same.

`WORKSPACE` snippet:

```
git_repository(
    name = "com_github_grpc_grpc",
    remote = "https://github.com/grpc/grpc.git",
    commit = "85a500c13ab93f161c5fc77941fbd3d10728b4a9",  # Oct 4, 2019
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

```

Reproducing with:
```
$ bazel query ...
INFO: Call stack for the definition of repository 'build_bazel_rules_apple' which is a http_archive (rule definition at /home/andrei/.cache/bazel/_bazel_andrei/4eef79b3aab51bafb13292cadca53ebd/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/andrei/.cache/bazel/_bazel_andrei/4eef79b3aab51bafb13292cadca53ebd/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:225:9
 - .../client/WORKSPACE:61:1
ERROR: error loading package '': in /home/andrei/.cache/bazel/_bazel_andrei/4eef79b3aab51bafb13292cadca53ebd/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /home/andrei/.cache/bazel/_bazel_andrei/4eef79b3aab51bafb13292cadca53ebd/external/upb/bazel/upb_proto_library.bzl: Unable to find package for @bazel_version//:bazel_version.bzl: The repository '@bazel_version' could not be resolved.
```

**Comment by Kernald** [comment]
I didn't target the specific commit yet, but it happened at some point between 1.22.1 and 1.32.0-pre1.

**Comment by theopencompany** [comment]
+1 the same at my side

git_repository(
  name = "grpc",
  remote = "https://github.com/grpc/grpc",
  tag = "v1.24.2",
  init_submodules = True
)
load("@grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

**Comment by gnossen** [comment]
@djwenren 's contribution fixes this.

**Comment by jackleehunter** [comment]
The same to this!
How to fix this problem, Could u tell me?

**Comment by jackleehunter** [comment]
http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        # "https://github.com/grpc/grpc/archive/v1.25.0.tar.gz",
		"http://10.128.2.197:8800/thirdparty/v1.25.0.tar.gz",
    ],
	sha256 = "5512f39ffb9e88a037acc16149c5deba2abebc14d554ba8765f1aceac9221eeb",
    strip_prefix = "grpc-1.25.0",
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

ERROR: /home/yckj2767/myfile/bazel_example/jack_example/project_a/main/BUILD:36:1: error loading package '@com_github_grpc_grpc//': in /home/yckj2767/.cache/bazel/_bazel_AD\yckj2767/95b094ada2b60fe0d11e4dcc449086c0/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /home/yckj2767/.cache/bazel/_bazel_AD\yckj2767/95b094ada2b60fe0d11e4dcc449086c0/external/upb/bazel/upb_proto_library.bzl: Unable to find package for @bazel_version//:bazel_version.bzl: The repository '@bazel_version' could not be resolved. and referenced by '//main:mycar'
ERROR: Analysis of target '//main:mycar' failed; build aborted: error loading package '@com_github_grpc_grpc//': in /home/yckj2767/.cache/bazel/_bazel_AD\yckj2767/95b094ada2b60fe0d11e4dcc449086c0/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /home/yckj2767/.cache/bazel/_bazel_AD\yckj2767/95b094ada2b60fe0d11e4dcc449086c0/external/upb/bazel/upb_proto_library.bzl: Unable to find package for @bazel_version//:bazel_version.bzl: The repository '@bazel_version' could not be resolved.

**Comment by gnossen** [comment]
@jackleehunter 
Make sure you're using a recent enough version of the repo and invoke [`grpc_extra_deps`](https://github.com/grpc/grpc/blob/a30f2f95017bf0f53acf2a89056252eb3a2cbbab/bazel/test/python_test_repo/WORKSPACE#L10).

**Comment by jackleehunter** [comment]
@gnossen 
grpc_extra_deps,  In grpc package, I can't find grpc_extra_deps.bzl?

**Comment by jackleehunter** [comment]
@gnossen 
thx very mush, i fixed it.   My grpc version is too old!

**Comment by gertvdijk** [comment]
I'm using gRPC from source on the v1.26.x branch which should include this fix, and I've adopted the WORKSPACE to call the grpc_extra_deps as well.

I notice it still fails for me for my project where we rely on the Python protoc plugin, e.g.:

```
_py_grpc_library_gen = rule(
    attrs = {
        "deps": attr.label_list(
            mandatory = True,
            providers = [ProtoInfo],
        ),
        "includes": attr.label_list(),
        "_protoc": attr.label(
            default = Label("@com_google_protobuf//:protoc"),
            executable = True,
            allow_single_file = True,
            cfg = "host",
        ),
        "_plugin": attr.label(
            default = Label("@com_github_grpc_grpc//src/compiler:grpc_python_plugin"),
            executable = True,
            allow_single_file = True,
            cfg = "host",
        ),
    },
    output_to_genfiles = True,
    implementation = _py_grpc_library_gen_impl,
)
```

And then this fails as follows:

```
ERROR: /myproj/BUILD.bazel:196:1: every rule of type _py_grpc_library_gen implicitly depends upon the target '@com_github_grpc_grpc//src/compiler:grpc_python_plugin', but this target could not be found because of: error loading package '@com_github_grpc_grpc//src/compiler': in /home/gert/.cache/bazel/_bazel_gert/9a5697af4b4898056e1adadcd9c31af8/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /home/gert/.cache/bazel/_bazel_gert/9a5697af4b4898056e1adadcd9c31af8/external/upb/bazel/upb_proto_library.bzl: Unable to load file '@bazel_version//:bazel_version.bzl': file doesn't exist
ERROR: Analysis of target '//myproj:my_py_grpc_library' failed; build aborted: error loading package '@com_github_grpc_grpc//src/compiler': in /home/gert/.cache/bazel/_bazel_gert/9a5697af4b4898056e1adadcd9c31af8/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl: in /home/gert/.cache/bazel/_bazel_gert/9a5697af4b4898056e1adadcd9c31af8/external/upb/bazel/upb_proto_library.bzl: Unable to load file '@bazel_version//:bazel_version.bzl': file doesn't exist
```

Am I missing something, or was this fix not covering this use case?

**Comment by tsvisabo** [comment]
Since `grpc_extra_deps.bzl` is new to 1.26:
http_archive(
    name = "com_github_grpc_grpc",
    strip_prefix = "grpc-1.26.0-pre1",
    urls = [
        "https://github.com/grpc/grpc/archive/v1.26.0-pre1.tar.gz",
    ],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()
