### ISSUE TITLE
ServerBuilder::BuildAndStart hangs on Ubuntu 19.10

### ISSUE THREAD

**Issue by bfowle** [grpc/grpc#21213]
### What version of gRPC and what language are you using?

Tested on v1.24.x and v1.25.x
C++ language

### What operating system (Linux, Windows,...) and version?

Ubuntu 19.10

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc/g++ 9.2.1-9ubuntu2

### What did you do?

- Compiled/installed gRPC according to the installation instructions.
- Compiled `examples/cpp/helloworld` example.
- Tried running `./greeter_server`

### What did you expect to see?

The helloworld application working properly.

##### v1.25.x Test (hangs):

```
$ GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer_check,-timer ./greeter_server 
D1114 16:43:04.016775905   14313 ev_posix.cc:174]            Using polling engine: epollex
D1114 16:43:04.016867235   14313 dns_resolver_ares.cc:503]   Using ares dns resolver
```

...and it's hung here. Specifically line that includes `builder.BuildAndStart()` on this example.

```
$ strace ./greeter_server
...
epoll_create1(EPOLL_CLOEXEC)            = 3
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 4
epoll_ctl(3, EPOLL_CTL_ADD, 4, {EPOLLIN|EPOLLEXCLUSIVE|EPOLLONESHOT|EPOLLET, {u32=0, u64=0}}) = -1 EINVAL (Invalid argument)
close(4)                                = 0
close(3)                                = 0
epoll_create1(EPOLL_CLOEXEC)            = 3
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 4
epoll_ctl(3, EPOLL_CTL_ADD, 4, {EPOLLIN|EPOLLET, {u32=3886127653, u64=94029310171685}}) = 0
uname({sysname="Linux", nodename="<redacted>", ...}) = 0
futex(0x7fdf7afa4500, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fdf7b89dda8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
```

##### v1.24.x Test (segfault):

```
$ GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer_check,-timer gdb ./greeter_server 
...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff725c700 (LWP 31408)]
[New Thread 0x7fffeffff700 (LWP 31409)]
D1114 17:04:06.843734995   31401 ev_posix.cc:174]            Using polling engine: epollex
E1114 17:04:06.843823520   31401 handshaker_registry.cc:103] assertion failed: g_handshaker_factory_lists != nullptr

Thread 1 "greeter_server" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7715899 in __GI_abort () at abort.c:79
#2  0x00007ffff743e2eb in grpc_core::HandshakerRegistry::RegisterHandshakerFactory(bool, grpc_core::HandshakerType, std::unique_ptr<grpc_core::HandshakerFactory, grpc_core::DefaultDelete<grpc_core::HandshakerFactory> >) () from /usr/local/lib/libgrpc.so.8
#3  0x00007ffff74b8f12 in grpc_core::SecurityRegisterHandshakerFactories() () from /usr/local/lib/libgrpc.so.8
#4  0x00007ffff74ba76d in grpc_security_init() () from /usr/local/lib/libgrpc.so.8
#5  0x00007ffff7435a23 in grpc_init () from /usr/local/lib/libgrpc.so.8
#6  0x0000555555565ca4 in grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) ()
#7  0x00007ffff7bf151e in grpc_impl::ServerBuilder::BuildAndStart() () from /usr/local/lib/libgrpc++.so.1
#8  0x0000555555578e29 in RunServer() ()
#9  0x0000555555578f99 in main ()
```

**Comment by sheenaqotj** [comment]
The 1.24 crash is weird, since grpc_init() calls HandshakerRegistry::Init() right before which should initialize it.

@markdroth do you see anything obvious?

**Comment by bhaprayan** [comment]
+1 facing the same issue

`$ strace ./greeter_server
...
epoll_create1(EPOLL_CLOEXEC)            = 3
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 4
epoll_ctl(3, EPOLL_CTL_ADD, 4, {EPOLLIN|EPOLLEXCLUSIVE|EPOLLONESHOT|EPOLLET, {u32=0, u64=0}}) = -1 EINVAL (Invalid argument)
close(4)                                = 0
close(3)                                = 0
epoll_create1(EPOLL_CLOEXEC)            = 3
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 4
epoll_ctl(3, EPOLL_CTL_ADD, 4, {EPOLLIN|EPOLLET, {u32=869709333, u64=93940394407445}}) = 0
uname({sysname="Linux", nodename="bhaprayan", ...}) = 0
futex(0x7f5f44aaa180, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f5f44c20ca8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
`

**Comment by rustyx** [comment]
There are some ODR violations in libgrpc++ (master branch); for example `client_channel.cc` is included in both `libgrpc.so` and `libgrpc++.so`.
That leads to the same `grpc_core::TraceFlag grpc_client_channel_call_trace` being constructed twice (notice `this=0x7fffff7a07f0` in both traces below), creating a loop in the trace flag chain.

Global objects are merged during dynamic loading, but not their initializers, it's a well-known phenomenon (examples: [1](https://stackoverflow.com/questions/26547454/static-variable-is-initialized-twice), [2](https://stackoverflow.com/questions/6714046/c-linux-double-destruction-of-static-variable-linking-symbols-overlap/7053461#7053461), [3](https://stackoverflow.com/questions/19373061/what-happens-to-global-and-static-variables-in-a-shared-library-when-it-is-dynam), [4](https://stackoverflow.com/questions/6538501/linking-two-shared-libraries-with-some-of-the-same-symbols)).

```
#1  0x00007fffff6e4e24 in grpc_core::TraceFlagList::Add (flag=0x7fffff7a07f0 <grpc_core::grpc_client_channel_call_trace>) at src/core/lib/debug/trace.cc:80
#2  0x00007fffff6e4f01 in grpc_core::TraceFlag::TraceFlag (this=0x7fffff7a07f0 <grpc_core::grpc_client_channel_call_trace>, default_enabled=false, name=0x7fffff288a06 "client_channel_call") at src/core/lib/debug/trace.cc:98
#3  0x00007fffff0816bc in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at src/core/ext/filters/client_channel/client_channel.cc:100
#4  0x00007fffff0816ed in _GLOBAL__sub_I_client_channel.cc(void) () at src/core/ext/filters/client_channel/client_channel.cc:4046
#5  0x00007fffff7cf37a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7ffffffedde8, env=env@entry=0x7ffffffeddf8) at dl-init.c:72
#6  0x00007fffff7cf476 in call_init (env=0x7ffffffeddf8, argv=0x7ffffffedde8, argc=1, l=<optimized out>) at dl-init.c:30
#7  _dl_init (main_map=0x7fffff7e9190, argc=1, argv=0x7ffffffedde8, env=0x7ffffffeddf8) at dl-init.c:119
#8  0x00007fffff7c10ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#9  0x0000000000000001 in ?? ()
#10 0x00007ffffffedfff in ?? ()
#11 0x0000000000000000 in ?? ()

(gdb) info sym 0x00007fffff0816ed
_GLOBAL__sub_I_client_channel.cc + 19 in section .text of /usr/local/lib/libgrpc.so.9

#1  0x00007fffff6e4e24 in grpc_core::TraceFlagList::Add (flag=0x7fffff7a07f0 <grpc_core::grpc_client_channel_call_trace>) at src/core/lib/debug/trace.cc:80
#2  0x00007fffff6e4f01 in grpc_core::TraceFlag::TraceFlag (this=0x7fffff7a07f0 <grpc_core::grpc_client_channel_call_trace>, default_enabled=false, name=0x7fffff6f5006 "client_channel_call") at src/core/lib/debug/trace.cc:98
#3  0x00007fffff64d19e in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at src/core/ext/filters/client_channel/client_channel.cc:100
#4  0x00007fffff64d1cf in _GLOBAL__sub_I_client_channel.cc(void) () at src/core/ext/filters/client_channel/client_channel.cc:4046
#5  0x00007fffff7cf37a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7ffffffedde8, env=env@entry=0x7ffffffeddf8) at dl-init.c:72
#6  0x00007fffff7cf476 in call_init (env=0x7ffffffeddf8, argv=0x7ffffffedde8, argc=1, l=<optimized out>) at dl-init.c:30
#7  _dl_init (main_map=0x7fffff7e9190, argc=1, argv=0x7ffffffedde8, env=0x7ffffffeddf8) at dl-init.c:119
#8  0x00007fffff7c10ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#9  0x0000000000000001 in ?? ()
#10 0x00007ffffffedfff in ?? ()
#11 0x0000000000000000 in ?? ()

(gdb) info sym 0x00007fffff64d1cf
_GLOBAL__sub_I_client_channel.cc + 19 in section .text of /usr/local/lib/libgrpc++.so.1
```

If the implementation is the same, why does libgrpc++ depend on libgrpc??

Anyway, as a temporary workaround add a check to `void TraceFlagList::Add(TraceFlag* flag)` (in `src/core/lib/debug/trace.cc`) to avoid adding the flag twice:
```
void TraceFlagList::Add(TraceFlag* flag) {
  for (TraceFlag* t = root_tracer_; t != nullptr; t = t->next_tracer_) {
    if (t == flag) {
      return;
    }
  }
  flag->next_tracer_ = root_tracer_;
  root_tracer_ = flag;
}
```

**Comment by hanhiver** [comment]
> There are some ODR violations in libgrpc++ (master branch); for example `client_channel.cc` is included in both `libgrpc.so` and `libgrpc++.so`.
> That leads to the same `grpc_core::TraceFlag grpc_client_channel_call_trace` being constructed twice (notice `this=0x7fffff7a07f0` in both traces below), creating a loop in the trace flag chain.
> 
> Global objects are merged during dynamic loading, but not their initializers, it's a well-known phenomenon (examples: [1](https://stackoverflow.com/questions/26547454/static-variable-is-initialized-twice), [2](https://stackoverflow.com/questions/6714046/c-linux-double-destruction-of-static-variable-linking-symbols-overlap/7053461#7053461), [3](https://stackoverflow.com/questions/19373061/what-happens-to-global-and-static-variables-in-a-shared-library-when-it-is-dynam), [4](https://stackoverflow.com/questions/6538501/linking-two-shared-libraries-with-some-of-the-same-symbols)).
> 
> ```
> #1  0x00007fffff6e4e24 in grpc_core::TraceFlagList::Add (flag=0x7fffff7a07f0 <grpc_core::grpc_client_channel_call_trace>) at src/core/lib/debug/trace.cc:80
> #2  0x00007fffff6e4f01 in grpc_core::TraceFlag::TraceFlag (this=0x7fffff7a07f0 <grpc_core::grpc_client_channel_call_trace>, default_enabled=false, name=0x7fffff288a06 "client_channel_call") at src/core/lib/debug/trace.cc:98
> #3  0x00007fffff0816bc in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at src/core/ext/filters/client_channel/client_channel.cc:100
> #4  0x00007fffff0816ed in _GLOBAL__sub_I_client_channel.cc(void) () at src/core/ext/filters/client_channel/client_channel.cc:4046
> #5  0x00007fffff7cf37a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7ffffffedde8, env=env@entry=0x7ffffffeddf8) at dl-init.c:72
> #6  0x00007fffff7cf476 in call_init (env=0x7ffffffeddf8, argv=0x7ffffffedde8, argc=1, l=<optimized out>) at dl-init.c:30
> #7  _dl_init (main_map=0x7fffff7e9190, argc=1, argv=0x7ffffffedde8, env=0x7ffffffeddf8) at dl-init.c:119
> #8  0x00007fffff7c10ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
> #9  0x0000000000000001 in ?? ()
> #10 0x00007ffffffedfff in ?? ()
> #11 0x0000000000000000 in ?? ()
> 
> (gdb) info sym 0x00007fffff0816ed
> _GLOBAL__sub_I_client_channel.cc + 19 in section .text of /usr/local/lib/libgrpc.so.9
> 
> #1  0x00007fffff6e4e24 in grpc_core::TraceFlagList::Add (flag=0x7fffff7a07f0 <grpc_core::grpc_client_channel_call_trace>) at src/core/lib/debug/trace.cc:80
> #2  0x00007fffff6e4f01 in grpc_core::TraceFlag::TraceFlag (this=0x7fffff7a07f0 <grpc_core::grpc_client_channel_call_trace>, default_enabled=false, name=0x7fffff6f5006 "client_channel_call") at src/core/lib/debug/trace.cc:98
> #3  0x00007fffff64d19e in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at src/core/ext/filters/client_channel/client_channel.cc:100
> #4  0x00007fffff64d1cf in _GLOBAL__sub_I_client_channel.cc(void) () at src/core/ext/filters/client_channel/client_channel.cc:4046
> #5  0x00007fffff7cf37a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7ffffffedde8, env=env@entry=0x7ffffffeddf8) at dl-init.c:72
> #6  0x00007fffff7cf476 in call_init (env=0x7ffffffeddf8, argv=0x7ffffffedde8, argc=1, l=<optimized out>) at dl-init.c:30
> #7  _dl_init (main_map=0x7fffff7e9190, argc=1, argv=0x7ffffffedde8, env=0x7ffffffeddf8) at dl-init.c:119
> #8  0x00007fffff7c10ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
> #9  0x0000000000000001 in ?? ()
> #10 0x00007ffffffedfff in ?? ()
> #11 0x0000000000000000 in ?? ()
> 
> (gdb) info sym 0x00007fffff64d1cf
> _GLOBAL__sub_I_client_channel.cc + 19 in section .text of /usr/local/lib/libgrpc++.so.1
> ```
> 
> If the implementation is the same, why does libgrpc++ depend on libgrpc??
> 
> Anyway, as a temporary workaround add a check to `void TraceFlagList::Add(TraceFlag* flag)` (in `src/core/lib/debug/trace.cc`) to avoid adding the flag twice:
> 
> ```
> void TraceFlagList::Add(TraceFlag* flag) {
>   for (TraceFlag* t = root_tracer_; t != nullptr; t = t->next_tracer_) {
>     if (t == flag) {
>       return;
>     }
>   }
>   flag->next_tracer_ = root_tracer_;
>   root_tracer_ = flag;
> }
> ```

Many thanks, the workaround works fine for me. I am in a ubuntu 18.04 environment.

**Comment by markdroth** [comment]
That's very interesting.  @nicolasnoble, I'm guessing that this is an artifact of the way our build files are set up?

**Comment by bfowle** [comment]
Issues #21273 and #21280 reporting the same symptoms. Doesn't seem build-related...?

**Comment by Warchant** [comment]
Is it possible to build C++ grpc client without linking to `libgrpc`?

**Comment by parthpower** [comment]
I see the same behavior only when I try to cross-compile for 
Host: i686-unknown-linux-gnu
gcc: 4.8.4
glibc: 2.17
(with `CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"`)

However, it works just fine when compiled with host compiler
Host: x86_64-linux-gnu
gcc: 5.4.0
glibc: 2.23

Fixes from https://github.com/grpc/grpc/issues/21280#issuecomment-558164977 and https://github.com/grpc/grpc/issues/21213#issuecomment-554944145 work. The latter one is more promising as it solves the core problem rather than skipping grpc trace setup altogether.

I can see this issue is after https://github.com/grpc/grpc/commit/87905ae5ead879a3baff731b3bed5408249beacd#diff-3d716411b72686a7bb06ed1a933665b7

**Comment by agudpp** [comment]
as a reference this can also be related with #20757

**Comment by vitakot** [comment]
Same behavior, none of the mentioned fixes helped me.

Ubuntu 19.10
grpc v 1.25.0
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
protoc v 3.8.0

That's really crazy, I can do nothing but wait for fix...

**Comment by Vicfred** [comment]
This was happening to me with version 1.25 on gentoo and ubuntu 18.04, changed to 1.20 and now it's working

**Comment by vitakot** [comment]
I downgraded to 1.24 and it works, but the downgrade was a pain. I thing that grpc make install is broken, sometimes it does not install anything, I had to install it manually. 

Two days of my life are gone and I have a really bad feeling about the maturity of this lib...

**Comment by parthpower** [comment]
https://github.com/grpc/grpc/pull/21329

There was a recent switch from `make` to `cmake` as preferred way to build grpc libs. I wonder if it fixes this issue.

**Comment by ya-mouse** [comment]
Seems like this fixed in 1.26.0.

**Comment by Warchant** [comment]
@ya-mouse just checked - 1.26.0 still has this bug.

**Comment by bduclaux** [comment]
Bug still present with 1.26.0. 
Please change priority to P1 or P0, fix, and more important implement unit testing for helloworld examples !

**Comment by veblush** [comment]
Can you test the bug again since the fix was merged onto both v1.26.x or master branch?

**Comment by rustyx** [comment]
The master branch seems OK now, at least the hello_world example is working.

**Comment by veblush** [comment]
@rustyx Thanks for your confirmation!
@bfowle Can you check this on your environment? The fix is supposed to address "v1.25.x Test (hangs)" but I have no idea on "v1.24.x Test (segfault)" so please check this.

**Comment by baldman88** [comment]
Still present with 1.26.0

**Comment by Warchant** [comment]
@baldman88 try branch 1.26.x

**Comment by bfowle** [comment]
@veblush Hello! I checked with the latest `v1.26.x` branch and was able to properly compile and run the examples, as well as my own programs with this version on Ubuntu 19.10.
Thanks, cheers~

**Comment by miaogen123** [comment]
As I had spent a long time on trying which version could work, I’d like to know what caused this problem.

在 2020年1月18日，上午7:23，Brett Fowle <notifications@github.com<mailto:notifications@github.com>> 写道：


@veblush<https://github.com/veblush> Hello! I checked with the latest v1.26.x branch and was able to properly compile and run the examples, as well as my own programs with this version on Ubuntu 19.10.
Thanks, cheers~

**Comment by donnadionne** [comment]
@miaogen123 
There was an ODR violation which causes an undefined behavior, in this case, a crash. Please see fix https://github.com/grpc/grpc/pull/21662

**Comment by SylvestreG** [comment]
the problem is still here on ArchLinux v 1.26.0-4

**Comment by veblush** [comment]
Thank you for the confirmation.

@SylvestreG The package on ArchLinux is not maintained by us so I'm not sure how they manage it but it doesn't seem that that version got the change since the last release date was 2020-01-02. ([ref](https://www.archlinux.org/packages/community/x86_64/grpc/))

**Comment by fundies** [comment]
the arch package is listed as 2020-02-14 now on arch and I'm on grpc-1.27.2-1 and it still hangs on launching grpc in the same spot

**Comment by JanFeld** [comment]
Got the same behaviour on ARMv7 linux kernel 5.8.0-rc5. On Manjaro with 5.7.17-2 everything is fine.

It blocks on `BuildAndStart()` with ~100 % CPU usage.

I'm using gRPC++ 1.30.2

**Comment by tanglebridge** [comment]
> There are some ODR violations in libgrpc++ (master branch); for example `client_channel.cc` is included in both `libgrpc.so` and `libgrpc++.so`.
> That leads to the same `grpc_core::TraceFlag grpc_client_channel_call_trace` being constructed twice (notice `this=0x7fffff7a07f0` in both traces below), creating a loop in the trace flag chain.

This affects my build as well, and the proposed fix works for me. It is still present in the latest (1.34). My environment:
- g++/gcc 9.3
- ubuntu 20.04
- C++, cmake

The libgrpc++ package that comes with ubuntu 20.04 _does not_ have this issue and works fine. I started developing with that (v1.16.1). Either the code has a different structure, they patched, or they built it differently.

ATM my solution is to patch the library before building, which is a bit of a pain.

**Comment by veblush** [comment]
@tanglebridge What made you think `client_channel.cc` ends up being included in both `libgrpc.so` and `libgrpc++.so`? Can you share me with how to build and see those symbols are found in both? `client_channel.cc` should be in `libgrpc.so` only.

**Comment by tanglebridge** [comment]
Using ar t to list the contents of the libraries (using grpc v1.27.3):
```
$ for f in *.a; do echo $f && ar t $f|grep client_channel.cc; done
$ for f in *.a; do echo "> $f" && ar t $f|grep client_channel.cc; done
> libabsl_bad_optional_access.a
> libabsl_base.a
> libabsl_dynamic_annotations.a
> libabsl_int128.a
> libabsl_log_severity.a
> libabsl_raw_logging_internal.a
> libabsl_spinlock_wait.a
> libabsl_strings.a
> libabsl_strings_internal.a
> libabsl_throw_delegate.a
> libaddress_sorting.a
> libcares.a
> libgpr.a
> libgrpc++.a
> libgrpc.a
client_channel.cc.o
> libgrpc++_alts.a
> libgrpc_cronet.a
client_channel.cc.o
> libgrpc++_error_details.a
> libgrpc_plugin_support.a
> libgrpcpp_channelz.a
> libgrpc++_reflection.a
> libgrpc++_unsecure.a
> libgrpc_unsecure.a
client_channel.cc.o
> libprotobuf.a
> libprotobuf-lite.a
> libprotoc.a
> libupb.a
> libz.a
```
So it occurs in libgrpc.a, libgrpc_cronet.a and libgrpc_unsecure.a. In cmake I use find_package() pretty much as shown in examples.
I use an unsecure channel in my setup. Is it possible it pulls in both `libgrpc.a` and `libgrpc_unsecure.a`?

**Comment by tanglebridge** [comment]
And I didn't really answer your question I realize: I had the same problem occur as was described by others - not getting past BuildAndStart(), traced it down to the flag check. The fix that checks flag existence works for me.

Ergo: I have the same problem.

**Comment by tanglebridge** [comment]
@veblush I just had another realization and a question. My server uses the gRPC mediated client connection locally via domain socket to provide a service over tcp/ip. Both client and server link in the code in question. Since TraceFlag* is static they would operate on the same variable, and hence explain the duplication?

What I don't understand then is why this code worked when I linked dynamically with the ubuntu libgrpc package, and why it fails as it does now when I compile myself and link statically.

**Comment by veblush** [comment]
@veblush libgrpc variants such as _unsecure are expected to have `client_channel` as well. So those variants should be used mutually exclusively.

Having the client and server should be fine and the same TraceFlags* are going to be used for both client and server. ODR violation usually happens when two libraries which are not designed to be used at once are loaded for some reason. Can you narrow down what modules are loaded for your application which doesn't work correctly?

If you use a static-library and a dynamic-library, it could be a culprit.  Also if you use a grpc and grpc_unsecure, it could cause this as well.

**Comment by rustyx** [comment]
ODR violation happens when the same identifier with external linkage is linked into an application more than once, either statically or dynamically.

It actually happens left and right in the wild with all sorts of libraries and often goes unnoticed, only in case of `libgrpc` it causes an infinite loop in the trace chain. With a bit of defensive coding in that area (see my [earlier post](https://github.com/grpc/grpc/issues/21213#issuecomment-554944145)) it can be possible to make it work also under those conditions. Then it won't matter if `libgrpc`, `libgrpc_secure` or `libgrpc++` end up pulled in together (well, it might still matter, but at least it won't hang outright).

**Comment by tanglebridge** [comment]
@rustyx Thanks for that, your code snippet works for me too - saved the bacon. I am doing some dissecting of my code to make sure it is all as it should be.
@veblush I made sure to only have static libs available, and those are the ones linked in (using find_package() in cmake). I am trying to turn things off atm and doing some forensics. Knowing what to look for helps a lot!

**Comment by veblush** [comment]
Although the workaround @rustyx mentioned can solve the case, solving the ODR violation should be the right way in 
 the long run because it can have any problem potentially, which could be more subtle and dangerous.

**Comment by kml-mudgal** [comment]
I am facing this issue on release  1.24.3 
On which release this issue is fixed .

**Comment by Warchant** [comment]
@kml-mudgal 1.26.x but not 1.26.0
