### ISSUE TITLE
Error Installing BoringSSL-GRPC

### ISSUE THREAD

**Issue by bongzlive** [grpc/grpc#21773]
### What version of gRPC and what language are you using?

Trying to install BoringSSL-GRPC (0.0.3) via terminal on Mac OS Catalina 10.15.2

### What operating system (Linux, Windows,...) and version?

Mac OS Catalina 10.15.2

### What runtime / compiler are you using (e.g. python version or version of gcc)

Xcode Environment

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Added pod 'Firebase/Firestore' to the PodFile and ran 'pod install'

### What did you expect to see?

Pods installed successfully

### What did you see instead?

Installing BoringSSL-GRPC (0.0.2)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/k3/8phztphs11d0hbtshqcxx9hr0000gn/T/d20190226-73853-1azgtd4 --template=

Cloning into '/var/folders/k3/8phztphs11d0hbtshqcxx9hr0000gn/T/d20190226-73853-1azgtd4'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

This also takes forever to show this error more than an hour and a half

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by AbScott1985** [comment]
did you manage to fix this as I have the same error

**Comment by PWakwima** [comment]
I have the same error. Is there a fix?

**Comment by AbScott1985** [comment]
I have not found one yet

**Comment by bongzlive** [comment]
Hi,

I managed to resolve this. You need to open the PodFile under your Xcode prroject and do the following...

1. Remove **ALL** Firebase pods from the PodFile and save the PodFile.
2. Make sure Xcode is closed.
3. Open Terminal and cd to your Xcode project directory.
4. Run **'pod install'**
5. Add **pod 'Firebase/Auth'** and **pod 'Firebase/Firestore'** to your PodFile and save the PodFile.
6. Run **'pod install'** and voila.

I hope this helps you guys, of course every case is unique, but I hope we all had the same issue. 

**P.S** If Firebase does not recognize your app during the SDK setup, you might want to check if you have **pod 'Firebase/Analytics'** in your PodFile. If not add it and run another **'pod install'**.

**Comment by AbScott1985** [comment]
so this worked for Firebase/Auth as soon as I done Firebase/Firestore it came up with the same error :(

**Comment by AbScott1985** [comment]
the other ones go straight to firebase where Firestore goes straight to install BoringSSL-GPRC and that is where the error is coming from 

Angela@Iains-iMac ios % pod install
Analyzing dependencies
Downloading dependencies
Installing BoringSSL-GRPC (0.0.3)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/f2/cpx0475j7t52__99k3spzhn00000gp/T/d20200124-14030-1ck4wxp --template=

Cloning into '/var/folders/f2/cpx0475j7t52__99k3spzhn00000gp/T/d20200124-14030-1ck4wxp'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by bongzlive** [comment]
You need to have both pods in your PodFile simultaneously when you run 'pod install' and you need to remove all Firebase installations and dependencies first before you do.

**Comment by AbScott1985** [comment]
could you provide a guide on how to do that please I just want to make sure I am doing it correctly

**Comment by bongzlive** [comment]
Please refer to my comment above that is in numeric bullet point form.

**Comment by AbScott1985** [comment]
thanks I done what you said 

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'

end

This is my pod file

this is my terminal

Angela@Iains-iMac ios % pod init
Angela@Iains-iMac ios % pod install
Analyzing dependencies
Downloading dependencies
Installing BoringSSL-GRPC (0.0.3)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/f2/cpx0475j7t52__99k3spzhn00000gp/T/d20200126-2629-1fdpm6v --template=

Cloning into '/var/folders/f2/cpx0475j7t52__99k3spzhn00000gp/T/d20200126-2629-1fdpm6v'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed


[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by bongzlive** [comment]
Please uncomment line 2 " **# platform :ios, '9.0'** " and re-run the steps above.

**Comment by AbScott1985** [comment]
hi I done what you said this is my pod file 

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
end


this is my terminal 

Angela@Iains-iMac ios % pod install
Analyzing dependencies
Downloading dependencies
Installing BoringSSL-GRPC (0.0.3)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/f2/cpx0475j7t52__99k3spzhn00000gp/T/d20200128-79876-4r6cil --template=

Cloning into '/var/folders/f2/cpx0475j7t52__99k3spzhn00000gp/T/d20200128-79876-4r6cil'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by adarshraj87** [comment]
@AbScott1985 did you managed to find a solution for it ?

**Comment by AbScott1985** [comment]
Yes there was a block on my internet so I tried a vpn and it worked so went on the my network and took off the security on my network

**Comment by adarshraj87** [comment]
Thanks, @AbScott1985 I just figured it out by switching the network, not sure what was issue with network probably something to do with pandemic traffic.

**Comment by AbScott1985** [comment]
I was so annoyed I had changed a lot of my settings and messed around with it so much for it to not be an issue with the app was so angry but at least it is sorted now and I will be checking that first from now on lol glad its sorted x

**Comment by Mohanedy98** [comment]
This fixed the problem for me 
in the project directory using terminal
```
rm -rf Pods

rm Podfile.lock

pod install
```

**Comment by DustinJSilk** [comment]
Connecting to my VPN solved it, too. Weird.

**Comment by ghasemikasra39** [comment]
same here, Any solutions?

**Comment by joshua-hester** [comment]
Compiling with/without your VPN does not make sense for that solution. Most likely just Pods using cache previously installed with later versions. BoringSSL is a heavily used packaged throughout different packages. 

Also, the comment about "Pandemic Traffic" is hilarious.. :P

**Comment by Mauratay** [comment]
@joshua-hester can you elaborate about that please?

**Comment by Mauratay** [comment]
Refer to: https://github.com/firebase/firebase-ios-sdk/issues/4994#issuecomment-592763815

**Comment by DustinJSilk** [comment]
Brand new laptop, fresh environment, still struggling with this problem.

**Comment by sowntharsakthi** [comment]
Hi,

I managed to resolve this. You need to open the PodFile under your Xcode prroject and do the following...


Remove Firebase/Firestore pods from the PodFile and save the PodFile.
Make sure Xcode is closed.
Open Terminal and cd to your Xcode project directory.
Run 'pod install'
After that you add the fireStore then its worked for me
Add pod 'Firebase/Auth' and pod 'Firebase/Firestore' to your PodFile and save the PodFile.
Run 'pod install'

**Comment by veblush** [comment]
Although this was closed a while back, it seems that there is still an issue. Yulin, can you take a look at this?

**Comment by yulin-liang** [comment]
> Although this was closed a while back, it seems that there is still an issue. Yulin, can you take a look at this?

Sure, I'll take a look at it.

**Comment by yulin-liang** [comment]
> Brand new laptop, fresh environment, still struggling with this problem.

Have you fixed it? If not, have you tried the solution that bongzlive@ mentioned above?

**Comment by akhilsanker** [comment]
Hi facing the same issue while adding 'pod 'Firebase/Firestore'.
Any working solution?

Thanks

**Comment by yulin-liang** [comment]
> Hi facing the same issue while adding 'pod 'Firebase/Firestore'.
> Any working solution?
> 
> @yulin-liang , Have you got any workaround?
> 
> Thanks

Have you tried the solution bongzlive@ mentioned above? 

- Remove ALL Firebase pods from the PodFile and save the PodFile.
- Make sure Xcode is closed.
- Open Terminal and cd to your Xcode project directory.
- Run 'pod install'
- Add pod 'Firebase/Auth' and pod 'Firebase/Firestore' to your PodFile and save the PodFile.
- Run 'pod install'.

**Comment by lemusthelroy** [comment]
So I have this issue...is there any resolution on the horizon?

**Comment by lemusthelroy** [comment]
To give some context to this...I am using a brand new MacBook on Catalina and I am using Xcode 12.0.1. I can build an iOS app with the basic flutter counter app and this displays in the iPhone simulator as expected.  However, I have another app that runs fine on Android on Windows but I can't get past this error on macOS. 

This morning I went to the effort of removing anything Firebase related out of my pubspec and deleted pods with the commands suggested above. However, this produced the same error.

**Comment by lemusthelroy** [comment]
I have now isolated this issue in my case where I am using flutter. Removing the dependency cloud_firestore, allows me to successfully pod install. However, this dependency is required in my app and every time I add it back in - I get the above error.

**Comment by lemusthelroy** [comment]
To add even further context, it turns out the precise command that is failing is git clone https://github.com/CocoaPods/Specs.git, which is hanging up unexpectedly. See https://github.com/flutter/flutter/issues/30185 where they refer to this.

Only way I am going to resolve this is finding a way to pull from this repo without it hanging up. Thought I would post this update as it confirms issue is not with BoringSSL itself, but during pod install when the above repo is cloned.

**Comment by lemusthelroy** [comment]
-> Installing BoringSSL-GRPC (0.0.7)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/5y/kz_7kysj73z8jtb1xzc0skmr0000gp/T/d20200928-1463-1g58de
     --template=
     Cloning into '/var/folders/5y/kz_7kysj73z8jtb1xzc0skmr0000gp/T/d20200928-1463-1g58de'...
     error: RPC failed; curl 18 transfer closed with outstanding read data remaining
     fatal: the remote end hung up unexpectedly
     fatal: early EOF
     fatal: index-pack failed

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/5y/kz_7kysj73z8jtb1xzc0skmr0000gp/T/d20200928-1463-1g58de --template=

Cloning into '/var/folders/5y/kz_7kysj73z8jtb1xzc0skmr0000gp/T/d20200928-1463-1g58de'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by lemusthelroy** [comment]
My current internet connection is 110 Mbps, so no issues there

**Comment by yulin-liang** [comment]
@lemusthelroy Thanks for the information, can you try to remove `ios/Flutter/Flutter.framework`, `ios/Pods`, and `Podfile.lock` before running `pod install`?

**Comment by lemusthelroy** [comment]
Same error unfortunately 😭

**Comment by yulin-liang** [comment]
@lemusthelroy Can you create a simple demo that I can reproduce the issue?

**Comment by lemusthelroy** [comment]
For me to get the issue all I have to do is the following:-

1. `flutter create demoApp`
2. Add cloud_firestore as a dependency in pubspec.yaml
3. `flutter run`

**Comment by yulin-liang** [comment]
@lemusthelroy I tried to add `cloud_firestore: ^0.12.9+5` in the `pubspec.yaml` and ran `pod install` in `iOS/` directory, I can install it successfully. What's the version of your flutter? Can you also paste your dependencies?
<img width="1087" alt="Screen Shot 2020-09-28 at 1 04 49 PM" src="https://user-images.githubusercontent.com/64815511/94480532-4682ef00-018b-11eb-84cc-36112b4508a7.png">

**Comment by lemusthelroy** [comment]
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (2 weeks ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

**Comment by lemusthelroy** [comment]
name: boringSSLBug
description: A new Flutter project.

publish_to: 'none'

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

**Comment by yulin-liang** [comment]
@lemusthelroy It looks like an git internet connection issue, you can take a look at this post, https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining.
I also found a similar [issue](https://github.com/CocoaPods/CocoaPods/issues/9564) in Cocoapods repo. Can you try to increase buffer size? Hope it can work.
```
git config --global http.postBuffer 524288000
```

**Comment by lemusthelroy** [comment]
Yeah I've seen that suggestion before. Tried it again and still the same issue 😢 I'm pretty new to developing on iOS but had enjoyed Flutter on Windows over the last year, just a shame I can't any of my apps on iOS atm.

**Comment by lemusthelroy** [comment]
So on a hunch, I ran 'flutter run' on a hotspot and it worked just fine. For all others that may hit the same issue, I am in the UK and using Virgin Media. I had to log into Virgin Media website, (not to the router), and disable Child Safe.

**Comment by yulin-liang** [comment]
This seems like an internet connection issue and not much we can do. For those who may ran into the same issue, please try to do the following first:
```
Remove Firebase/Firestore pods from the PodFile and save the PodFile.
Make sure Xcode is closed.
Open Terminal and cd to your Xcode project directory.
Run 'pod install'
After that you add the fireStore then its worked for me
Add pod 'Firebase/Auth' and pod 'Firebase/Firestore' to your PodFile and save the PodFile.
Run 'pod install'
``` 

If it doesn't work for you, you may need to switch to another network or check your network configuration.

**Comment by vharron** [comment]
This is hard to believe. I root caused this issue to a wired ethernet adapter I was using. wifi and two other wired ethernet adapters worked.

Note that ethernet adapter seemed to work fine otherwise. The git clone worked fine from the command line, the issue only surfaced when ruby Process.spawn executed it!

**Comment by investisocial** [comment]
> This is hard to believe. I root caused this issue to a wired ethernet adapter I was using. wifi and two other wired ethernet adapters worked.
> 
> Note that ethernet adapter seemed to work fine otherwise. The git clone worked fine from the command line, the issue only surfaced when ruby Process.spawn executed it!

@vharron Unbelievable! I've read your post and I've tried to unplug my network adapter and update all the pods with wifi connection. It greatly works! It fixed my issue. You saved me. Thank you. My network adapter is: Atolla wired sub/ethernet apple adapter. I will buy an original adapter 👍

**Comment by louicoder** [comment]
> hi I done what you said this is my pod file
> 
> ```
> # Uncomment the next line to define a global platform for your project
>  platform :ios, '9.0'
> 
> target 'Runner' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   use_frameworks!
> 
>   # Pods for Runner
> 
> 	pod 'Firebase/Analytics'
> 	pod 'Firebase/Auth'
> 	pod 'Firebase/Firestore'
> end
> ```
> 
> this is my terminal
> 
> ```
> Angela@Iains-iMac ios % pod install
> Analyzing dependencies
> Downloading dependencies
> Installing BoringSSL-GRPC (0.0.3)
> 
> [!] Error installing BoringSSL-GRPC
> [!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/f2/cpx0475j7t52__99k3spzhn00000gp/T/d20200128-79876-4r6cil --template=
> 
> Cloning into '/var/folders/f2/cpx0475j7t52__99k3spzhn00000gp/T/d20200128-79876-4r6cil'...
> error: RPC failed; curl 18 transfer closed with outstanding read data remaining
> fatal: the remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> ```

Please change to another network. Changing the network helped me resolve this issue. I'm not sure why because even the network I was using was working fine.

**Comment by MuhamadJalal** [comment]
For Flutter developers:
change all firebase dependencies I use to this versions solve my problem

 ```
  firebase_messaging: ^10.0.2
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.1
  firebase_storage: ^8.1.3
  firebase_core: ^1.3.0
```

**Comment by fakfa19** [comment]
I fix by add
`pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.8.0'`
or 
`pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.6.0'`
in `ios/Podfile`

Example:
```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.8.0'
  pod 'Firebase/Core'


  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by hachem9** [comment]
to solve this delete podfile and podfile.lock then run (flutter pub get) then in terminal run  (cd ios)  then run (pod install).

**Comment by rahulsharma20** [comment]
> > This is hard to believe. I root caused this issue to a wired ethernet adapter I was using. wifi and two other wired ethernet adapters worked.
> > Note that ethernet adapter seemed to work fine otherwise. The git clone worked fine from the command line, the issue only surfaced when ruby Process.spawn executed it!
> 
> @vharron Unbelievable! I've read your post and I've tried to unplug my network adapter and update all the pods with wifi connection. It greatly works! It fixed my issue. You saved me. Thank you. My network adapter is: Atolla wired sub/ethernet apple adapter. I will buy an original adapter 👍

This actually resolved the issue for me

**Comment by usaman9040** [comment]
Using a VPN worked for me 

[stackoverflow](https://stackoverflow.com/a/77632470/8410341)

**Comment by mrasityilmaz** [comment]
I have tried many different solution but this fixed my problem.

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'FirebaseFirestore/WithLeveldb', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.9.0'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by Musyimi97** [comment]
For flutter, I fixed mine using `git config --global http.postBuffer 1048576000` to  increase the postBuffer size in my git configuration. This helps with issues related to large files in the repository. Then `cd ios && rm -rf Pods && rm Podfile.lock && gem install cocoapods && pod install`

**Comment by belle-beauty** [comment]
> For flutter, I fixed mine using `git config --global http.postBuffer 1048576000` to increase the postBuffer size in my git configuration. This helps with issues related to large files in the repository. Then `cd ios && rm -rf Pods && rm Podfile.lock && gem install cocoapods && pod install`

This did not fix the issue. I still get the error in react native version 0.73.0

**Comment by bilalahmad9** [comment]
### git config --global http.postBuffer 524288000

for me its working by running this command, after running this command inside iOS folder of flutter project I run **### pod install** command and all working fine

**Comment by sayedmoataz** [comment]
> @lemusthelroy It looks like an git internet connection issue, you can take a look at this post, https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining. I also found a similar [issue](https://github.com/CocoaPods/CocoaPods/issues/9564) in Cocoapods repo. Can you try to increase buffer size? Hope it can work.
> 
> ```
> git config --global http.postBuffer 524288000
> ```

that's working for me, thanks

**Comment by abdulmoiz02** [comment]
git config --global http.postBuffer 524288000 
solved using this

**Comment by Tedmbg** [comment]
changing the network worked for me

**Comment by eslam-hegazy-runprof** [comment]
![Screenshot 2024-05-08 at 7 05 08 PM](https://github.com/grpc/grpc/assets/129666754/4a8957b4-96c4-4412-a168-bead430b1880)

this is solution
pod update

**Comment by muhammadali543** [comment]
just provide any progress bar or size of file, there is noting what the hell? Very disappointed. I have tried more than 50 times but not know what's size evey time got error after 200mb of internet used.

[!] Error installing BoringSSL-GRPC
[!] /usr/local/bin/git clone https://github.com/google/boringssl.git /var/folders/yw/bfsq8qr95qs8x5gws3_jt4vm0000gn/T/d20240710-3521-tmnryv --template=

Cloning into '/var/folders/yw/bfsq8qr95qs8x5gws3_jt4vm0000gn/T/d20240710-3521-tmnryv'...
error: RPC failed; curl 92 HTTP/2 stream 3 was not closed cleanly: CANCEL (err 8)
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by Mahmoudhodhod** [comment]
Here's a revised version of your documentation that omits the specific real path of the project while still guiding users through the process:

---

### Step 1: Clone BoringSSL Manually
1. Open Terminal.
2. Navigate to a directory where you want to clone BoringSSL (e.g., `~/Documents`):

   ```bash
   cd ~/Documents
   ```

3. Clone the repository:

   ```bash
   git clone https://github.com/google/boringssl.git
   ```

### Step 2: Specify the Local Path in Your Podfile
1. Open your Podfile in your Flutter project's `ios` directory. You can use a text editor like nano, vim, or any graphical text editor:

   ```bash
   cd ios
   nano Podfile
   ```

2. Locate the line for `BoringSSL-GRPC` and modify it to specify the local path. Replace the existing line with:

   ```ruby
   pod 'BoringSSL-GRPC', :path => '../Documents/boringssl'
   ```

   Adjust the path based on where you cloned BoringSSL relative to your Podfile.

### Step 3: Create the Podspec File
If you encounter an error indicating that CocoaPods couldn't find a .podspec file for BoringSSL-GRPC, follow these steps:

1. Navigate to the BoringSSL directory:

   ```bash
   cd ../boringssl
   ```

2. Create a new file named `BoringSSL-GRPC.podspec`:

   ```bash
   nano BoringSSL-GRPC.podspec
   ```

3. Copy and paste the following content into the `BoringSSL-GRPC.podspec` file:

   ```ruby
   Pod::Spec.new do |s|
     s.name         = 'BoringSSL-GRPC'
     s.version      = '0.0.32'  # Update this line if necessary
     s.summary      = 'BoringSSL forked from OpenSSL.'
     s.description  = <<-DESC
       BoringSSL is a fork of OpenSSL that is designed to meet the needs of Google and its users. 
       It is a C library that provides cryptographic operations.
     DESC
     s.homepage     = 'https://boringssl.googlesource.com/boringssl'
     s.license      = { :file => 'LICENSE' }
     s.author       = { 'Google' => 'https://www.google.com/' }
     s.source       = { :git => 'https://boringssl.googlesource.com/boringssl.git', :tag => s.version.to_s }
     s.platform     = :ios, '9.0'
     s.source_files  = 'include/**', 'crypto/**', 'ssl/**'
   end
   ```

4. Save and close the file.

### Step 4: Clean and Re-Install Pods
To ensure everything is in sync, follow these steps:

1. Clean the Pod Cache:

   ```bash
   pod cache clean --all
   ```

2. Delete the Pods folder and Podfile.lock:

   ```bash
   rm -rf Pods Podfile.lock
   ```

3. Re-Install Pods:

   ```bash
   pod install
   ```

---

Feel free to adjust any part of this documentation as needed!

**Comment by yingyugang** [comment]
`[!] Error installing BoringSSL-GRPC
[!] /opt/homebrew/bin/git clone https://github.com/google/boringssl.git /var/folders/6v/fc5vp06x6zx9h6ydjr9pgm7c0000gq/T/d20241008-28534-pcd4la --template=

Cloning into '/var/folders/6v/fc5vp06x6zx9h6ydjr9pgm7c0000gq/T/d20241008-28534-pcd4la'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 5547 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output`

By this error up, I solved it as this:
git config --global http.lowSpeedTime 999999

**Comment by brunolorente** [comment]
> ### git config --global http.postBuffer 524288000
> for me its working by running this command, after running this command inside iOS folder of flutter project I run **### pod install** command and all working fine

Worked for me thx

**Comment by farhan-pathan-us** [comment]
Downloading dependencies
Installing BoringSSL-GRPC (0.0.37)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/m0/v9n1zbh52s136_9vx6x6ffl80000gp/T/d20250411-48533-1hmnvc2 --template=

Cloning into '/var/folders/m0/v9n1zbh52s136_9vx6x6ffl80000gp/T/d20250411-48533-1hmnvc2'...
error: RPC failed; curl 56 Recv failure: Connection reset by peer
error: 1759 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
