### ISSUE TITLE
"Failed to connect to remote host: FD Shutdown" when client talks to server in same binary

### ISSUE THREAD

**Issue by ensonic** [grpc/grpc#22088]
This is maybe a duplicate of https://github.com/grpc/grpc/issues/19161, unfortunately that ticket did not mention where/how to "increase the wait time" (DEFAULT_POLL_INTERVAL).

We're getting errors like:
```
"Connect failed: {"created":"@1582198742.973444006","description":"Failed to connect to remote host: FD Shutdown","file":"third_party/grpc/src/core/lib/iomgr/lockfree_event.cc","file_line":195,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1582198742.973420053","description":"connect() timed out","file":"third_party/grpc/src/core/lib/iomgr/tcp_client_posix.cc","file_line":112}],"target_address":"ipv4:10.100.214.244:12346"}
"
```
where the client is retrying a dozen times and then it fails. 

In our case we have a grpc server that gets the initial call from a remote client. The case were the error happens is a nested call, where the server invokes itself. This works when we run the server standalone, but fails when it is running in a container.

**Comment by ensonic** [comment]
Found https://github.com/grpc/grpc/blob/master/doc/environment_variables.md
and tried
GRPC_CLIENT_CHANNEL_BACKUP_POLL_INTERVAL_MS=10000
but it does not help.

**Comment by ensonic** [comment]
This was causes due to a mix of grpc versions.

**Comment by jojotaro123** [comment]
how to slove it?

**Comment by stinovlas** [comment]
@ensonic I'm interested, how did you resolve the issue in the end? Did mix of grpc verisions cause the `FD Shutdown` itself, or didi it cause a problem with using `GRPC_CLIENT_CHANNEL_BACKUP_POLL_INTERVAL_MS`?

**Comment by ensonic** [comment]
@stinovlas in our case it was resolved by aligning the grpc versions, back then and we never saw the problem again. Sound a bit as if this was super specific to the version skew we had (and maybe could be seen as a bug). Sadly I did not record the before and after versions.

**Comment by anaser-fts** [comment]
> @stinovlas in our case it was resolved by aligning the grpc versions, back then and we never saw the problem again. Sound a bit as if this was super specific to the version skew we had (and maybe could be seen as a bug). Sadly I did not record the before and after versions.

@stinovlas 
Could you please explain what you mean by "aligning versions"? 
Thanks in advance

**Comment by stinovlas** [comment]
> @stinovlas Could you please explain what you mean by "aligning versions"? Thanks in advance

I'm afraid you'll have to ask @ensonic for further details (although based on his answer above, he may not have any). We're still experiencing the issue.

**Comment by mschaef-da** [comment]
> > @stinovlas in our case it was resolved by aligning the grpc versions, back then and we never saw the problem again. Sound a bit as if this was super specific to the version skew we had (and maybe could be seen as a bug). Sadly I did not record the before and after versions.
> 
> @stinovlas Could you please explain what you mean by "aligning versions"? Thanks in advance

I can't speak to what @stinovlas has seen, but I ran into something very similar with a JVM backend on `1.67.1` and a Python frontend on `1.68.1`. 

Downgrading the Python to the same `1.67.1` as the JVM backend seems to have cleared up the `FD shutdown` error.
