### ISSUE TITLE
ClientWriter::Write() does not return false when stream is closed by the server

### ISSUE THREAD

**Issue by santigl** [grpc/grpc#23881]
### What version of gRPC and what language are you using?
gRPC v1.16 with C++

### What operating system (Linux, Windows,...) and version?
Debian testing

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 8.3.0

### What did you do?
Taking the `RecordRoute()` call defined in [examples/protos](https://github.com/grpc/grpc/blob/master/examples/protos/route_guide.proto) as:
```javascript
rpc RecordRoute(stream Point) returns (RouteSummary) {}
```
I [modified the server implementation](https://github.com/santigl/grpc/blob/461fc70faea60af17c708e918d8fd47c42489a4f/examples/cpp/route_guide/route_guide_server.cc#L106) to immediately return `Status::OK` without reading messages from the client's stream. 

### What did you expect to see?
`ClientWriter::Write()` returning `false`when the client calls it for the second time.

### What did you see instead?
`ClientWriter::Write()` keeps returning `true`, failing to indicate to the client that the server has closed its end of the RPC.

#### CLI outputs
These are the outputs obtained when running the adaptation of the `route_guide` example to recreate this issue from this branch: https://github.com/santigl/grpc/tree/santigl/server-close-client-stream/examples/cpp/route_guide. (The code can be built and run using the same instructions provided in the gRPC docs.)

##### Server
```bash
> ./route_guide_server
DB parsed, loaded 100 features.
Server listening on 0.0.0.0:50051
RecordRoute() called, immediately returning OK
```

##### Client
```bash
> ./route_guide_client    
DB parsed, loaded 100 features.
-------------- RecordRoute --------------
Visiting point 41.5302, -74.8416 writer->Write()
Visiting point 40.2647, -74.7072 writer->Write()
Visiting point 40.1809, -74.4158 writer->Write()
Visiting point 40.4318, -74.0836 writer->Write()
Visiting point 40.6422, -74.7728 writer->Write()
Visiting point 40.7114, -74.9746 writer->Write()
Visiting point 40.4701, -74.4782 writer->Write()
Visiting point 40.1809, -74.4158 writer->Write()
Visiting point 41.0322, -74.7872 writer->Write()
Visiting point 41.6561, -74.6722 writer->Write()
Called writer->Write() 10 times
writer->Finish() returned OK

```

### Related issue
This is the same behavior as described in #14812 for the async implementation.

**Comment by veblush** [comment]
I believe this was fixed. Can you please test this with the latest version of gRPC?

**Comment by santigl** [comment]
@veblush: I tried it with v1.31.0 and I could still see the stream not getting closed immediately.

However, in the executions I made (this time inside a Docker container), `writer->Write()` started to return `false` after around 5-8 calls to it (running the client different times yielded different numbers).

**Comment by veblush** [comment]
@santigl Thank you for the test. If you eventually got the `false`, it might be because it takes the client sometime to receive the status change from the server.

@yashykt WDTY?

**Comment by yashykt** [comment]
That seems to be working as expected.

**Comment by yashykt** [comment]
ClientWriter::Write() should only start failing once the client see the end of stream.

**Comment by santigl** [comment]
That's great to know!

Thanks a lot for your help and for fixing the issue, @veblush and @yashykt.
