### ISSUE TITLE
"Segmentation fault" on alpine linux

### ISSUE THREAD

**Issue by knapo** [grpc/grpc#27995]
### What version of gRPC and what language are you using?
`grpc-1.41.0-x86_64-linux` on ruby 3.0.2

### What operating system (Linux, Windows,...) and version?
Alpine Linux 3.14 (ruby `3.0.2-alpine3.14` docker image)

### What runtime / compiler are you using (e.g. python version or version of gcc)
ruby version

I tried with both `gcompat` and `libc6-compat` alpine packages.

### What did you do?

I use [google-cloud-pubsub](https://rubygems.org/gems/google-cloud-pubsub/) to get/create pub/sub topic or publish message to a pub/sub topic.

https://rubygems.org/gems/google-cloud-pubsub/

### What did you expect to see?
Like for the same code on OSX 11.6, Debian bullseye (`3.0.2-slim-bullseye` docker image) or when ruby platform is forced (both `3.0.2-slim-bullseye` and `3.0.2-alpine3.14`) having no code exceptions.

### What did you see instead?

Segmentation fault:

```
 /usr/local/bundle/gems/grpc-1.41.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:367: [BUG] Segmentation fault at 0x000000000005e6e6
 ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-musl]
 
 -- Control frame information -----------------------------------------------
 c:0034 p:---- s:0211 e:000210 CFUNC  :run_batch
 c:0033 p:0088 s:0206 e:000205 METHOD /usr/local/bundle/gems/grpc-1.41.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:367
 c:0032 p:0012 s:0197 e:000196 BLOCK  /usr/local/bundle/gems/grpc-1.41.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:174
 c:0031 p:0013 s:0194 e:000193 METHOD /usr/local/bundle/gems/grpc-1.41.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:170
 c:0030 p:0010 s:0187 e:000186 BLOCK  /usr/local/bundle/gems/grpc-1.41.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:173 [FINISH]
 c:0029 p:0061 s:0184 e:000183 METHOD /usr/local/bundle/gems/gapic-common-0.7.0/lib/gapic/grpc/service_stub/rpc_call.rb:121
 c:0028 p:0032 s:0172 e:000171 METHOD /usr/local/bundle/gems/gapic-common-0.7.0/lib/gapic/grpc/service_stub.rb:156
 c:0027 p:0312 s:0162 e:000161 METHOD /usr/local/bundle/gems/google-cloud-pubsub-v1-0.6.0/lib/google/cloud/pubsub/v1/publisher/client.rb:501
 c:0026 p:0016 s:0152 e:000151 METHOD /usr/local/bundle/gems/google-cloud-pubsub-2.9.0/lib/google/cloud/pubsub/service.rb:109
 c:0025 p:0044 s:0146 e:000145 METHOD /usr/local/bundle/gems/google-cloud-pubsub-2.9.0/lib/google/cloud/pubsub/project.rb:165
```

**Comment by ejona86** [comment]
Looking at objdump, this looks to be similar to grpc/grpc-java#8751. It appears __strdup isn't available and the linker doesn't produce a clean error.

```
000000000005e6e0 <__strdup@plt>:
   5e6e0:	ff 25 8a cc 59 00    	jmp    *0x59cc8a(%rip)        # 5fb370 <__strdup@GLIBC_2.2.5>
   5e6e6:	68 6b 00 00 00       	push   $0x6b
   5e6eb:	e9 30 f9 ff ff       	jmp    5e020 <grpc_1.0@@grpc_1.0+0x5e020>
```

If you read through that issue though, I'd have expected Alpine 3.13 to resolve the problem. Poking at the image, things look right. I suspect the issue is that the grpc_c.so's linker isn't being used and ruby itself is using the musl linker. When I do the `LD_PRELOAD=/lib/libgcompat.so.0` trick, ldd seems happy. I'd suggest LD_PRELOAD as a temporary workaround.

**Comment by alikinir** [comment]
Hi, 
Unfortunately LD_PRELOAD=/lib/libgcompat.so.0 possibly fixing this issue, but causing the system to fail to start. Any chance you can prioritize the fix? We are really stuck because of that. 
Thanks in advance.

**Comment by jonmchan** [comment]
I can confirm that this is still failing on grpc-1.43.1:

```
 /usr/local/bundle/gems/grpc-1.43.1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:367: [BUG] Segmentation fault at 0x00000000000636e6
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux-musl]
-- Control frame information -----------------------------------------------
c:0012 p:---- s:0082 e:000081 CFUNC :run_batch
c:0011 p:0088 s:0077 e:000076 METHOD /usr/local/bundle/gems/grpc-1.43.1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:367
c:0010 p:0009 s:0068 e:000067 BLOCK /usr/local/bundle/gems/grpc-1.43.1-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:180
c:0009 p:0013 s:0065 e:000064 METHOD /usr/local/bundle/gems/grpc-1.43.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:170
c:0008 p:0093 s:0058 e:000057 METHOD /usr/local/bundle/gems/grpc-1.43.1-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:179
c:0007 p:0067 s:0040 e:000039 BLOCK /usr/local/bundle/gems/grpc-1.43.1-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:171 [FINISH]
c:0006 p:0022 s:0035 e:000034 METHOD /usr/local/bundle/gems/fabric-gateway-0.4.0/lib/fabric/client.rb:75
c:0005 p:0018 s:0029 e:000028 METHOD /usr/local/bundle/gems/fabric-gateway-0.4.0/lib/fabric/entities/proposal.rb:139
c:0004 p:0019 s:0022 e:000021 METHOD /usr/local/bundle/gems/fabric-gateway-0.4.0/lib/fabric/contract.rb:103
c:0003 p:0015 s:0015 e:000014 METHOD /usr/local/bundle/gems/fabric-gateway-0.4.0/lib/fabric/contract.rb:64
c:0002 p:0062 s:0009 e:000008 BLOCK benchmarks.rb:59 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]
```

**Comment by alto-ruby** [comment]
The strdup issue should have been fixed a while back but was recently re-introduced in 1.57.0.
#34177 is the new fix.

**Comment by jdcalvin** [comment]
Confirmed this is still occuring in 1.73

ruby 3.0.6 and alpine 3.16
