### ISSUE TITLE
PHP gRPC extension causes fpm child to hang up on shutdown

### ISSUE THREAD

**Issue by mkopentag** [grpc/grpc#30526]
### What version of gRPC and what language are you using?
gRPC 1.48.0, PHP 8.1.9

### What operating system (Linux, Windows,...) and version?
Linux 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64
Alpine 3.16 under Docker

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc version 11.2.1 20220219 (Alpine 11.2.1_git20220219)
PHP 8.1.9

### What did you do?
Just installed PHP gRPC extension 1.48.0 and enabled preloading, proceeded as normal without utilizing any gRPC PHP code.
You can use [following](https://github.com/mkopentag/php-grpc-with-preloading) repo to reproduce it as well. Just run it with docker-compose up -d, hit localhost:11167 five times. FPM will try to restart the child after five requests and just hang up.

It starts to work fine if I either:
1. Don't install gRPC extension
2. Run container as a root
3. Disable preloading

Also I have noticed that there was [similar issue](https://github.com/grpc/grpc/issues/11711) few years ago that was fixed.

### What did you expect to see?
PHP/FPM worker should normally shutdown.

### What did you see instead?

FPM workers fail to shutdown properly, which eventually caused the FPM pool to max out its children, and eventually crash:

```
(gdb) bt
#0  0x00007ff14b02fa13 in __syscall6 (a6=<optimized out>, a5=<optimized out>, a4=<optimized out>, a3=<optimized out>, a2=<optimized out>, a1=<optimized out>, n=<optimized out>) at ./arch/x86_64/syscall_arch.h:59
#1  syscall (n=<optimized out>) at src/misc/syscall.c:20
#2  0x00007ff149f28633 in absl::lts_20220623::synchronization_internal::FutexImpl::WaitUntil (t=..., val=0, v=0x7ff14979c140) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/futex.h:104
#3  absl::lts_20220623::synchronization_internal::Waiter::Wait (this=this@entry=0x7ff14979c140, t=t@entry=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/waiter.cc:93
#4  0x00007ff149f28521 in AbslInternalPerThreadSemWait_lts_20220623 (t=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/per_thread_sem.cc:89
#5  0x00007ff149b9d161 in absl::lts_20220623::synchronization_internal::PerThreadSem::Wait (t=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/internal/per_thread_sem.h:107
#6  absl::lts_20220623::Mutex::DecrementSynchSem (t=..., w=<optimized out>, mu=0x7ff14a2605d0 <g_mu>) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/mutex.cc:579
#7  absl::lts_20220623::CondVar::WaitCommon (this=0x7ff14a2605b8 <g_cv_shutdown>, mutex=0x7ff14a2605d0 <g_mu>, t=...) at /tmp/pear/temp/grpc/third_party/abseil-cpp/absl/synchronization/mutex.cc:2577
#8  0x00007ff149dc0e1f in gpr_cv_wait (cv=0x7ff14a2605b8 <g_cv_shutdown>, mu=0x7ff14a2605d0 <g_mu>, abs_deadline=...) at /tmp/pear/temp/grpc/src/core/lib/gpr/sync_abseil.cc:85
#9  0x00007ff149df49d7 in stop_threads () at /tmp/pear/temp/grpc/src/core/lib/iomgr/timer_manager.cc:327
#10 0x00007ff149eaa9d4 in grpc_shutdown_internal_locked () at /tmp/pear/temp/grpc/src/core/lib/surface/init.cc:179
#11 0x00007ff149eaacb0 in grpc_shutdown () at /tmp/pear/temp/grpc/src/core/lib/surface/init.cc:221
#12 0x00007ff149edf5f9 in zm_shutdown_grpc (type=<optimized out>, module_number=<optimized out>) at /tmp/pear/temp/grpc/src/php/ext/grpc/php_grpc.c:575
#13 zm_shutdown_grpc (type=<optimized out>, module_number=<optimized out>) at /tmp/pear/temp/grpc/src/php/ext/grpc/php_grpc.c:564
#14 0x000055f0e4f62ed6 in module_destructor (module=0x7ff14a6e7a90) at /usr/src/php/Zend/zend_API.c:2971
#15 0x000055f0e4f5411b in module_destructor_zval (zv=0x7ffe67f383d0) at /usr/src/php/Zend/zend.c:849
#16 0x000055f0e4f6f9d0 in _zend_hash_del_el_ex (ht=0x55f0e6025e20 <module_registry>, idx=33, p=0x7ff14a760b70, prev=0x0) at /usr/src/php/Zend/zend_hash.c:1355
#17 0x000055f0e4f6faaf in _zend_hash_del_el (ht=0x55f0e6025e20 <module_registry>, idx=33, p=0x7ff14a760b70) at /usr/src/php/Zend/zend_hash.c:1378
#18 0x000055f0e4f71457 in zend_hash_graceful_reverse_destroy (ht=0x55f0e6025e20 <module_registry>) at /usr/src/php/Zend/zend_hash.c:1832
#19 0x000055f0e4f605d4 in zend_destroy_modules () at /usr/src/php/Zend/zend_API.c:2333
#20 0x000055f0e4f54598 in zend_shutdown () at /usr/src/php/Zend/zend.c:1108
#21 0x000055f0e4eaa2d2 in php_module_shutdown () at /usr/src/php/main/main.c:2414
#22 0x000055f0e50e31ca in main (argc=1, argv=0x7ffe67f38998) at /usr/src/php/sapi/fpm/fpm/fpm_main.c:1970
```

**Comment by zeriyoshi** [comment]
@stanley-cheung 
How is the progress on this issue?
We are probably having the same problem and are addressing it by lowering the version.

**Comment by alto-php** [comment]
add `grpc.enable_fork_support=1` to your php.ini should fix this.

**Comment by Nyholm** [comment]
> add grpc.enable_fork_support=1 to your php.ini should fix this.

Thank you for this suggestion but it did not solve my problem.

**Comment by alto-php** [comment]
@Nyholm I was able to reproduce it with the repo in the post.
Adding `grpc.enable_fork_support=1` to php.ini and rebuild the image fpm image, the issue no longer exists any more.


```
{
    "pool": "www",
    "process-manager": "dynamic",
    "start-time": 1718379834,
    "start-since": 121,
    "accepted-conn": 273,
    "listen-queue": 0,
    "max-listen-queue": 0,
    "listen-queue-len": 511,
    "idle-processes": 0,
    "active-processes": 1,
    "total-processes": 1,
    "max-active-processes": 1,
    "max-children-reached": 1,
    "slow-requests": 0,
    ...
```

**Comment by Nyholm** [comment]
I understand. 
I tried the same trick in my production environment and it didn't work for me. I'll see if I can find some time to give you a new image.

**Comment by Nyholm** [comment]
I was wrong. 

I did another test. I created this [repo](https://github.com/Nyholm/grpc-preload-test). I also tested for two weeks on my application in prod. 

I was very wrong. The workaround is working. =)

```ini
[grpc]
grpc.enable_fork_support = 1
grpc.poll_strategy = epoll1
```
