### ISSUE TITLE
gRPC extension prevents PHP execution

### ISSUE THREAD

**Issue by donis** [grpc/grpc#31772]
### What version of gRPC and what language are you using?
grpc 1.51.1
PHP 7.4.33

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Whatever `php:7.4-fpm-buster` docker image is running.

### What did you do?
Compiled a new gRPC php extension version and when running anything with PHP - we get this error:

### What did you expect to see?
normally running PHP process

### What did you see instead?
any PHP process hangs with this error message:
`E1130 11:14:11.870998498      29 thread_pool.cc:253]                   Waiting for thread pool to idle before forking`

**Comment by rickyyx** [comment]
We running into this error logging as well. When we have multiple threads trying to do some computation. 

Piggybacking here as it seems to be the same issue - or happy to open another if needed. 

**What version of gRPC and what language are you using?**
grpc 1.51.1

**What operating system (Linux, Windows,...) and version?**
macOS Catalina

**What runtime / compiler are you using (e.g. python version or version of gcc)**
python 3.7

**What did you do?**
We have a workload where I believe multiple threads perform some computation (serialization) - we use grpc for cross process communication. I wasn't sure exactly what the callstack is when this logging happens though. 

**What did you expect to see?**
Normal run 

**What did you see instead?**
workload hanging with: 
```
E1207 01:40:20.292858000 4513988032 thread_pool.cc:253]                Waiting for thread pool to idle before forking
```

**Anything else we should know about your project / environment?**

Our job is here if this is helpful in anyway: https://buildkite.com/ray-project/oss-ci-build-branch/builds/1435#0184e9ed-2010-4a26-a83d-6b3918b006d8

**Comment by scv119** [comment]
hi Grpc team, does this warrant yanking the release? It will cause downstream project hanging on Mac, as manifested in our CI.

**Comment by stanley-cheung** [comment]
May I ask how can I reproduce this? Reason I am asking is we have tests running on the `php:7.4-buster` docker image and I was able to run some basic RPCs examples just fine. Is there something specific to `fpm`? 

Also, did this work in any previous release? Was it only 1.51.1 + fpm that breaks?

**Comment by wouter-toppy** [comment]
I have the same error since december 7.

PHP 8.1.13
RPC 1.51.1

downgrated to 1.49.0 solves that issue, but getting random `Segmentation Fault` errors on CLI commands. which we didnt have before. 

Note: had some `Segmentation Fault` error before in the past few years, never found a clear problem, but i always had to do something with the gRPC

**Comment by donis** [comment]
This happens both with php-fpm and with CLI. Hard to say if it's `fork()` as it might be one of the dependencies that we're bumping into. Perhaps it conflicts with some other dependency?

We're running these:
```
[PHP Modules]
apcu
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
ftp
gmp
grpc
hash
iconv
igbinary
intl
json
libxml
mbstring
mcrypt
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by stanley-cheung** [comment]
@donis So what's the symptom? You run a PHP script either from CLI or from FPM. When does the hang happen? Does it enter your script at all? Or it hangs after your script finished? 

When it hangs, does it hang forever? 

As of now we still need a reproducible test case to debug this further.

**Comment by stanley-cheung** [comment]
One thing to try, you might need to add these 2 lines to your `php.ini`

```
grpc.enable_fork_support = 1
grpc.poll_strategy = epoll1
```

https://github.com/grpc/grpc/tree/master/src/php#pcntl_fork-support

I am suspecting something else in your environment is calling `fork()` somehow and we need those 2 lines to enable fork support in the `grpc` extension

**Comment by kenji21** [comment]
we got a process (php-cli) stuck for 3 days with 1.51.1, and no issue with 1.45.0

```
# php -i | grep grpc
/etc/php/7.4/cli/conf.d/30-grpc.ini
grpc
grpc support => enabled
grpc module version => 1.51.1
grpc.enable_fork_support => 0 => 0
grpc.grpc_trace => no value => no value
grpc.grpc_verbosity => no value => no value
grpc.log_filename => no value => no value
grpc.poll_strategy => no value => no value
```

after downgrade:
```
# php -i|grep grpc
/etc/php/7.4/cli/conf.d/30-grpc.ini
grpc
grpc support => enabled
grpc module version => 1.45.0
grpc.enable_fork_support => 0 => 0
grpc.grpc_trace => no value => no value
grpc.grpc_verbosity => no value => no value
grpc.log_filename => no value => no value
grpc.poll_strategy => no value => no value
```

so the issue might not depend on these parameters

**Comment by dwsupplee** [comment]
We have been seeing this on google-cloud-php as well. To reproduce drop the version requirement for the extension:
https://github.com/googleapis/google-cloud-php/blob/main/.github/workflows/tests.yaml#L30

**Comment by scv119** [comment]
I also checked the PR introduced the behavior change; one behavior difference is after the change, we will [continue execute]((https://github.com/grpc/grpc/commit/6b95573959f4efd62c60a144b29b430e093d2813#diff-6ec322bdfb691919a41e2af96163b70dbb17c7c51b3d891499d4f27be9911dbfR78) the callbacks after calling ThreadPool.PreFork, where as previously we will discard the remaining callbacks.  I suspect this could be the cause of this hanging issue.

**Comment by scv119** [comment]
We captured a deadlock https://gist.github.com/scv119/578eaf822c8cffcbbd0045a5eab02e50

It shows two thread deadlocked:

ThreadPool thread stacktrace: it's waiting for all worker thread finishes going to 0 before finish forking.
```
 ...
    +2866 _PyMethodDef_RawFastCallKeywords  (in python) + 353  [0x10167d001]
    + 2866 subprocess_fork_exec  (in _posixsubprocess.cpython-37m-darwin.so) + 684  [0x101aa108c]
    +  2866 fork  (in libsystem_c.dylib) + 12  [0x7fff2067fb4f]
    +   2866 libSystem_atfork_prepare  (in libSystem.B.dylib) + 11  [0x7fff2a976904]
    +     2866 _pthread_atfork_prepare_handlers  (in libsystem_pthread.dylib) + 90  [0x7fff2079a150]
    +      2866 grpc_event_engine::experimental::PrepareFork()  (in cygrpc.cpython-37m-darwin.so) + 147  [0x10a75edf3]
    +       2866 grpc_event_engine::experimental::ThreadPool::ThreadCount::BlockUntilThreadCount(int, char const*)  (in cygrpc.cpython-37m-darwin.so) + 151  [0x10a771337]
    +        2866 gpr_cv_wait  (in cygrpc.cpython-37m-darwin.so) + 137  [0x10a7769a9]
    +          2866 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1298  [0x7fff2079ae49]
    +             2866 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff20767cce]
```

Worker thread stacktrace: it's waiting for fork to finish before bumping the counter in the ExcCtx.
```
    2866 Thread_93633372
      2866 thread_start  (in libsystem_pthread.dylib) + 15  [0x7fff20796443]
        2866 _pthread_start  (in libsystem_pthread.dylib) + 224  [0x7fff2079a8fc]
          2866 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::'lambda'(void*)::__invoke(void*)  (in cygrpc.cpython-37m-darwin.so) + 140  [0x10a77bb2c]
            2866 grpc_event_engine::experimental::ThreadPool::StartThread(std::__1::shared_ptr<grpc_event_engine::experimental::ThreadPool::State>, grpc_event_engine::experimental::ThreadPool::StartThreadReason)::$_0::__invoke(void*)  (in cygrpc.cpython-37m-darwin.so) + 264  [0x10a771e08]
              2866 grpc_event_engine::experimental::ThreadPool::Queue::Step()  (in cygrpc.cpython-37m-darwin.so) + 278  [0x10a770f96]
                2866 grpc_event_engine::experimental::PosixEventEngine::ClosureData::Run()  (in cygrpc.cpython-37m-darwin.so) + 81  [0x10a769311]
                  2866 void absl::lts_20220623::internal_any_invocable::LocalInvoker<false, void, grpc_core::Subchannel::OnConnectingFinishedLocked(absl::lts_20220623::Status)::$_1&>(absl::lts_20220623::internal_any_invocable::TypeErasedState*)  (in cygrpc.cpython-37m-darwin.so) + 482  [0x10a67ea32]
                    2866 grpc_core::Fork::DoIncExecCtxCount()  (in cygrpc.cpython-37m-darwin.so) + 116  [0x10a777ad4]
                      2866 gpr_cv_wait  (in cygrpc.cpython-37m-darwin.so) + 155  [0x10a7769bb]
                        2866 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1298  [0x7fff2079ae49]
                          2866 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff20767cce]
```

**Comment by bshaffer** [comment]
For anyone blocked by this bug, you can rollback to `grpc-1.49.0` to get around the issue until there is a fix

**Comment by stanley-cheung** [comment]
@ctiller I mentioned this bug to you before. Can you take a look at the [stacktrace](https://github.com/grpc/grpc/issues/31772#issuecomment-1350338433) and maybe triage this please?

**Comment by stanley-cheung** [comment]
This is being tracked in #31885 and is actively being worked on.

**Comment by taisph** [comment]
We're getting this with PHP 8.0.27 (CLI) (using OpenTelemetry gRPC trace exporter). gRPC 1.50.0 seems to be ok.

**Comment by gnossen** [comment]
I believe https://github.com/grpc/grpc/pull/32196 will resolve this. Is anyone able to build this PR from source and confirm on the PHP side?

**Comment by danw-mpl** [comment]
This also breaks `opentelemetry-instrument` with Gunicorn, causing the same `Waiting for thread pool to idle before forking` error.

I downgraded 1.52.0 to 1.51.1 to fix the issue.

**Comment by DavidSchnepper** [comment]
> One thing to try, you might need to add these 2 lines to your `php.ini`
> 
> ```
> grpc.enable_fork_support = 1
> grpc.poll_strategy = epoll1
> ```
> 
> https://github.com/grpc/grpc/tree/master/src/php#pcntl_fork-support
> 
> I am suspecting something else in your environment is calling `fork()` somehow and we need those 2 lines to enable fork support in the `grpc` extension

Did anyone try this workaround, and what were the results?

**Comment by taka-oyama** [comment]
I have tested the work around and it seems to be working with only the first line.

**Comment by halnique** [comment]
>```
>grpc.enable_fork_support = 1
>grpc.poll_strategy = epoll1
>```

I have tried this workaround, but the results did not change.

grpc: 1.51.1
php: 8.1.13

**Comment by DavidSchnepper** [comment]
I also tried the two INI option workarounds, separately & together, and the problem still occurred.
grpc 1.51.1
php 8.0.27

**Comment by oprudkyi** [comment]
@nocive it haven't been fixed yet in python as well 
https://github.com/grpc/grpc/issues/31885

**Comment by bshaffer** [comment]
Can we get an update on this? We are still pinned to `grpc-1.49.0` in our tests, which causes each test to run 20+ minutes slower because it has to install it every time.

**Comment by nocive** [comment]
:yawning_face:

**Comment by nocive** [comment]
bump

**Comment by bshaffer** [comment]
I can confirm these issues have been fixed in `1.54.0`, and pinning to this version plus [implementing workflow caching](https://github.com/googleapis/google-cloud-php/pull/5944/files#diff-95557d53bf91069e59d82b9d8fcfaf52ec84a762858983edd5ef3c9b3e4c8191R28-R40) has fixed the issue for us.

**Comment by MrMage** [comment]
@bshaffer did you also check whether the issues have stayed fixed in later versions such as `1.56.0`? 😅

**Comment by bshaffer** [comment]
I haven't tested in later versions, no, but I would think that the. chance of a regression in a minor version is slim.

**Comment by valenciaed** [comment]
I'm still having this issue. Any updates?

❯ php -i | grep grpc                                  
Additional .ini files parsed => /opt/homebrew/etc/php/8.2/conf.d/20-grpc.ini,
grpc
grpc support => enabled
grpc module version => 1.56.0
grpc.enable_fork_support => 0 => 0
grpc.grpc_trace => no value => no value
grpc.grpc_verbosity => no value => no value
grpc.log_filename => no value => no value
grpc.poll_strategy => no value => no value

**Comment by bshaffer** [comment]
@valenciaed thanks for reporting this. Have you tried using `1.54.0`?

**Comment by TomasSjosten** [comment]
How do you downgrade to 1.54?
Last line "grpc@1.54" but module version still show 1.56

grpc
grpc support => enabled
grpc module version => 1.56.0
grpc.enable_fork_support => 0 => 0
grpc.grpc_trace => no value => no value
grpc.grpc_verbosity => no value => no value
grpc.log_filename => no value => no value
grpc.poll_strategy => no value => no value
PATH => /opt/homebrew/opt/grpc@1.54/bin:/opt/homebrew/opt/php@8.0

**Comment by nocive** [comment]
bump

**Comment by taisph** [comment]
FWIW. We use gRPC extensively and have not had any hangs with 1.56.0.

```console
$ php -v
PHP 8.1.21 (cli) (built: Jul 10 2023 23:04:11) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.21, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.21, Copyright (c), by Zend Technologies
$ php -i | grep grpc
/usr/local/etc/php/conf.d/docker-php-ext-grpc.ini,
grpc
grpc support => enabled
grpc module version => 1.56.0
grpc.enable_fork_support => 0 => 0
grpc.grpc_trace => no value => no value
grpc.grpc_verbosity => no value => no value
grpc.log_filename => no value => no value
grpc.poll_strategy => no value => no value
$ php artisan inspire   
Very little is needed to make a happy life. - Marcus Aurelius
$ 
```

**Comment by kenji21** [comment]
is it possible to be related to the python issue and deadlock explained [here](https://github.com/grpc/grpc/issues/34672#issuecomment-1765355144) ?

**Comment by gtcooke94** [comment]
I don't think this root cause would be because of the same refactor PR behind #34672  - that change is significantly newer than this issue

**Comment by nocive** [comment]
To whom it may concern: we haven't seen this resurface since we upgraded to 1.58, it's been ~2 months.

**Comment by superbiche** [comment]
There are still issues with this, PHP 8.3.1, `extension grpc version 1.59.1`, specifically with Tinker/Psych shells, and `pcntl` extension.  

We use `grpc.poll_strategy=epoll1`

- Using Tinker with `grpc.enable_fork_support=1`, the tinker command never reaches the prompt, it keeps hanging after `Psy Shell v0.11.22 (PHP 8.3.1 — cli) by Justin Hileman`  
- Using Tinker with `grpc.enable_fork_support=1`, the tinker command reaches the prompt, but interacting with gRPC hangs, eg when running a Temporal workflow.

**Comment by taisph** [comment]
> There are still issues with this, PHP 8.3.1, `extension grpc version 1.59.1`, specifically with Tinker/Psych shells, and `pcntl` extension.  

We worked around this long ago by adding a `.psysh.php` config file with the following content.

```php
<?php

return [
    'usePcntl' => false, // Must be false to prevent hanging tinker when Pub/Sub is enabled.
];
```

**Comment by eberkund** [comment]
We are also encountering this issue with Laravel Horizon jobs (PHP CLI). Fork support does not seem to help.

**Comment by imhmdb** [comment]
> We are also encountering this issue with Laravel Horizon jobs (PHP CLI). Fork support does not seem to help.

I've been facing the same issue on gRPC v1.60.0 with any process running with Laravel's php artisan command
I tried `grpc.enable_fork_support=1` and with/without `grpc.poll_strategy=epoll1` but didn't help, I also tried modifying `pcre.jit` in php.init to 0 but also didn't work, I also tried defining the psysh configs mentioned in [taisph](https://github.com/taisph) comment and I can see that the issue started happening a lot less often, but caught the process hanging a couple of times already so it didn't get fixed.

**Comment by nocive** [comment]
:zzz:

**Comment by nocive** [comment]
ping @stanley-cheung

**Comment by MrMage** [comment]
I am currently pinned to gRPC version `1.56.0`; does anyone have experience whether there are any newer versions that work well?

**Comment by oprudkyi** [comment]
@MrMage 1.64.1 seems work well for us

**Comment by oprudkyi** [comment]
though there is other  issue, we ended with 
```
zend.max_allowed_stack_size=-1
```
because otherwise got many random stack overflow errors and probably it related to grpc (or protobuf)

**Comment by taisph** [comment]
Seems like 1.68.0 is causing hangs again. 1.67.0 is fine but spews a lot of log lines like below for some reason.

```
I0000 00:00:1733415524.123360      35 call_credentials.c:168] GRPC_PHP: call credentials plugin function - begin
I0000 00:00:1733415524.123644      35 call_credentials.c:171] GRPC_PHP: call credentials plugin function - end
I0000 00:00:1733415524.480082      35 call_credentials.c:168] GRPC_PHP: call credentials plugin function - begin
I0000 00:00:1733415524.480199      35 call_credentials.c:171] GRPC_PHP: call credentials plugin function - end
I0000 00:00:1733415524.815889      35 call_credentials.c:168] GRPC_PHP: call credentials plugin function - begin
I0000 00:00:1733415524.816027      35 call_credentials.c:171] GRPC_PHP: call credentials plugin function - end
```

**Comment by taisph** [comment]
> Seems like 1.68.0 is causing hangs again (PHP 8.2.26). 1.67.0 ~is fine~ (is not fine - just takes a bit longer to hang) but spews a lot of log lines like below for some reason.

I've now tested all latest releases. 1.65.5 is the last known working version. 1.66.0, 1.67.0 and 1.68.0 all hang after a variable period, usually triggered by publishing a message via Pub/Sub.

**Comment by HeenaBansal20** [comment]
I am seeing SIGSEV with version 1.68.0 and 1.69.0 with  my google pubsub testcases reported here 
https://github.com/grpc/grpc/issues/38216

**Comment by taisph** [comment]
> I've now tested all latest releases. 1.65.5 is the last known working version. 1.66.0, 1.67.0 and 1.68.0 all hang after a variable period, usually triggered by publishing a message via Pub/Sub.

1.71.0 also hangs. Still can't move beyond 1.65.5.

**Comment by BSN4** [comment]
For anyone still dealing with this — [grpc-php-rs](https://github.com/BSN4/grpc-php-rs) is a drop-in replacement for ext-grpc that doesn't block PHP execution. It uses a pure Rust stack (tonic + tokio) instead of the C gRPC core.

```sh
pie install bsn4/grpc
```

Or in Docker:
```dockerfile
COPY --from=ghcr.io/bsn4/grpc-php-rs:latest-php8.5 /usr/local/ /usr/local/
```

**Comment by tisogawa** [comment]
> For anyone still dealing with this — [grpc-php-rs](https://github.com/BSN4/grpc-php-rs) is a drop-in replacement for ext-grpc that doesn't block PHP execution. It uses a pure Rust stack (tonic + tokio) instead of the C gRPC core.

@BSN4 Thank you so much for creating and sharing `grpc-php-rs`.
It worked successfully for our use case, and thanks to it, we were finally able to resolve this long-standing issue and move forward.
I really appreciate your work on this project and for introducing it here. It helped us a lot.

**Comment by BSN4** [comment]
> > For anyone still dealing with this — [grpc-php-rs](https://github.com/BSN4/grpc-php-rs) is a drop-in replacement for ext-grpc that doesn't block PHP execution. It uses a pure Rust stack (tonic + tokio) instead of the C gRPC core.
> 
> @BSN4 Thank you so much for creating and sharing `grpc-php-rs`.
> It worked successfully for our use case, and thanks to it, we were finally able to resolve this long-standing issue and move forward.
> I really appreciate your work on this project and for introducing it here. It helped us a lot.

Thanks for your kind words
