### ISSUE TITLE
tests.bins/asan/end2end_test fails

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#3578]
https://grpc-testing.appspot.com/job/gRPC_master/7727/config=asan,language=c++,platform=linux/console

**Comment by dgquintas** [comment]
Still failing, https://grpc-testing.appspot.com/job/gRPC_master/7773/config=asan,language=c++,platform=linux/console

```
[ RUN      ] End2end/End2endTest.ChannelState/1
I1001 17:46:03.272230661   13363 end2end_test.cc:357]        Scenario: proxy 0, tls 0
E1001 17:46:03.272838036   13363 tcp_client_posix.c:169]     socket error: connection refused
D1001 17:46:03.327013116   13839 server.c:398]               finish_destroy_channel: 0x616000059480
E1001 17:46:03.328443971   13363 sync_posix.c:48]            assertion failed: pthread_mutex_lock(mu) == 0



*******************************
Caught signal 6
bins/asan/end2end_test(backtrace+0x95)[0x5855c5]
bins/asan/end2end_test[0xead003]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7ff09ec788d0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7ff09dfaf107]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7ff09dfb04e8]
bins/asan/end2end_test(gpr_mu_lock+0x149)[0xeccd39]
bins/asan/end2end_test(grpc_completion_queue_shutdown+0x159)[0x9eef19]
bins/asan/end2end_test(grpc_completion_queue_destroy+0x109)[0x9ef429]
bins/asan/end2end_test(_ZN4grpc15CompletionQueueD1Ev+0x1b1)[0x8c9731]
bins/asan/end2end_test(_ZN4grpc6ServerD1Ev+0x74a)[0x8fdd0a]
bins/asan/end2end_test(_ZN4grpc6ServerD0Ev+0x111)[0x8fe0e1]
bins/asan/end2end_test(_ZNKSt14default_deleteIN4grpc6ServerEEclEPS1_+0x1ec)[0x6ffafc]
bins/asan/end2end_test(_ZNSt10unique_ptrIN4grpc6ServerESt14default_deleteIS1_EED2Ev+0x203)[0x6f15f3]
bins/asan/end2end_test[0x61abec]
bins/asan/end2end_test[0x6a9afc]
bins/asan/end2end_test[0x6a9c61]
bins/asan/end2end_test(_ZN7testing4Test11DeleteSelf_Ev+0x17c)[0x128775c]
bins/asan/end2end_test(_ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x389)[0x1306d39]
bins/asan/end2end_test(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x65c)[0x128437c]
bins/asan/end2end_test(_ZN7testing8TestInfo3RunEv+0x9f3)[0x1207353]
bins/asan/end2end_test(_ZN7testing8TestCase3RunEv+0x7ea)[0x120a56a]
bins/asan/end2end_test(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x14bf)[0x1230a8f]
bins/asan/end2end_test(_ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x389)[0x12e6f79]
bins/asan/end2end_test(_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x672)[0x1296042]
bins/asan/end2end_test(_ZN7testing8UnitTest3RunEv+0x543)[0x122f353]
bins/asan/end2end_test(_Z13RUN_ALL_TESTSv+0x11)[0x6d4341]
bins/asan/end2end_test(main+0x267)[0x5ecd87]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7ff09df9bb45]
bins/asan/end2end_test[0x5e292d]

FAILED: bins/asan/end2end_test [ret=-6, pid=13363]
```

**Comment by jtattermusch** [comment]
Seen again.

https://grpc-testing.appspot.com/job/gRPC_master/7887/config=asan,language=c++,platform=linux/console

```
=================================================================
==14096==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8216 byte(s) in 1 object(s) allocated from:
    #0 0x5c531b in __interceptor_malloc (/var/local/git/grpc/bins/asan/end2end_test+0x5c531b)
    #1 0xeb4621 in gpr_malloc /var/local/git/grpc/src/core/support/alloc.c:40:13
    #2 0xebbf06 in gpr_slice_malloc /var/local/git/grpc/src/core/support/slice.c:178:27
    #3 0xbc3558 in tcp_continue_read /var/local/git/grpc/src/core/iomgr/tcp_posix.c:187:34
    #4 0xbbf471 in tcp_handle_read /var/local/git/grpc/src/core/iomgr/tcp_posix.c:256:5
    #5 0xa1f061 in grpc_exec_ctx_flush /var/local/git/grpc/src/core/iomgr/exec_ctx.c:46:7
    #6 0xad2269 in grpc_pollset_work /var/local/git/grpc/src/core/iomgr/pollset_posix.c:236:5
    #7 0x9edcef in grpc_completion_queue_next /var/local/git/grpc/src/core/surface/completion_queue.c:228:5
    #8 0x8ca38a in grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) /var/local/git/grpc/src/cpp/common/completion_queue.cc:56:15
    #9 0x7775fd in grpc::CompletionQueue::Next(void**, bool*) /var/local/git/grpc/include/grpc++/completion_queue.h:127:13
    #10 0x90ea2e in grpc::Server::SyncRequest::Wait(grpc::CompletionQueue*, bool*) /var/local/git/grpc/src/cpp/server/server.cc:132:10
    #11 0x906f69 in grpc::Server::RunRpc() /var/local/git/grpc/src/cpp/server/server.cc:544:15
    #12 0x911ed9 in void std::_Mem_fn<void (grpc::Server::*)()>::operator()<, void>(grpc::Server*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11
    #13 0x911c0e in void std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1263:11
    #14 0x9119ba in void std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)>::operator()<, void>() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1321:11
    #15 0x910950 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (grpc::Server::*)()> (grpc::Server*)> >::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2039:4
    #16 0x8d9407 in std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2439:14
    #17 0x8d4535 in grpc::DynamicThreadPool::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:81:7
    #18 0x8d37fd in grpc::DynamicThreadPool::DynamicThread::ThreadFunc() /var/local/git/grpc/src/cpp/server/dynamic_thread_pool.cc:50:3
    #19 0x8f7949 in void std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()>::operator()<, void>(grpc::DynamicThreadPool::DynamicThread*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11
    #20 0x8f750e in void std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18
    #21 0x8f7342 in std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16
    #22 0x8f71d2 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::DynamicThreadPool::DynamicThread::*)()> (grpc::DynamicThreadPool::DynamicThread*)> >::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13
    #23 0x7f0eb2d6d96f (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb696f)

Objects leaked above:
0x625000352100 (8216 bytes)

SUMMARY: AddressSanitizer: 8216 byte(s) leaked in 1 allocation(s).

FAILED: bins/asan/end2end_test [ret=23, pid=14096]
```

**Comment by yang-g** [comment]
I am looking at this now.

**Comment by soltanmm** [comment]
Feels weird pinging a thread that's being looked at, but per build-pony procedure here's another ping:
https://grpc-testing.appspot.com/job/gRPC_master/config=asan,language=c++,platform=linux/7913/testReport/(root)/tests/bins_asan_end2end_test/

**Comment by yang-g** [comment]
#3595 and #3627 fixed the first and second issues. The leak should be fixed by #3679. There are other flakes which I filed separately in #3680 and #3681. I think this can be closed.

**Comment by apolcyn** [comment]
failure still happening on v1.1.x.

saw in https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2614/testReport/junit/(root)/c++_linux_opt/bins_opt_end2end_test___gtest_filter_End2end_End2endTest_ChannelState_1__GRPC_POLL_STRATEGY_poll/

pr #9654 against v1.1.x
