### ISSUE TITLE
Support for PHP 8.5

### ISSUE THREAD

**Issue by remicollet** [grpc/grpc#40242]
Build is broken with 8.5.0alpha2

```
/builddir/build/BUILD/php85-php-pecl-grpc-1.73.0-build/php85-php-pecl-grpc-1.73.0/grpc-1.73.0/src/php/ext/grpc/call.c: In function 'grpc_parse_metadata_array':
/builddir/build/BUILD/php85-php-pecl-grpc-1.73.0-build/php85-php-pecl-grpc-1.73.0/grpc-1.73.0/src/php/ext/grpc/call.c:87:30: error: implicit declaration of function 'zend_exception_get_default'; did you mean 'zend_exception_set_previous'? [-Wimplicit-function-declaration]
   87 |         zend_throw_exception(zend_exception_get_default(TSRMLS_C),
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              zend_exception_set_previous
/builddir/build/BUILD/php85-php-pecl-grpc-1.73.0-build/php85-php-pecl-grpc-1.73.0/grpc-1.73.0/src/php/ext/grpc/call.c:87:30: error: passing argument 1 of 'zend_throw_exception' makes pointer from integer without a cast [-Wint-conversion]
   87 |         zend_throw_exception(zend_exception_get_default(TSRMLS_C),
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              |
      |                              int
In file included from /builddir/build/BUILD/php85-php-pecl-grpc-1.73.0-build/php85-php-pecl-grpc-1.73.0/grpc-1.73.0/src/php/ext/grpc/call.c:27:
/opt/remi/php85/root/usr/include/php/Zend/zend_exceptions.h:57:72: note: expected 'zend_class_entry *' {aka 'struct _zend_class_entry *'} but argument is of type 'int'
   57 | ZEND_API ZEND_COLD zend_object *zend_throw_exception(zend_class_entry *exception_ce, const char *message, zend_long code);
      |                                                      ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

```

Patch is trivial, from UPGRADING.INTERNALS
```
  . zend_exception_get_default() was removed, use zend_ce_exception directly.
```

Notice: zend_ce_exception is available since PHP 7.0

**Comment by remicollet** [comment]
```
diff -up ./src/php/ext/grpc/call.c.php85 ./src/php/ext/grpc/call.c
--- ./src/php/ext/grpc/call.c.php85	2025-07-17 10:28:12.598376396 +0200
+++ ./src/php/ext/grpc/call.c	2025-07-17 10:28:45.097057429 +0200
@@ -84,7 +84,7 @@ zval *grpc_parse_metadata_array(grpc_met
     if (php_grpc_zend_hash_find(array_hash, str_key, key_len, (void **)&data)
         == SUCCESS) {
       if (Z_TYPE_P(data) != IS_ARRAY) {
-        zend_throw_exception(zend_exception_get_default(TSRMLS_C),
+        zend_throw_exception(zend_ce_exception,
                              "Metadata hash somehow contains wrong types.",
                              1 TSRMLS_CC);
         efree(str_key);
```

**Comment by verfriemelt-dot-org** [comment]
heyho, is there a approximate timeline for this? i'd love to upgrade but rely on this extension for php8.5 :)

**Comment by pawbhard** [comment]
Hi @verfriemelt-dot-org, approximate time line would be January end at this time, would try to see if we can complete it before.

**Comment by pyatnitsev** [comment]
Hi @pawbhard!
Could you have a look at [this](https://github.com/grpc/grpc/pull/40337) PR please? It seems, that could be resolve this issue.

**Comment by pawbhard** [comment]
Thanks for pointing @pyatnitsev . Sure, will take a look. Might need to add test in CI as well.

**Comment by nocive** [comment]
bump

**Comment by pawbhard** [comment]
Merged the PR solving the php 8.5 issue. https://github.com/grpc/grpc/pull/40337

**Comment by schodemeiss** [comment]
Will this make its way into RC2 for 1.78?

**Comment by nocive** [comment]
@schodemeiss ~~Looks like it didn't make it, I've tried it and the problem persists.~~ RC2 is working :)

**Comment by pawbhard** [comment]
@nocive , Did you check with RC2 I pushed today. I remember back-porting to 1.78 so it is part of RC2 release.
Let me also check.

Update verified code changes of PR is part of tar file released.

**Comment by nocive** [comment]
@pawbhard yes, I did try RC2 via pecl and the problem persisted:
```
1396.7 In file included from /tmp/pear/temp/grpc/src/php/ext/grpc/call.c:27:
1396.7 /usr/local/include/php/Zend/zend_exceptions.h:57:72: note: expected 'zend_class_entry *' {aka 'struct _zend_class_entry *'} but argument is of type 'int'
1396.7    57 | ZEND_API ZEND_COLD zend_object *zend_throw_exception(zend_class_entry *exception_ce, const char *message, zend_long code);
1396.7       |                                                      ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
1396.7 make: *** [Makefile:2965: src/php/ext/grpc/call.lo] Error 1
1396.7 make: *** Waiting for unfinished jobs....
1396.7 ERROR: `make -j2' failed
```

EDIT: looks like I did a mistake while doing so, trying again...

**Comment by nocive** [comment]
@pawbhard thanks for double checking, you're absolutely right! RC2 is indeed patched and working ⭐

**Comment by schodemeiss** [comment]
> [@nocive](https://github.com/nocive) , Did you check with RC2 I pushed today. I remember back-porting to 1.78 so it is part of RC2 release. Let me also check.
> 
> Update verified code changes of PR is part of tar file released.

Yea, works for me on RC2. Great stuff. Thank-you!
