### ISSUE TITLE
ASAN detected ODR violation

### ISSUE THREAD

**Issue by newsoft** [grpc/grpc#4331]
I compiled the whole stack (from protobuf to gRPC) with `clang` and `-fsanitize=address`.

`examples/cpp/helloworld/greeter_server` will refuse to run because of an ODR violation:
```
  [1] size=88 'grpc_client_census_filter' src/core/census/grpc_filter.c:172:27
  [2] size=88 'grpc_client_census_filter' src/core/census/grpc_filter.c:172:27
```
`const grpc_channel_filter grpc_client_census_filter` is initialized by both `libgrpc.so` and `libgrpc_unsecure.so` - and `greeter_server` apparently links both.

This is not an issue per se, as both initializations are probably identical, but this prevents further testing with `odr-violation` enabled in ASAN (which would possibly yield more interesting results).

**Comment by ctiller** [comment]
Was this at head? I've fixed a slew of similar problems recently. Not
shocked there's one more.

**Comment by newsoft** [comment]
Apparently it still reproduces at head:
```
$ git log | head
commit 6a18f0ce93bfc407a84b79e2769e14ac7aa24648
Merge: 045c848 82e40da
Author: jboeuf <jboeuf@users.noreply.github.com>
Date:   Mon Dec 7 22:47:01 2015 -0800
    Merge pull request #4326 from ctiller/creds-test-fix
    Fix memory leak
...
```

Just apply the following changes to `helloworld` `Makefile`:
```
CXX = clang++
LDFLAGS += -fsanitize-address
```
