### ISSUE TITLE
'openssl/rsa.h' file not found (BoringSSL)

### ISSUE THREAD

**Issue by Gurpartap** [grpc/grpc#4351]
<img width="1072" alt="screen shot 2015-12-09 at 9 44 20 am" src="https://cloud.githubusercontent.com/assets/39792/11676564/76e7d6d2-9e59-11e5-890e-8d9b6412a8fd.png">

Reference project:
https://github.com/Gurpartap/echo-grpc-swift

**Comment by jcanizales** [comment]
Yeah this is definitely https://github.com/CocoaPods/CocoaPods/issues/4605; it's the same error I got.

**Comment by yarnping** [comment]
Is there a solution?

**Comment by BenchR267** [comment]
Did you found any solution @yarnping?

**Comment by jcanizales** [comment]
If any of you guys know Ruby, we can work together on fixing the Cocoapods issue. We know what the required behavior is, but I can really use a hand there.

**Comment by BenchR267** [comment]
I would love to help but I've never done that much in ruby that I think I could help :/

**Comment by jcanizales** [comment]
I'm going to give [this](http://howistart.org/posts/ruby/1) a quick read and try to see if I can at least set up a Cocoapods built from code on my machine.

**Comment by jcanizales** [comment]
Ok, this is the plan @timburks and I are pursuing. Unlike a hundred other things we've tried so far, this one looks promising.

For each of BoringSSL, the C core, and maybe others:
1. Write and check in a script that creates a dynamic framework for it.
2. Have the podspec point to that framework instead of the source files.
3. For development, have a `prepare_command` in the podspec call the script that creates the framework.
4. For release, create a gzip file out of the framework and have the podspec point at it in `source`.

(In order to have a single podspec for both local development and release, the `prepare_command` can be made conditional on reading an environmental variable via `ENV['varname']`).

So far we've been able to successfully create the framework for BoringSSL, in a way that's amenable to scripting.

**Comment by makdharma** [comment]
Quick update: we're able to build the gRPC as a framework, and link with it. However while running, we run into "Image not found" (http://stackoverflow.com/questions/20092886/image-not-found-error-while-using-custom-framework)

**Comment by kouky** [comment]
Also encountering this issue when building grpc as a standalone framework.

**Comment by kouky** [comment]
Solved the issue temporarily by creating symlinks for the missing headers. Huge thanks to @matti777 who posed the solution on [cocoapods issue 4605](https://github.com/CocoaPods/CocoaPods/issues/4605#issuecomment-191182412).

**Comment by jcanizales** [comment]
We're aiming to having a solution today that works for everybody, without manual intervention after `pod install`.

**Comment by makdharma** [comment]
@jcanizales can you update this issue with p rogress?

**Comment by makdharma** [comment]
@jcanizales ping?

**Comment by jcanizales** [comment]
#6849 :)

**Comment by hsaliak** [comment]
@jcanizales is the pull request ready to merge? What's pending for resolution of this issue?

**Comment by jcanizales** [comment]
It's pending review by @makdharma and @TimBurks.

**Comment by jcanizales** [comment]
This is now fixed in the 0.14 branch by #6849. After pushing 0.14 to Cocoapods, I'll merge 0.14 back into the master branch (late today or early tomorrow).

**Comment by bch007** [comment]
this is awesome work! big thanks ! :)

**Comment by maxisme** [comment]
I am still getting this issue. I am currently file sharing from my MBP to my desktop if I copy and paste the files locally and then run there is no error. I have no idea what is going on as both times I am running xcode locally?

**Comment by muxi** [comment]
@maxisme Is this still a problem to you? If not, could you please provide more information such as your environment and how do you reproduce it?

**Comment by maxisme** [comment]
I can reproduce by running the xcode files on a remote server and not installing the pods locally. 

Once I ran pod install on the local machine everything was fixed :)

**Comment by muxi** [comment]
Could you elaborate how you "run xcode on a remote server"? Did you run pod install on your server then access them on your desktop, or are you trying to run pod install on your desktop? Some steps for us to repeat and expected result (refer to [issue guideline](https://github.com/grpc/grpc/issues/new)) would be helpful. You may file a new issue if you like.
