### ISSUE TITLE
C core dies after "Address already in use" message.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4446]
Seen this when running one of the C# tests. It looks like 

(tcp_server_posix.c:284)  prepare_socket  returns -1 and from there things start to go wrong until it finally dies in grpc_server_add_insecure_http2_port.

```
***** Grpc.Core.Tests.TimeoutsTest.DeadlineInThePast
Stacktrace:

Native stacktrace:

	/usr/bin/mono() [0x4b73d8]
	/usr/bin/mono() [0x50f13b]
	/usr/bin/mono() [0x423d22]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f4e64666340]
	/usr/local/google/home/jtattermusch/github/grpc/libs/opt/libgrpc.so.0(grpc_tcp_listener_get_port+0) [0x7f4e42b95620]
	/usr/local/google/home/jtattermusch/github/grpc/libs/opt/libgrpc.so.0(grpc_server_add_insecure_http2_port+0xbe) [0x7f4e42ba0bce]
	[0x4013b1a1]
E12/14/2015 8:47:44 AM 139974112372480 src/core/iomgr/tcp_server_posix.c:284: bind addr=[::ffff:127.0.0.1]:58084: Address already in use
Debug info from gdb:
```

**Comment by jtattermusch** [comment]
@ctiller  for triage.

**Comment by ctiller** [comment]
How recently did you see this? I thought I had this fixed in #4433.

**Comment by jtattermusch** [comment]
I just rebased to the freshest master and I am still seeing this.

Looks like there's some extra debug info:
```
E12/14/2015 9:18:08 AM 140310063539968 src/core/iomgr/tcp_server_posix.c:284: bind addr=[::ffff:127.0.0.1]:58775: Address already in use
E12/14/2015 9:18:08 AM 140310063539968 src/core/surface/server_chttp2.c:116: assertion failed: port_num == port_temp
```

```
Native stacktrace:

	/usr/bin/mono() [0x4b73d8]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f9c9cbe6340]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f9c9c847cc9]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f9c9c84b0d8]
	/usr/local/google/home/jtattermusch/github/grpc/libs/dbg/libgrpc.so.0(grpc_server_add_insecure_http2_port+0x199) [0x7f9c7af9786a]
	/usr/local/google/home/jtattermusch/github/grpc/libs/dbg/libgrpc_csharp_ext.so(grpcsharp_server_add_insecure_http2_port+0x23) [0x7f9c7b3ead59]
	[0x40d120a1]
```

**Comment by ctiller** [comment]
How do I repro?

**Comment by jtattermusch** [comment]
I am in the middle of doing some C# testing work, but here's my branch:
https://github.com/jtattermusch/grpc/tree/csharp_test_restructuring

If I run  `tools/run_tests/run_tests.py -c dbg -l csharp -S -n 10` I am pretty much guaranteed to see the problem. Now looking at the core dump.

**Comment by jtattermusch** [comment]
By the time the assertion fails:
```
(gdb) print port_num
$1 = 58775
(gdb) print port_temp
$2 = 0
```

**Comment by jtattermusch** [comment]
(gdb) print listener
$3 = (grpc_tcp_listener *) 0x0

**Comment by ctiller** [comment]
I think the 'port_temp >= 0' condition should be 'port_temp > 0'

**Comment by ctiller** [comment]
(can you check - this will also need fixing in server_secure_chttp2.c)

**Comment by jtattermusch** [comment]
From grpc_server_add_insecure_http2_port:
```
for (i = 0; i < resolved->naddrs; i++) {
    grpc_tcp_listener *listener;
    listener = grpc_tcp_server_add_port(
        tcp, (struct sockaddr *)&resolved->addrs[i].addr,
        resolved->addrs[i].len);
    port_temp = grpc_tcp_listener_get_port(listener);
    if (port_temp >= 0) {
      if (port_num == -1) {
        port_num = port_temp;
      } else {
        GPR_ASSERT(port_num == port_temp);
      }
      count++;
    }
  }
```
What happens:
grpc_tcp_server_add_port returns null,  grpc_tcp_listener_get_port therefore returns 0. Then things go wrong.

**Comment by jtattermusch** [comment]
Yep, I will try and create a PR if needed. Thanks for help.
