### ISSUE TITLE
csharp.Grpc.Core.Tests.TimeoutsTest is flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5424]
```
I02/24/2016 22:40:06 140478366344960 src/core/surface/completion_queue.c:392: grpc_completion_queue_pluck(cc=0x7fc3a01ef890, tag=0x7fc3a022ee00, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
Stacktrace:


Native stacktrace:

    mono() [0x49d56c]
    mono() [0x4f33ee]
    mono() [0x42498d]
    /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0) [0x7fc3c45e18d0]
    /var/local/git/grpc/src/csharp/Grpc.Core.Tests/bin/Release/nativelibs/linux_x64/libgrpc_csharp_ext.so(+0x10d6fa) [0x7fc3aad6b6fa]
    /var/local/git/grpc/src/csharp/Grpc.Core.Tests/bin/Release/nativelibs/linux_x64/libgrpc_csharp_ext.so(grpc_cq_end_op+0x9c) [0x7fc3aac997ac]
    /var/local/git/grpc/src/csharp/Grpc.Core.Tests/bin/Release/nativelibs/linux_x64/libgrpc_csharp_ext.so(+0x381bd) [0x7fc3aac961bd]
    /var/local/git/grpc/src/csharp/Grpc.Core.Tests/bin/Release/nativelibs/linux_x64/libgrpc_csharp_ext.so(grpc_exec_ctx_flush+0x57) [0x7fc3aacfff37]
    /var/local/git/grpc/src/csharp/Grpc.Core.Tests/bin/Release/nativelibs/linux_x64/libgrpc_csharp_ext.so(grpc_completion_queue_pluck+0x285) [0x7fc3aac99e45]
    /var/local/git/grpc/src/csharp/Grpc.Core.Tests/bin/Release/nativelibs/linux_x64/libgrpc_csharp_ext.so(grpcsharp_completion_queue_pluck+0x2a) [0x7fc3aac9428a]
    [0x40cc7eeb]
```

https://grpc-testing.appspot.com/job/gRPC_master/15386/config=opt,language=csharp,platform=linux/testReport/junit/(root)/tests/csharp_Grpc_Core_Tests_TimeoutsTest/

**Comment by jtattermusch** [comment]
Today I wasn't able to reproduce this error (despite running the entire suite 300x). My investigation indicates that it was fixed by #5307.

@ctiller  thanks!

**Comment by adelez** [comment]
Still getting this failure: https://sponge.corp.google.com/target?id=a1d076cd-f8a7-49f1-9bac-32147796f008&target=github/grpc/csharp_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by adelez** [comment]
The failure above looks different. I'm closing this one and filing a new one.
