### ISSUE TITLE
tests.py.test._crust_over_core_over_links_face_interface_test.GenericInvokerBlockingInvocationInlineServiceTest timeout

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5779]
We are still seeing this (but way less often than before https://github.com/grpc/grpc/pull/5763), it would be good to understand the root cause.

https://grpc-testing.appspot.com/job/gRPC_master/15848/config=opt,language=python,platform=macos/testReport/junit/(root)/tests/py_test__crust_over_core_over_links_face_interface_test_GenericInvokerBlockingInvocationInlineServiceTest/

**Comment by soltanmm** [comment]
I think I have the root cause understood (single-thread deadlock on a filled OS-level buffer due to Python's GC behavior). Just need to write a patch.

**Comment by jcanizales** [comment]
I expect it's the same issue as here? https://grpc-testing.appspot.com/job/gRPC_master/15859/config=opt,language=python,platform=linux/testReport/junit/(root)/tests/py_test__crust_over_core_over_links_face_interface_test_MultiCallableInvokerFutureInvocationAsynchronousEventServiceTest/

**Comment by jcanizales** [comment]
And here? https://grpc-testing.appspot.com/job/gRPC_master/15879/config=dbg,language=python,platform=linux/testReport/junit/(root)/tests/py_test__face_interface_test_DynamicInvokerFutureInvocationAsynchronousEventServiceTest/

**Comment by jtattermusch** [comment]
This might have been fixed by #5786, let's see.

**Comment by sreecha** [comment]
Still happening: https://grpc-testing.appspot.com/job/gRPC_master/16133/

**Comment by stanley-cheung** [comment]
Still happening, but very occasionally: https://grpc-testing.appspot.com/job/gRPC_master/16276/config=dbg,language=python,platform=macos/
