### ISSUE TITLE
"Greeter recerived : RPC failed" in cpp example

### ISSUE THREAD

**Issue by yookyoung89** [grpc/grpc#6862]
When i try to run cpp hello world example, a error have been happenning.
"Greeter received: RPC failed"  What can i do to resolve this problem?

$ ./greeter_server
D0610 13:46:17.375313774   31124 env_linux.c:77]             Warning: insecure environment read function 'getenv' used
D0610 13:46:17.375486286   31124 env_linux.c:77]             Warning: insecure environment read function 'getenv' used
D0610 13:46:17.375512302   31124 ev_posix.c:101]             Using polling engine: poll
D0610 13:46:17.375542479   31124 env_linux.c:77]             Warning: insecure environment read function 'getenv' used
Server listening on 0.0.0.0:50051
E0610 13:46:27.531291219   31128 compression.c:157]          Unknown compression level 32759.

$./greeter_client
D0610 13:46:27.529877420   31136 env_linux.c:77]             Warning: insecure environment read function 'getenv' used
D0610 13:46:27.530095493   31136 env_linux.c:77]             Warning: insecure environment read function 'getenv' used
D0610 13:46:27.530131618   31136 ev_posix.c:101]             Using polling engine: poll
D0610 13:46:27.530186037   31136 env_linux.c:77]             Warning: insecure environment read function 'getenv' used
Greeter received: RPC failed

**Comment by fdefever** [comment]
You can enable grpc tracing with
`export GRPC_TRACE=all && ./greeter_server` and same thing for the client.

**Comment by crclark** [comment]
I'm seeing the same "unknown compression level" error with our Haskell gRPC library (which uses the C core), on OS X with 0.15.0, when running a simple unary request/response test. Note this happens regardless of whether I set a compression level explicitly when starting the server. This didn't happen with 0.14.0, and is blocking us from upgrading to 0.15.0. 

Server trace:

```
0728 13:21:11.355667000 140735123824640 ev_posix.c:101] Using polling engine: poll
I0728 13:21:11.357069000 140735123824640 init.c:188] grpc_init(void)
I0728 13:21:11.357762000 140735123824640 server.c:984] grpc_server_create(0x7fb575000310, 0x0)
I0728 13:21:11.358661000 140735123824640 server_chttp2.c:92] grpc_server_add_insecure_http2_port(server=0x7fb573c05a90, addr=localhost:50051)
I0728 13:21:11.359685000 140735123824640 completion_queue.c:129] grpc_completion_queue_create(reserved=0x0)
I0728 13:21:11.359698000 140735123824640 server.c:968] grpc_server_register_completion_queue(server=0x7fb573c05a90, cq=0x7fb575101420, reserved=0x0)
I0728 13:21:11.359704000 140735123824640 server.c:1064] grpc_server_start(server=0x7fb573c05a90)
I0728 13:21:11.359857000 140735123824640 completion_queue.c:129] grpc_completion_queue_create(reserved=0x0)
I0728 13:21:11.360085000 140735123824640 metadata_array.c:42] grpc_metadata_array_init(array=0x7fb573c06210)
I0728 13:21:11.360102000 140735123824640 call_details.c:42] grpc_call_details_init(cd=0x7fb573c05780)
I0728 13:21:11.360113000 140735123824640 server.c:1371] grpc_server_request_call(server=0x7fb573c05a90, call=0x7fb575100dd0, details=0x7fb573c05780, initial_metadata=0x7fb573c06210, cq_bound_to_call=0x7fb5751015b0, cq_for_notification=0x7fb575101420, tag=0x8000000000000000)
I0728 13:21:11.360275000 140735123824640 completion_queue.c:434] grpc_completion_queue_pluck(cc=0x7fb575101420, tag=0x8000000000000000, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 0 }, reserved=0x0)
D0728 13:21:30.539424000 140735123824640 tcp_server_posix.c:367] SERVER_CONNECT: incoming connection: ipv6:[::1]:50868
D0728 13:21:30.539774000 140735123824640 connectivity_state.c:109] CONWATCH: 0x7fb5740b4d48 server_transport: from IDLE [cur=READY] notify=0x7fb573c06aa8
D0728 13:21:30.539799000 140735123824640 connectivity_state.c:109] CONWATCH: 0x7fb5740b4d48 server_transport: from READY [cur=READY] notify=0x7fb573c06aa8
D0728 13:21:30.539821000 140735123824640 parsing.c:168] FLOW parsed: server transport CREDIT       global.announce_incoming_window(0) by                   announce_bytes(983041) giving 983041
D0728 13:21:30.539830000 140735123824640 parsing.c:170] FLOW parsed: server transport CREDIT           parsing.incoming_window(65535) by                   announce_bytes(983041) giving 1048576
D0728 13:21:30.539840000 140735123824640 writing.c:163] FLOW write: server transport DEBIT   global.announce_incoming_window(983041) by                        announced(983041) giving 0
D0728 13:21:30.539877000 140735123824640 frame_settings.c:250] CHTTP2:SVR: got setting 2 = 0
D0728 13:21:30.539883000 140735123824640 frame_settings.c:250] CHTTP2:SVR: got setting 3 = 0
D0728 13:21:30.539886000 140735123824640 frame_settings.c:250] CHTTP2:SVR: got setting 4 = 65535
D0728 13:21:30.539889000 140735123824640 frame_settings.c:250] CHTTP2:SVR: got setting 6 = 16384
D0728 13:21:30.539894000 140735123824640 frame_window_update.c:122] FLOW parse: server transport CREDIT               parsing.outgoing_window(0) by                  received_update(983041) giving 983041
I0728 13:21:30.539908000 140735123824640 call.c:1353] ops[0]: RECV_INITIAL_METADATA ptr=0x7fb5740b76f0
I0728 13:21:30.539915000 140735123824640 server.c:780] OP[server:0x7fb5740b7608]: RECV_INITIAL_METADATA
I0728 13:21:30.539919000 140735123824640 http_server_filter.c:219] OP[http-server:0x7fb5740b7620]: RECV_INITIAL_METADATA
I0728 13:21:30.539923000 140735123824640 connected_channel.c:70] OP[connected:0x7fb5740b7650]: RECV_INITIAL_METADATA
I0728 13:21:30.539931000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: :scheme: http
I0728 13:21:30.539938000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: :method: POST
I0728 13:21:30.539946000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: :path: /echo.Echo/DoEcho
I0728 13:21:30.539953000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: :authority: localhost:50051
I0728 13:21:30.539959000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: grpc-encoding: identity
I0728 13:21:30.539966000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: grpc-accept-encoding: identity,deflate,gzip
I0728 13:21:30.539977000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: te: trailers
I0728 13:21:30.539981000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: content-type: application/grpc
I0728 13:21:30.539987000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: user-agent: grpc-c/0.15.0 (osx; chttp2)
I0728 13:21:30.539995000 140735123824640 parsing.c:655] HTTP:1:HDR:SVR: grpc-timeout: 5S
D0728 13:21:30.540008000 140735123824640 parsing.c:592] FLOW parse: server transport DEBIT          parsing.incoming_window(1048576) by                   incoming_frame_size(9) giving 1048567
D0728 13:21:30.540015000 140735123824640 parsing.c:594] FLOW parse: server stream[1] DEBIT            parsing.incoming_window(65535) by                   incoming_frame_size(9) giving 65526
I0728 13:21:30.540029000 140735123824640 call.c:1353] ops[0]: RECV_INITIAL_METADATA ptr=0x7fb5740b86f0
I0728 13:21:30.540033000 140735123824640 server.c:780] OP[server:0x7fb5740b8608]: RECV_INITIAL_METADATA
I0728 13:21:30.540037000 140735123824640 http_server_filter.c:219] OP[http-server:0x7fb5740b8620]: RECV_INITIAL_METADATA
I0728 13:21:30.540040000 140735123824640 connected_channel.c:70] OP[connected:0x7fb5740b8650]: RECV_INITIAL_METADATA
I0728 13:21:30.540046000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: :scheme: http
I0728 13:21:30.540049000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: :method: POST
I0728 13:21:30.540052000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: :path: /echo.Echo/DoEcho
I0728 13:21:30.540055000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: :authority: localhost:50051
I0728 13:21:30.540058000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: grpc-encoding: identity
I0728 13:21:30.540061000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: grpc-accept-encoding: identity,deflate,gzip
I0728 13:21:30.540064000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: te: trailers
I0728 13:21:30.540067000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: content-type: application/grpc
I0728 13:21:30.540070000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: user-agent: grpc-c/0.15.0 (osx; chttp2)
I0728 13:21:30.540074000 140735123824640 parsing.c:655] HTTP:3:HDR:SVR: grpc-timeout: 5S
D0728 13:21:30.540079000 140735123824640 parsing.c:592] FLOW parse: server transport DEBIT          parsing.incoming_window(1048567) by                   incoming_frame_size(9) giving 1048558
D0728 13:21:30.540084000 140735123824640 parsing.c:594] FLOW parse: server stream[3] DEBIT            parsing.incoming_window(65535) by                   incoming_frame_size(9) giving 65526
I0728 13:21:30.540095000 140735123824640 call.c:1353] ops[0]: RECV_INITIAL_METADATA ptr=0x7fb5740b96f0
I0728 13:21:30.540099000 140735123824640 server.c:780] OP[server:0x7fb5740b9608]: RECV_INITIAL_METADATA
I0728 13:21:30.540102000 140735123824640 http_server_filter.c:219] OP[http-server:0x7fb5740b9620]: RECV_INITIAL_METADATA
I0728 13:21:30.540106000 140735123824640 connected_channel.c:70] OP[connected:0x7fb5740b9650]: RECV_INITIAL_METADATA
I0728 13:21:30.540111000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: :scheme: http
I0728 13:21:30.540114000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: :method: POST
I0728 13:21:30.540117000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: :path: /echo.Echo/DoEcho
I0728 13:21:30.540120000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: :authority: localhost:50051
I0728 13:21:30.540123000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: grpc-encoding: identity
I0728 13:21:30.540126000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: grpc-accept-encoding: identity,deflate,gzip
I0728 13:21:30.540129000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: te: trailers
I0728 13:21:30.540132000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: content-type: application/grpc
I0728 13:21:30.540135000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: user-agent: grpc-c/0.15.0 (osx; chttp2)
I0728 13:21:30.540138000 140735123824640 parsing.c:655] HTTP:5:HDR:SVR: grpc-timeout: 5S
D0728 13:21:30.540143000 140735123824640 parsing.c:592] FLOW parse: server transport DEBIT          parsing.incoming_window(1048558) by                   incoming_frame_size(9) giving 1048549
D0728 13:21:30.540152000 140735123824640 parsing.c:594] FLOW parse: server stream[5] DEBIT            parsing.incoming_window(65535) by                   incoming_frame_size(9) giving 65526
I0728 13:21:30.540164000 140735123824640 call.c:1353] ops[0]: RECV_INITIAL_METADATA ptr=0x7fb5740ba6f0
I0728 13:21:30.540168000 140735123824640 server.c:780] OP[server:0x7fb5740ba608]: RECV_INITIAL_METADATA
I0728 13:21:30.540171000 140735123824640 http_server_filter.c:219] OP[http-server:0x7fb5740ba620]: RECV_INITIAL_METADATA
I0728 13:21:30.540174000 140735123824640 connected_channel.c:70] OP[connected:0x7fb5740ba650]: RECV_INITIAL_METADATA
I0728 13:21:30.540179000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: :scheme: http
I0728 13:21:30.540183000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: :method: POST
I0728 13:21:30.540186000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: :path: /echo.Echo/DoEcho
I0728 13:21:30.540189000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: :authority: localhost:50051
I0728 13:21:30.540192000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: grpc-encoding: identity
I0728 13:21:30.540195000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: grpc-accept-encoding: identity,deflate,gzip
I0728 13:21:30.540198000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: te: trailers
I0728 13:21:30.540201000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: content-type: application/grpc
I0728 13:21:30.540204000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: user-agent: grpc-c/0.15.0 (osx; chttp2)
I0728 13:21:30.540207000 140735123824640 parsing.c:655] HTTP:7:HDR:SVR: grpc-timeout: 5S
D0728 13:21:30.540211000 140735123824640 parsing.c:592] FLOW parse: server transport DEBIT          parsing.incoming_window(1048549) by                   incoming_frame_size(9) giving 1048540
D0728 13:21:30.540216000 140735123824640 parsing.c:594] FLOW parse: server stream[7] DEBIT            parsing.incoming_window(65535) by                   incoming_frame_size(9) giving 65526
D0728 13:21:30.540225000 140735123824640 parsing.c:154] FLOW parsed: server transport MOVE                  global.outgoing_window(0) <-          parsing.outgoing_window(983041) giving 983041
D0728 13:21:30.540241000 140735123824640 writing.c:77] FLOW write: server transport MOVE             writing.outgoing_window(65535) <-           global.outgoing_window(983041) giving 1048576
D0728 13:21:30.540272000 140735123824640 frame_window_update.c:116] FLOW parse: server stream[5] CREDIT               parsing.outgoing_window(0) by                   received_update(65535) giving 65535
D0728 13:21:30.540280000 140735123824640 frame_window_update.c:116] FLOW parse: server stream[3] CREDIT               parsing.outgoing_window(0) by                   received_update(65535) giving 65535
D0728 13:21:30.540285000 140735123824640 frame_window_update.c:116] FLOW parse: server stream[7] CREDIT               parsing.outgoing_window(0) by                   received_update(65535) giving 65535
D0728 13:21:30.540290000 140735123824640 frame_window_update.c:116] FLOW parse: server stream[1] CREDIT               parsing.outgoing_window(0) by                   received_update(65535) giving 65535
D0728 13:21:30.540298000 140735123824640 parsing.c:190] FLOW parsed: server stream[5] MOVE              global.outgoing_window(65535) <-           parsing.outgoing_window(65535) giving 131070
D0728 13:21:30.540304000 140735123824640 parsing.c:190] FLOW parsed: server stream[3] MOVE              global.outgoing_window(65535) <-           parsing.outgoing_window(65535) giving 131070
D0728 13:21:30.540309000 140735123824640 parsing.c:190] FLOW parsed: server stream[7] MOVE              global.outgoing_window(65535) <-           parsing.outgoing_window(65535) giving 131070
D0728 13:21:30.540315000 140735123824640 parsing.c:190] FLOW parsed: server stream[1] MOVE              global.outgoing_window(65535) <-           parsing.outgoing_window(65535) giving 131070
I0728 13:21:30.540330000 140735123824640 completion_queue.c:242] grpc_cq_end_op(exec_ctx=0x7fff53f3c480, cc=0x7fb575101420, tag=0x8000000000000000, error=null, done=0x10c63df23, done_arg=0x10d43ff98, storage=0x10d43ffc0)
E0728 13:21:30.540334000 140735123824640 completion_queue.c:244] Operation failed: tag=0x8000000000000000, error=null
I0728 13:21:30.540341000 140735123824640 completion_queue.c:513] RETURN_EVENT[0x7fb575101420]: OP_COMPLETE: tag:0x8000000000000000 OK
I0728 13:21:30.540701000 140735123824640 call_details.c:47] grpc_call_details_destroy(cd=0x7fb573c05780)
I0728 13:21:30.540710000 140735123824640 metadata_array.c:47] grpc_metadata_array_destroy(array=0x7fb573c06210)
I0728 13:21:30.540827000 140735123824640 call.c:1677] grpc_call_start_batch(call=0x7fb5740b7000, ops=0x7fb573c06fa0, nops=2, tag=0x8000000000000000, reserved=0x0)
I0728 13:21:30.540834000 140735123824640 call.c:1353] ops[0]: SEND_INITIAL_METADATA
I0728 13:21:30.540838000 140735123824640 call.c:1353] ops[1]: RECV_MESSAGE ptr=0x7fb573c06280
I0728 13:21:30.540842000 140735123824640 compression.c:155] grpc_compression_algorithm_for_level(level=1413827664)
E0728 13:21:30.540845000 140735123824640 compression.c:157] Unknown compression level 1413827664.
```

Client trace:

```
D0728 13:21:30.534631000 140735123824640 ev_posix.c:101] Using polling engine: poll
E0728 13:21:31.123614000 123145307131904 chttp2_transport.c:1810] close_transport: {"created":"@1469737291.123526000","description":"Failed parsing HTTP/2","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1726,"referenced_errors":[{"created":"@1469737291.123515000","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":233}]}
```

The error on the client side makes it look like this might be the same underlying issue as https://github.com/grpc/grpc/issues/7278.

**Comment by dgquintas** [comment]
@crclark , thanks. I'm having a look today. I seem to recall that this has been fixed on the pre-1.0.0. Would you mind testing against the "v1.0.x" branch?

**Comment by crclark** [comment]
Sure, I'll try to test against that branch and get back to you.

**Comment by crclark** [comment]
@dgquintas This still happens on branch `v1.0.x`. For some reason, though, `GRPC_TRACE` isn't working for me on that branch. Also, the client fails differently. I get an unavailable status code and the status details are:

```
{"created":"@1469740136.839567000","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}
```

**Comment by dgquintas** [comment]
@crclark yes, and I know why: at https://github.com/grpc/grpc/blob/master/src/core/lib/surface/call.c#L1412 , `effective_compression_level` is not initialized, and the following logic is such that it can remain so when there's no specification of the compression level from the channel or the call.

The fix is simply initializing `effective_compression_level` to `GRPC_COMPRESS_LEVEL_NONE`. I'm improving the tests to actually catch this error, on top of creating a PR with the fix in a matter of minutes. But just in case you wanted to quickly fix it.

Thanks for the report. This is "one of those things" and it would have been unfortunate if it'd made it into the 1.0 release :)

**Comment by dgquintas** [comment]
OTOH, `GRPC_TRACE` should be working as usual... I'll get back to you on that one.

**Comment by crclark** [comment]
@dgquintas Thanks for the quick reply. Unfortunately, I just rebuilt the library (v1.0.x) with the fix you suggested, and I'm still getting the same "unknown compression level" error. Let me know if you want me to try anything else.

**Comment by dgquintas** [comment]
@crclark `make install` as well? Perhaps the binary is picking up the old library file.

**Comment by crclark** [comment]
@dgquintas I added a printf under the changed line to make sure it's using my changed version. However, I just discovered that if I run the executable with valgrind, I don't get the error, so something strange might be going on. I'll keep digging.

**Comment by dgquintas** [comment]
BTW, a new environment variable `GRPC_VERBOSITY` was added in https://github.com/grpc/grpc/pull/7494 in order to control the amount of logging output. In order to get the former tracing behavior, one would have to do `GRPC_VERBOSITY=DEBUG GRPC_TRACE=all ...`

**Comment by dgquintas** [comment]
Some updates:

1. My previous comment still stands. The variable should be initialized. However, the problem wasn't there (its usage was always protected by `level_set`). The problem is actually [here](https://github.com/grpc/grpc/blob/release-0_15/include/grpc++/impl/codegen/call.h#L183). There needs to be a `maybe_compression_level_.is_set = false` in that default constructor. The reasons are somewhat involved, but they add up to there being a new way to set compression options via initial metadata as opposed to C++ cheating and (over)reaching into the C core.
2. There has been [a pending PR](https://github.com/grpc/grpc/pull/7502) with this and other changes (that fix the aforementioned C++ cheating). That's why all this seemed familiar. I'm merging it to master and backporting it to the v1.0.x branch today. I'd recommend picking up those changes, as it fixes everything The Right Way.

**Comment by crclark** [comment]
@dgquintas Would the fixes in https://github.com/grpc/grpc/pull/7502 help our library, which is only using the C library? I find it puzzling that this error occurs regardless of whether we set compression level in the grpc_channel_args.

**Comment by dgquintas** [comment]
@crclark hmm no, all I've been saying assumed C++. It's very surprising It happens when using only the C layer. Is there any way for me to repro? We run tests under msan for C, which should catch issues like this (which clearly look like an uninitialized variable issue).

**Comment by dgquintas** [comment]
@crclark hold on... here's where the issue may be. If you are dealing with the core directly, I assume you are assembling `grpc_op`s yourself, something like what happens [here](https://github.com/grpc/grpc/blob/master/test/core/end2end/tests/large_metadata.c#L145). If so, you have to _always_ memset your ops to zero. Otherwise, in this particular case, `op->data.send_initial_metadata.maybe_compression_level.is_set` can have a non-zero value, which would then cause `op->data.send_initial_metadata.maybe_compression_level.level` to be taken into account while it also contains uninitialized garbage`.

**Comment by dgquintas** [comment]
@yookyoung89 could you pull from master (now that #7502 has been merged) and try again? Thanks!

**Comment by crclark** [comment]
@dgquintas Aha! We had initially modeled our code off those tests, but I hadn't thought to look for changes to the tests in 0.15 when tracking down the problem. That fixed it for me. Sorry if I led you astray!

**Comment by dgquintas** [comment]
@crclark no worries! In fact we found the bad form of the initialized variable and it reminded me to merge and backport to v1.0.x the critical C++ fix mentioned (which I'm sure does explain the rest of the similar bug reports).

**Comment by dgquintas** [comment]
Marking as fixed.

**Comment by chakpongchung** [comment]
philips@z420:~/software/grpc/examples/cpp/helloworld$ ./greeter_server 
I0328 14:11:34.874821922     458 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
Server listening on 0.0.0.0:50051


philips@z420:~/software/grpc/examples/cpp/helloworld$ ./greeter_client 
14: Connect Failed
Greeter received: RPC failed


The following is my installation script:

git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
# git clone https://github.com/grpc/grpc
cd grpc
git submodule update --init
make -j$(nproc)
sudo make -j$(nproc) install

**Comment by LeTranAnhVu** [comment]
@chakpongchung 
metoo, please Team help me !!!
Thank!

**Comment by ncteisen** [comment]
Please specify:
- what version of gRPC you have installed
- what OS you are running on

Also please run with GRPC_VERBOSITY=DEBUG and GRPC_TRACE=all and paste the output

**Comment by GenuineJyn** [comment]
V1.4.3    && ubuntu 14.04

**Comment by GenuineJyn** [comment]
https://github.com/grpc/grpc/issues/9989

unset http_proxy

**Comment by LeTranAnhVu** [comment]
Yes you can use:
unset http_proxy
unset https_proxy
unset ftp_proxy
unset socks_proxy


But now it seem just work for me in the first several times , then when I use client to call server, it stuck. Not thing is showed and no "ask me failed" 
When I use :
ps aux | grep path/to/server or path/toclient

I saw that although I ctrl + z server or client already but They are not dead.
So I have to use : 

kill -9 

It work. But it is hard working.And I don't know how to get better way.
