### ISSUE TITLE
Failed at the grpc@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.

### ISSUE THREAD

**Issue by intralizee** [grpc/grpc#8495]
Hi, 

Attempting to npm install google-cloud with node v7.0.0 and npm install is returning a build error.

System:
macOS Sierra Version 10.12.1
node v7.0.0
npm v3.10.8

```
Psychedelices:Mademoiselle intralizee$ npm install --save google-cloud

> grpc@1.0.0 install /Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.0/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.0 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
  CC(target) Release/obj.target/grpc/src/core/lib/surface/init.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_args.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_stack.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/channel_stack_builder.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/compress_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/connected_channel.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/http_client_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/channel/http_server_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/compression/compression.o
  CC(target) Release/obj.target/grpc/src/core/lib/compression/message_compress.o
  CC(target) Release/obj.target/grpc/src/core/lib/debug/trace.o
  CC(target) Release/obj.target/grpc/src/core/lib/http/format_request.o
  CC(target) Release/obj.target/grpc/src/core/lib/http/httpcli.o
  CC(target) Release/obj.target/grpc/src/core/lib/http/parser.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/closure.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/endpoint.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/endpoint_pair_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/endpoint_pair_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/error.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/ev_epoll_linux.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/ev_poll_and_epoll_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/ev_poll_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/ev_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/exec_ctx.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/executor.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/iocp_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/iomgr.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/iomgr_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/iomgr_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/load_file.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/network_status_tracker.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/polling_entity.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/pollset_set_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/pollset_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/resolve_address_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/resolve_address_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/sockaddr_utils.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/socket_utils_common_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/socket_utils_linux.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/socket_utils_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/socket_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_client_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_client_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_server_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_server_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/tcp_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/time_averaged_stats.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/timer.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/timer_heap.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/udp_server.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/unix_sockets_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/unix_sockets_posix_noop.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/wakeup_fd_eventfd.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/wakeup_fd_nospecial.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/wakeup_fd_pipe.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/wakeup_fd_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/workqueue_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/iomgr/workqueue_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/json/json.o
  CC(target) Release/obj.target/grpc/src/core/lib/json/json_reader.o
  CC(target) Release/obj.target/grpc/src/core/lib/json/json_string.o
  CC(target) Release/obj.target/grpc/src/core/lib/json/json_writer.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/alarm.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/api_trace.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/byte_buffer.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/byte_buffer_reader.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/call.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/call_details.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/call_log_batch.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/channel.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/channel_init.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/channel_ping.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/channel_stack_type.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/completion_queue.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/event_string.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/lame_client.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/metadata_array.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/server.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/validate_metadata.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/version.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/byte_stream.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/connectivity_state.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/metadata.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/metadata_batch.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/static_metadata.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/transport.o
  CC(target) Release/obj.target/grpc/src/core/lib/transport/transport_op_string.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/bin_decoder.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/bin_encoder.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/chttp2_plugin.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_data.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_goaway.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_ping.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_rst_stream.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_settings.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/frame_window_update.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/hpack_encoder.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/hpack_parser.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/hpack_table.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/huffsyms.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/incoming_metadata.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/parsing.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/status_conversion.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/stream_lists.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/stream_map.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/timeout_encoding.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/varint.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/transport/writing.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/alpn/alpn.o
  CC(target) Release/obj.target/grpc/src/core/lib/http/httpcli_security_connector.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/context/security_context.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/composite/composite_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/credentials_metadata.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/fake/fake_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/google_default/credentials_posix.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/google_default/credentials_windows.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/google_default/google_default_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/iam/iam_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/jwt/json_token.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/jwt/jwt_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/jwt/jwt_verifier.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/oauth2/oauth2_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/plugin/plugin_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/credentials/ssl/ssl_credentials.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/client_auth_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/handshake.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/secure_endpoint.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/security_connector.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/server_auth_filter.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/transport/tsi_error.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/util/b64.o
  CC(target) Release/obj.target/grpc/src/core/lib/security/util/json_util.o
  CC(target) Release/obj.target/grpc/src/core/lib/surface/init_secure.o
  CC(target) Release/obj.target/grpc/src/core/lib/tsi/fake_transport_security.o
  CC(target) Release/obj.target/grpc/src/core/lib/tsi/ssl_transport_security.o
  CC(target) Release/obj.target/grpc/src/core/lib/tsi/transport_security.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/client/secure/secure_channel_create.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/channel_connectivity.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/client_channel.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/client_channel_factory.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/client_config.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/client_config_plugin.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/connector.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/default_initial_connect_string.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/initial_connect_string.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/lb_policy.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/lb_policy_factory.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/lb_policy_registry.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/parse_address.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/resolver.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/resolver_factory.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/resolver_registry.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/subchannel.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/subchannel_call_holder.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/subchannel_index.o
  CC(target) Release/obj.target/grpc/src/core/ext/client_config/uri_parser.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create.o
  CC(target) Release/obj.target/grpc/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.o
  CC(target) Release/obj.target/grpc/src/core/ext/lb_policy/grpclb/load_balancer_api.o
  CC(target) Release/obj.target/grpc/src/core/ext/lb_policy/grpclb/proto/grpc/lb/v1/load_balancer.pb.o
  CC(target) Release/obj.target/grpc/third_party/nanopb/pb_common.o
  CC(target) Release/obj.target/grpc/third_party/nanopb/pb_decode.o
  CC(target) Release/obj.target/grpc/third_party/nanopb/pb_encode.o
  CC(target) Release/obj.target/grpc/src/core/ext/lb_policy/pick_first/pick_first.o
  CC(target) Release/obj.target/grpc/src/core/ext/lb_policy/round_robin/round_robin.o
  CC(target) Release/obj.target/grpc/src/core/ext/resolver/dns/native/dns_resolver.o
  CC(target) Release/obj.target/grpc/src/core/ext/resolver/sockaddr/sockaddr_resolver.o
  CC(target) Release/obj.target/grpc/src/core/ext/load_reporting/load_reporting.o
  CC(target) Release/obj.target/grpc/src/core/ext/load_reporting/load_reporting_filter.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/context.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/gen/census.pb.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/grpc_context.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/grpc_filter.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/grpc_plugin.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/initialize.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/mlog.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/operation.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/placeholders.o
  CC(target) Release/obj.target/grpc/src/core/ext/census/tracing.o
  CC(target) Release/obj.target/grpc/src/core/plugin_registry/grpc_plugin_registry.o
  LIBTOOL-STATIC Release/libgrpc.a
  CC(target) Release/obj.target/gpr/src/core/lib/profiling/basic_timers.o
  CC(target) Release/obj.target/gpr/src/core/lib/profiling/stap_timers.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/alloc.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/avl.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/backoff.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cmdline.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cpu_iphone.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cpu_linux.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cpu_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/cpu_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/env_linux.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/env_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/env_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/histogram.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/host_port.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log_android.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log_linux.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/log_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/murmur_hash.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/slice.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/slice_buffer.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/stack_lockfree.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/string.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/string_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/string_util_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/string_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/subprocess_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/subprocess_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/sync.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/sync_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/sync_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/thd.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/thd_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/thd_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/time.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/time_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/time_precise.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/time_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/tls_pthread.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/tmpfile_msys.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/tmpfile_posix.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/tmpfile_windows.o
  CC(target) Release/obj.target/gpr/src/core/lib/support/wrap_memcpy.o
  LIBTOOL-STATIC Release/libgpr.a
  CXX(target) Release/obj.target/grpc_node/src/node/ext/byte_buffer.o
../src/node/ext/byte_buffer.cc:99:49: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
  Local<Object> fastBuffer = bufferConstructor->NewInstance(3, consArgs);
                                                ^
/Users/intralizee/.node-gyp/7.0.0/include/node/v8.h:3288:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
1 warning generated.
  CXX(target) Release/obj.target/grpc_node/src/node/ext/call.o
../src/node/ext/call.cc:616:20: error: no member named 'SetHiddenValue' in 'v8::Object'
      info.This()->SetHiddenValue(Nan::New("channel_").ToLocalChecked(),
      ~~~~~~~~~~~  ^
../src/node/ext/call.cc:624:69: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    MaybeLocal<Object> maybe_instance = constructor->GetFunction()->NewInstance(
                                                                    ^
/Users/intralizee/.node-gyp/7.0.0/include/node/v8.h:3288:31: note: 'NewInstance' has been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
1 warning and 1 error generated.
make: *** [Release/obj.target/grpc_node/src/node/ext/call.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/grpc
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.1.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/grpc
node-pre-gyp ERR! node -v v7.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/Users/intralizee/Development/GitHub/Mademoiselle/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary' (1)
Mademoiselle@0.0.0 /Users/intralizee/Development/GitHub/Mademoiselle
└── (empty)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "google-cloud"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/intralizee/Development/GitHub/Mademoiselle/npm-debug.log
npm ERR! code 1
```

**Comment by murgatroid99** [comment]
Thank you for the report. That error was fixed in #8220, and the warning was fixed in #7738, so this should work in the next release.

**Comment by massimiliano-delia** [comment]
Hello, please can You give us a release schedule?

When the next release will be available?

Thank You!

**Comment by Kenblair1226** [comment]
+1, if it will not release within the next few days, I gonna figure out a work around for this.

Thanks!

**Comment by ssmoon** [comment]
grpc in windows 10 also encounter some errors during node-pre-gyp phrase under nodejs 7.0.
when downgrade to node 6.9, everything goes fine.
Hope it will be fixed in next release.

**Comment by asktalk** [comment]
pls fixed the bug, thank you!

**Comment by randunel** [comment]
Similar *but not identical* error on linux.

```
  CXX(target) Release/obj.target/grpc_node/src/node/ext/byte_buffer.o
../src/node/ext/byte_buffer.cc: In function ‘v8::Local<v8::Value> grpc::node::MakeFastBuffer(v8::Local<v8::Value>)’:
../src/node/ext/byte_buffer.cc:99:72: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/mihai/.node-gyp/7.0.0/include/node/v8.h:3287): Use maybe version [-Wdeprecated-declarations]
   Local<Object> fastBuffer = bufferConstructor->NewInstance(3, consArgs);
                                                                        ^
  CXX(target) Release/obj.target/grpc_node/src/node/ext/call.o
../src/node/ext/call.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE grpc::node::Call::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node/ext/call.cc:616:20: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’
       info.This()->SetHiddenValue(Nan::New("channel_").ToLocalChecked(),
                    ^
../src/node/ext/call.cc:625:19: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /home/mihai/.node-gyp/7.0.0/include/node/v8.h:3287): Use maybe version [-Wdeprecated-declarations]
         argc, argv);
                   ^
make: *** [Release/obj.target/grpc_node/src/node/ext/call.o] Error 1
make: Leaving directory `/home/mihai/projects/inventures/roxi-frontend/node_modules/google-cloud/node_modules/grpc/build'
gyp ERR! build error 
```

Should I open a new issue?

**Comment by murgatroid99** [comment]
Those are the warnings that were fixed in #7738.

Version 1.0.1 has been released with the fix for this issue.

**Comment by jcastill0** [comment]
I tried to run npm install grpc on both MacOS and Ubuntu 16 but keep getting the same error shown above. I will open a new issue as I see this closed as it tried to find grpc@1.0.1 but didn't find it.

**Comment by matiishyn** [comment]
Having the same issue.
downgrading to node 6.9 fixed it.
Please let us know when fix is released

**Comment by otymartin** [comment]
@murgatroid99 this error still exists in node 7.3

**Comment by Kenblair1226** [comment]
Confirmed issue still exists with node 7.2 and 7.3.
Node 6.9 works fine.

**Comment by jab** [comment]
Tried with Node 7.5.0 and hit this issue with that version too.

**Comment by murgatroid99** [comment]
grpc 1.1 should work on Node 7 now

**Comment by jab** [comment]
@murgatroid99 Thanks! Will try that shortly, but in the meantime, looks like a tag for 1.1 still needs to be cut (and any release notes added) so it appears under https://github.com/grpc/grpc/releases - currently shows v1.1.0-pre1 as latest.

**Comment by Maijied** [comment]
Just downgrade your Node.js version .
And try to use node-v6.9.0 version.
