### ISSUE TITLE
Ruby Server Returns UNKNOWN, Should Return UNIMPLEMENTED

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#9188]
When a client attempts to call a Ruby service method that is defined in the proto file, but not implemented by the service, it receives a status code UNKNOWN, with the message: "unkown error handling call on server". The client should receive UNIMPLEMENTED for this situation.

To demonstrate this behavior on the current master branch, first run:
```src/ruby/pb/generate_proto_ruby.sh```
This makes sure the generated Ruby code is up to date with the most current src/proto/grpc/testing/test.proto. This is important because test.proto was updated to include TestService/UnimplementedCall and the Ruby file test_services_pb.rb has not yet picked up that change.

Then start a Ruby service:
```src/ruby/pb/test/server.rb --port 8080```

Then run any interop client against the server. For example, in c++:
```
bins/opt/interop_client 
  --server_host=127.0.0.1 
  --server_host_override=localhost 
  --server_port=8080 
  --test_case=unimplemented_method
```

The test will fail since the server does not respond with an UNIMPLEMENTED status code.

**Comment by apolcyn** [comment]
I think this should actually be fixed by https://github.com/grpc/grpc/pull/9034.

The issue it fixed was the base service class defined the method that returns unimplemented in CamelCase (as in the generated service class) rather than snake case.

**Comment by ncteisen** [comment]
I am still seeing the faulty behavior, even on the most current version of master

**Comment by ncteisen** [comment]
Looks like that fix allowed the server to still run, even if it hadn't implemented all of the methods defined in the proto, but the server does not fail in the right way if the unimplemented method is called. 

Looks to me like the error occurs right [here](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/rpc_desc.rb#L67) (at least in the case I am testing, which is a unary_unary call). The call method would usually take two args, but in the case of the unimplemented method it takes zero

**Comment by apolcyn** [comment]
thanks, saw the handler had wrong arity
