### ISSUE TITLE
Cannot install on Windows machine - npm errors

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#9311]
_From @jonair on January 11, 2017 16:35_

Hi there 

#### Environment details

  - OS: Windows 8.1 Pro
  - Node.js version: 
  - npm version: 
  - google-cloud-node version: ? won't install

#### Steps to reproduce

  1. npm install google-cloud --save

Get the errors shown in attached log and a very full DOS window:

node-pre-gyp ERR! Tried to download(404): https://storage.googleapis.com/grpc-pr
ecompiled-binaries/node/grpc/v1.0.1/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.1 and node@7.3.0 (no
de-v51 ABI) (falling back to source compile with node-gyp)

C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits\node_modules\google-cloud\node
_modules\grpc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\
node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
clean )  else (node "" clean )

C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits\node_modules\google-cloud\node
_modules\grpc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\
node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
configure --fallback-to-build --module=C:\Users\jon.air.SPARKOL\Dropbox\Projects
\ritbits\node_modules\google-cloud\node_modules\grpc\src\node\extension_binary\g
rpc_node.node --module_name=grpc_node --module_path=C:\Users\jon.air.SPARKOL\Dro
pbox\Projects\ritbits\node_modules\google-cloud\node_modules\grpc\src\node\exten
sion_binary )  else (node "" configure --fallback-to-build --module=C:\Users\jon
.air.SPARKOL\Dropbox\Projects\ritbits\node_modules\google-cloud\node_modules\grp
c\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path
=C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits\node_modules\google-cloud\nod
e_modules\grpc\src\node\extension_binary )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\jon.air.SPARKOL\AppData\Local\
Programs\Python\Python36-32\python.exe" is v3.6.0, which is not supported by gyp
.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:202:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:501:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=C:\\Users\\jon.air.SPARKOL\\Dropbox\\Projects\\ritbi
ts\\node_modules\\google-cloud\\node_modules\\grpc\\src\\node\\extension_binary\
\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\jon.air.SPA
RKOL\\Dropbox\\Projects\\ritbits\\node_modules\\google-cloud\\node_modules\\grpc
\\src\\node\\extension_binary"
gyp ERR! cwd C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits\node_modules\goog
le-cloud\node_modules\grpc
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits\node_mod
ules\google-cloud\node_modules\grpc\src\node\extension_binary\grpc_node.node --m
odule_name=grpc_node --module_path=C:\Users\jon.air.SPARKOL\Dropbox\Projects\rit
bits\node_modules\google-cloud\node_modules\grpc\src\node\extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\jon.air.SPARKO
L\Dropbox\Projects\ritbits\node_modules\google-cloud\node_modules\node-pre-gyp\l
ib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jon.
air.SPARKOL\\Dropbox\\Projects\\ritbits\\node_modules\\google-cloud\\node_module
s\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits\node_mod
ules\google-cloud\node_modules\grpc
node-pre-gyp ERR! node -v v7.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\
jon.air.SPARKOL\Dropbox\Projects\ritbits\node_modules\google-cloud\node_modules\
grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_p
ath=C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits\node_modules\google-cloud\
node_modules\grpc\src\node\extension_binary' (1)
ritbits@0.0.1 C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits
`-- (empty)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "google-cloud" "--save"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.0.1 install script 'node-pre-gyp install --fallbac
k-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits\npm-debug.log
npm ERR! code 1

C:\Users\jon.air.SPARKOL\Dropbox\Projects\ritbits>

Help much appreciated - another blockage on my way to victory!

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1917_

**Comment by stephenplusplus** [comment]
_From @jonair on January 11, 2017 16:35_

[npm-debug.log.txt](https://github.com/GoogleCloudPlatform/google-cloud-node/files/699436/npm-debug.log.txt)

**Comment by murgatroid99** [comment]
We don't yet have precompiled binaries for Node 7. I expect that those will be released very soon, then this should work again.

**Comment by jonair** [comment]
So is there no solution for me to use google cloud? Can I move to a version of Node that will allow this project to continue and not just stop?

**Comment by jonair** [comment]
COOL - I've gone to node 6.9.4 and all is installed - thank you!

**Comment by murgatroid99** [comment]
We have now released a new version. You should now be able to use grpc@1.1.0-pre1 with Windows and Node 7.

**Comment by joelharkes** [comment]
It still can't find the pre compiled libraries and downloads them:

```
> grpc@1.0.1 install C:\hs\hs-platform-web\node_modules\@google-cloud\common\node_modules\grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.1/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.1 and node@7.4.0 (node-v51 ABI) (falling back to source compile with node-gyp)

C:\hs\hs-platform-web\node_modules\@google-cloud\common\node_modules\grpc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
```

node 7.4
npm 4.0.5

package.json:

```
"dependencies": {
    "@google-cloud/logging": "^0.6.1",
    "amqplib": "0.5.1",
    "body-parser": "1.16.0",
    "config": "1.24.0",
    "express": "4.14.0",
    "express-stormpath": "3.1.8",
    "grpc": "1.1.0-pre1",
    "mongoose": "4.7.7",
    "morgan": "1.7.0",
    "mssql": "3.3.0",
    "node-uuid": "1.4.7",
    "redis": "2.6.5",
    "request": "2.79.0"
  },
```

**Comment by murgatroid99** [comment]
I notice that even though you updated your dependency on grpc to 1.1.0-pre1, npm is still installing 1.0.1 as the sub-dependency for `@google-cloud/common`. Until they update their dependency and/or we publish 1.1.0, I'm not sure how to force a package to use a different version of a library as a sub-dependency.

**Comment by murgatroid99** [comment]
grpc@1.1.0 has now been published to npm, so I believe that `@google-cloud/common` should now pick it up automatically. This should work now. If it doesn't please reopen the issue.

**Comment by DmitryEfimenko** [comment]
Seems like this is still an issue. `@google-cloud/common` installs just fine on its own, but if I try to install `google-common`, it attempts to install grpc@1.0.1, and fails.
I'm on node 7.5.0

**Comment by jwuliger** [comment]
I am also having this issue on windows 10, node 7.

Here is a snippet of my log:

```
MINGW64 ~/Desktop/vanilla-firebase-app/functions
$ npm i
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> grpc@1.0.1 install C:\Users\Jared Wuliger\Desktop\vanilla-firebase-app\functions\node_modules\google-gax\node_modules\grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.0.1/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.0.1 and node@7.10.0 (node-v51 ABI) (falling back to source compile with node-gyp)
```

**Comment by murgatroid99** [comment]
grpc 1.0 was released before Node 7. You should upgrade your version of grpc to have compatibility with Node 7.
