### ISSUE TITLE
ALL Ruby tests on Mac are broken with error "bundle: command not found"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9560]
Seen here: https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2398/testReport/junit/(root)/aggregate_tests/run_tests_ruby_macos_opt/

```
+ export GRPC_CONFIG=opt
+ GRPC_CONFIG=opt
++ dirname tools/run_tests/helper_scripts/pre_build_ruby.sh
+ cd tools/run_tests/helper_scripts/../../..
+ bundle install
tools/run_tests/helper_scripts/pre_build_ruby.sh: line 39: bundle: command not found

FLAKE: tools/run_tests/helper_scripts/pre_build_ruby.sh [ret=127, pid=1891]
+ export GRPC_CONFIG=opt
+ GRPC_CONFIG=opt
++ dirname tools/run_tests/helper_scripts/pre_build_ruby.sh
+ cd tools/run_tests/helper_scripts/../../..
+ bundle install
tools/run_tests/helper_scripts/pre_build_ruby.sh: line 39: bundle: command not found

FAILED: tools/run_tests/helper_scripts/pre_build_ruby.sh [ret=127, pid=1894]
```

It seems that this has been happening on master builds and it's failing consistently.

Some of previous master build report this issue when running `pre_build_ruby.sh`:

```
fatal: No live threads left. Deadlock?
2 threads, 2 sleeps current:0x007fda38c08cd0 main thread:0x007fda38c08cd0
* #<Thread:0x007fda39068a90 sleep_forever>
   rb_thread_t:0x007fda38c08cd0 native:0x007fff78a1a300 int:0
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:43:in `pop'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:43:in `deq'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:102:in `call'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:77:in `call'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer.rb:199:in `install_in_parallel'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer.rb:166:in `install'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer.rb:80:in `run'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer.rb:24:in `install'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli/install.rb:70:in `run'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:181:in `block in install'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/settings.rb:99:in `temporary'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:180:in `install'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
   /usr/local/rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
   /usr/local/rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
   /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
   /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
* #<Thread:0x007fda413e7d58@Parallel Installer Worker #0@/usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:88 sleep_forever>
   rb_thread_t:0x007fda4204c030 native:0x0000010da4c000 int:0
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:56:in `pop'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:56:in `block in process_queue'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:55:in `loop'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:55:in `process_queue'
   /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:88:in `block (2 levels) in create_threads'

  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:43:in `pop'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/worker.rb:43:in `deq'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:131:in `process_specs'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:102:in `call'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer/parallel_installer.rb:77:in `call'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer.rb:199:in `install_in_parallel'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer.rb:166:in `install'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer.rb:80:in `run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/installer.rb:24:in `install'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli/install.rb:70:in `run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:181:in `block in install'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/settings.rb:99:in `temporary'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:180:in `install'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:20:in `dispatch'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/cli.rb:11:in `start'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/exe/bundle:32:in `block in <top (required)>'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /usr/local/rvm/gems/ruby-2.4.0/gems/bundler-1.14.3/exe/bundle:24:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
  /usr/local/rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
  /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
  /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'


FAILED: tools/run_tests/helper_scripts/pre_build_ruby.sh [ret=1, pid=4845]
```

**Comment by jtattermusch** [comment]
https://grpc-testing.appspot.com/job/gRPC_master_macos/1424

**Comment by apolcyn** [comment]
I forgot to reinstall bundler on all but one of the mac workers when updating yesterday - just reinstalled I think this should work now.

**Comment by jtattermusch** [comment]
Seems it is still broken:
https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/2420/

**Comment by apolcyn** [comment]
the latest `bundle` errors on mac is now due to a known issue in `bundler` - command is there but it's crashing on ruby 2.4

https://github.com/grpc/grpc/pull/9553 fixes this error

**Comment by jtattermusch** [comment]
Seems fixed?

**Comment by apolcyn** [comment]
the main error is still there and will be fixed once ruby protobuf 3.2 gem is published (should run on ruby 2.4). 
turned them off on master for the time being in #9589, but it will still happen on v1.1.x

**Comment by jtattermusch** [comment]
any updates?

**Comment by apolcyn** [comment]
should be fixed now, re-enabling ruby tests on mac in https://github.com/grpc/grpc/pull/9814
